### ISSUE TITLE
兼容性问题

### ISSUE THREAD

**Issue by menoly123456** [mushan0x0/AI0x0.com#102]
安装之后提示暂不支持你的系统，我的win7的

**Comment by mcyrj** [comment]
我的是macos-12。大哥，12的系统很多。因为好多软件13是不兼容的。

**Comment by Darling-Lee** [comment]
12系统才哪跟哪啊，苹果对10.15都还没放弃，就直接放弃12。太多人不敢升13了。。。。

**Comment by Darling-Lee** [comment]
而且放弃就算了，还动不动提示人升级。就不能在计划新版本放弃之前在旧版本加个系统版本判断？不符合就不提示升级？

**Comment by fengerwoo** [comment]
升级不能升级，新版只兼容macOS 13系统，现在的v1.2.3，BaiGPT 直接也不让用 说401

**Comment by mushan0x0** [comment]
win7和macos以下暂不兼容
