### ISSUE TITLE
我电脑已经科学上网，但是无法使用chatgpt

### ISSUE THREAD

**Issue by ryswork1993** [mushan0x0/AI0x0.com#105]
已经科学上网
<img width="722" alt="image" src="https://user-images.githubusercontent.com/44529247/228106772-6523bf32-f85d-4877-96ef-b7bca8fa8648.png">
选择chatgpt无法正常打开
![image](https://user-images.githubusercontent.com/44529247/228107022-62c2733d-dbbf-4397-b7a5-969f2024af20.png)

**Comment by MCMCMCMCMCMCMCCMCM** [comment]
我也一样情况~耐心等待吧~开发者应该在努力解决我们的反馈的

**Comment by mushan0x0** [comment]
开了代理就可以把加速关掉了，加速用的人太多了
