### ISSUE TITLE
有没有定时刷新功能呀

### ISSUE THREAD

**Issue by kkxg** [mushan0x0/AI0x0.com#107]
我知道网页版使用的时候也有需要刷新的问题。我已经带的有梯子了，使用它之前还是需要刷新。请问有没有定时刷新的功能呢？比如我自己浏览器设置的就是十分钟，然后想用的时候随时能用。。。不用等它刷新。

**Comment by mushan0x0** [comment]
1.3.5已设置为15分钟刷新
