### ISSUE TITLE
怎么连不上

### ISSUE THREAD

**Issue by baby8091** [mushan0x0/AI0x0.com#108]
<img width="662" alt="屏幕截图 2023-03-28 140610" src="https://user-images.githubusercontent.com/129147860/228143648-4f13e91d-3af2-447c-bda1-955c0814fad8.png">

**Comment by 2534231739** [comment]
我也是这样的情况

**Comment by Emotional123** [comment]
我也是

**Comment by greedhand** [comment]
加1

**Comment by mushan0x0** [comment]
点悬浮球的刷新按钮点快点多点几次，用的人太多，要挤进去

**Comment by 2534231739** [comment]
> 点悬浮球的刷新按钮点快点多点几次，用的人太多，要戳进去

是在点击谷歌账号登录的是弹出加载失败
