### ISSUE TITLE
关于悬浮球的一些反馈

### ISSUE THREAD

**Issue by huangxin8899** [mushan0x0/AI0x0.com#11]
1.悬浮球可以加隐藏功能；
2.目前悬浮球好像并不能移至副屏；
3.鼠标悬浮在悬浮球上的提示建议设为点击才出现；

**Comment by mushan0x0** [comment]
收到

**Comment by liubiao520** [comment]
还有那个查询模式和输入模式的快捷键可以自定义就好了，我平时查询的多，习惯就会按回车，经常不注意就让聊天框、文章这些给被回答填满，替换了，希望建议被采纳，辛苦了

**Comment by mushan0x0** [comment]
谢谢，我会考虑出一个默认查询还是输入的设置的🙏

**Comment by mushan0x0** [comment]
目前已经是回车默认查询模式了
