### ISSUE TITLE
怎么将代理写入文件

### ISSUE THREAD

**Issue by Yxnh-Cj** [mushan0x0/AI0x0.com#110]

**Comment by mushan0x0** [comment]
开启代理，把加速关掉，就会走你的代理了

**Comment by Yxnh-Cj** [comment]
谢谢回答，现在的问题是全局代理没问题，就是怎么将地址+端口写入文件，就不需要开启全局代理了。

**Comment by mushan0x0** [comment]
不用开全局，应该是你的代理没有把baichat和chatgpt的地址代理上 https://chat.theb.ai/#/chat/1002 把这个加到代理名单里吧

**Comment by Yxnh-Cj** [comment]
谢谢回复，就是我用的clash for windows端口是7890，我想写到安装后的配置文件，如config中，例：127.0.0.1:7890不清楚在哪加入，重启这个软件就会自动走这个端口代理。

**Comment by Yxnh-Cj** [comment]
![image](https://user-images.githubusercontent.com/93480778/228490233-97439663-34d3-4e2c-ba02-ad0b5387cd11.png)
ruhe如何能把国外的AI走这个代理，国内直连就行，但不清楚在哪加。

**Comment by Yxnh-Cj** [comment]
不能直接在C盘的Roaming文件
![image](https://user-images.githubusercontent.com/93480778/228493406-e24c6ae4-3ec7-47e4-9c5b-b9ad90a6da75.png)
中设置吗，还是只能在
![image](https://user-images.githubusercontent.com/93480778/228491690-601793fa-fc6e-4087-baaf-8cf0b4d983ff.png)
设置。

**Comment by Yxnh-Cj** [comment]
![image](https://user-images.githubusercontent.com/93480778/228493509-a6c0cff5-276d-47be-987e-9d2b171af0c6.png)

只有开启
![image](https://user-images.githubusercontent.com/93480778/228493767-c0586c19-2b2f-44f0-a625-e056c872e7a7.png)
的时候才能进去。
![image](https://user-images.githubusercontent.com/93480778/228493859-cd78a5a9-6b1e-4604-8ccf-2db1d46f78c7.png)

**Comment by Yxnh-Cj** [comment]
请问如何直接加入到配置文件中，因为0x0设置中没有这一项。
