### ISSUE TITLE
启动后最小化到系统托盘

### ISSUE THREAD

**Issue by Sunshagon** [mushan0x0/AI0x0.com#112]
如题，我所有的开机启动的东西都由一个软件管理着，开机后，我设置了让它开机自启 ，然后它帮我把其他的软件依次启动。我设置了让它帮我自动AI0x0，但是启动后，界面就弹出来了，但此时我不用ai0x0，所以需要关闭界面。
所以，我想说可以不可以，增加一个选项，让它"启动后最小化到系统托盘"

**Comment by mushan0x0** [comment]
弹出的啥界面，悬浮球吗，你想默认启动不显示悬浮球吗

**Comment by Sunshagon** [comment]
> 弹出的啥界面，悬浮球吗，你想默认启动不显示悬浮球吗

我想的是可以启动后，不弹出应用界面，可以最小化到托盘。
因为我设置了某个软件开机启动，而这个软件可以定时设置别的软件启动，我用它来自启AI  0x0。
但是AI  0x0启动后，它的应用界面就弹出来了，而我又没有使用需求，只能先把他的界面关掉，最小化到托盘。等我有使用需求了，再快捷键唤出。
所以我想大佬，能不能在设置里增加个选项，类似这种：
![image](https://user-images.githubusercontent.com/43169575/228489052-47ab1544-a709-4663-bab2-65497f8492fb.png)

**Comment by mushan0x0** [comment]
现在弹出的是啥应用界面

**Comment by Sunshagon** [comment]
> 现在弹出的是啥应用界面

就是正常的首页啊

**Comment by Sunshagon** [comment]
> 现在弹出的是啥应用界面

另外，这个Chat0x0的界面字体可以优化下嘛🤣🤣🤣，现在Chat0x0的字体如图：
![image](https://user-images.githubusercontent.com/43169575/228559838-97af4228-27c9-4819-a8c9-5cc72c91bb9d.png)


而下面是ChatGPT的字体：
![image](https://user-images.githubusercontent.com/43169575/228559955-a591c0a6-c4ba-4c47-956c-3dff216715a4.png)

**Comment by mushan0x0** [comment]
这个暂不考虑缩小到托盘。。
