### ISSUE TITLE
输入问题后没有反应

### ISSUE THREAD

**Issue by whckcs** [mushan0x0/AI0x0.com#114]
ctrl2在悬浮球上输入问题，或者选中文字后选择预设，按回车都没有反应，打开主界面一看才发现问题还在输入框里，没有发送

**Comment by whckcs** [comment]
好像更新后就是这样，我切回上一个版本试试

**Comment by mushan0x0** [comment]
你是啥系统的

**Comment by whckcs** [comment]
win11，切回上一个版本试了一下也是这样，不知道啥原因

**Comment by mushan0x0** [comment]
你用的文心一言吗

**Comment by mushan0x0** [comment]
你用的文心一言吗

**Comment by whckcs** [comment]
就是chatgpt

**Comment by whckcs** [comment]
> 你用的文心一言吗

哦对了说起这个我用的baichat也打不开，之前是可以打开的，我感觉还挺好用，速度比较快

**Comment by whckcs** [comment]
> 你用的文心一言吗

反映一下，开了tz后baichat可以用了，而且用baichat的话悬浮窗和选中文字用预设都是可以正常使用的，但是chatgpt就不行，选中文字后需要打开主界面手动发送。

**Comment by mushan0x0** [comment]
1.3.5已修复

**Comment by whckcs** [comment]
ok
