### ISSUE TITLE
话题名称无法修改，点击修改，名称自动变成ai0x02023&，无法删除这个名称，也无法增加字符

### ISSUE THREAD

**Issue by edisonzf2020** [mushan0x0/AI0x0.com#115]
系统win11，ai0x0 1.2.6版本

**Comment by mushan0x0** [comment]
啥话题名称，可以截图吗

**Comment by edisonzf2020** [comment]
![2023-03-31 113050](https://user-images.githubusercontent.com/95912883/229016084-84d4c983-3d2c-42f5-8922-fce7cb0b0c3c.jpg)

**Comment by mushan0x0** [comment]
已修复
