### ISSUE TITLE
[BUG]Al 登录时出现“由于找不到ffmpeg.dll，无法继续执行代码。重新安装程序可能会解决此问题”而登录不了

### ISSUE THREAD

**Issue by aymm2007** [mushan0x0/AI0x0.com#116]
[BUG]Al 登录时出现“由于找不到ffmpeg.dll，无法继续执行代码。重新安装程序可能会解决此问题”而登录不了

**Comment by mushan0x0** [comment]
系统截图啥的提供一下吧。。

**Comment by mushan0x0** [comment]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/29084441/229101098-6912b271-71c4-436a-9a11-78d17746f191.png">
本地环境导致的
