### ISSUE TITLE
[Feature]添加代理配置，否则我被迫开全局

### ISSUE THREAD

**Issue by shin701** [mushan0x0/AI0x0.com#118]
**您的功能请求是否与问题有关？请描述。**  
提供清晰简洁的问题描述。例如："每当......，我总是感到沮丧。"

**描述您想要的解决方案**  
提供清晰简洁的解决方案描述。

**描述您已考虑过的替代方案**  
提供清晰简洁的替代方案或特性说明。

**附加上下文**  
在这里添加有关功能请求的任何其他上下文或截图。

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/issues/110#issuecomment-1488273247 开启系统代理，关闭加速就行了
