### ISSUE TITLE
[BUG]很难进去，进去也基本用不了

### ISSUE THREAD

**Issue by lanjinzhoucode** [mushan0x0/AI0x0.com#121]
**描述错误**
之前登录状态，今天突然打开刚开始是进不去，后来直接要重新登录，输入之前注册的账密码也进不去，后来找回密码，验证码也收到了，输入验证码提示网络错误

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
试试1.3.4呢
