### ISSUE TITLE
[BUG]打不开，进入不了；

### ISSUE THREAD

**Issue by sunlinebox** [mushan0x0/AI0x0.com#123]
**描述错误**
清晰而简明地描述错误是什么。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：MacOs Big sur
 - 系统版本：11.7.3

**其他上下文**

➜  android-33 /Applications/AI\ 0x0.app/Contents/MacOS/AI\ 0x0  
<span style="caret-color: rgb(112, 114, 123); color: rgb(112, 114, 123); font-family: PingFangSC-Regular; font-size: 12px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration: none; display: inline !important; float: none;">lizhaomei</span>
10:13:52.614 › (node:97584) UnhandledPromiseRejectionWarning: Error: Command failed: sw_vers -ProductVersion
    at checkExecSyncError (node:child_process:865:11)
    at execSync (node:child_process:936:15)
    at node:electron/js2c/asar_bundle:2:12711
    at isSupportedOS (/Applications/AI 0x0.app/Contents/Resources/app.asar/dist-electron/main/index.js:96:55)
    at /Applications/AI 0x0.app/Contents/Resources/app.asar/dist-electron/main/index.js:106:8
(Use `AI 0x0 --trace-warnings ...` to show where the warning was created)
10:13:52.619 › (node:97584) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by mushan0x0** [comment]
11还没支持的

**Comment by mushan0x0** [comment]
1.3.5已修复，但是macos13一下版本没有支持，会有问题
