### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by zhou1831868** [mushan0x0/AI0x0.com#126]
**描述错误**
收费模式的版本一更新，悬浮球在跳来跳去，鼠标移到悬浮球就消失了，移道别的地方又正常

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：Windows
 - 系统版本 11

**Comment by mushan0x0** [comment]
你是双屏吗

**Comment by zhou1831868** [comment]
> 

是的

**Comment by zhou1831868** [comment]
> 你是双屏吗

是的
