### ISSUE TITLE
桌面有2个悬浮窗

### ISSUE THREAD

**Issue by HNYDDDTONY** [mushan0x0/AI0x0.com#127]
**描述错误**
最新版本更新之后桌面生成了两个悬浮窗

**截图**
![image](https://user-images.githubusercontent.com/129500120/229078203-d1b870b9-7896-422a-bbb6-01641d3050cb.png)

**系统（请填写以下信息）：**
 - 系统名称：Windows 11
 - 系统版本 20H2

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
你是多屏幕吗，试试1.3.4版本吧，先把多屏幕模式屏蔽了

**Comment by HNYDDDTONY** [comment]
![image](https://user-images.githubusercontent.com/129500120/229096235-f85fa634-b58e-4d83-a0a9-bfe29ab7e65d.png)
还是2个

**Comment by mushan0x0** [comment]
重启电脑看看可以吗

**Comment by ShenShizhe** [comment]
![2](https://user-images.githubusercontent.com/94941582/229098412-baee79e7-5061-4a3a-bedc-519af14dc745.png)
哈哈哈，我卡了一下之后就两个了，拖了一下变三个了，哈哈哈

**Comment by mushan0x0** [comment]
> ![2](https://user-images.githubusercontent.com/94941582/229098412-baee79e7-5061-4a3a-bedc-519af14dc745.png) 哈哈哈，我卡了一下之后就两个了，拖了一下变三个了，哈哈哈

加量不加价

**Comment by ShenShizhe** [comment]
> > ![2](https://user-images.githubusercontent.com/94941582/229098412-baee79e7-5061-4a3a-bedc-519af14dc745.png) 哈哈哈，我卡了一下之后就两个了，拖了一下变三个了，哈哈哈
> 
> 加量不加价

不敢动了，重启没了，哈哈哈，哥，咱还是把之前的隐藏悬浮窗的功能加回来吧，这样我就不用管他变几个了

**Comment by mushan0x0** [comment]
隐藏悬浮窗跟现在有些功能用冲突，可以试试贴边隐藏功能

**Comment by HNYDDDTONY** [comment]
其中一个悬浮球有的时候会让除了任务栏的其他部分都点不了，点一下任务栏就好了

**Comment by HNYDDDTONY** [comment]
![image](https://user-images.githubusercontent.com/129500120/229130169-b80b40b8-9243-41d5-90ec-7a431afc25e6.png)
我也有三个了，哈哈哈哈

**Comment by mushan0x0** [comment]
@HNYDDDTONY 重起后可以吗😂

**Comment by ShenShizhe** [comment]
> ![image](https://user-images.githubusercontent.com/129500120/229130169-b80b40b8-9243-41d5-90ec-7a431afc25e6.png) 我也有三个了，哈哈哈哈

加入光荣的进化吧！！哈哈哈

**Comment by HNYDDDTONY** [comment]
我都重装软件了，还是不行
