### ISSUE TITLE
鼠标随航问题

### ISSUE THREAD

**Issue by tomdbtel** [mushan0x0/AI0x0.com#13]
鼠标随航功能很好，但是感觉还是有一些缺陷，建议是在特定位置或者内容选择时加载，而不是点击后就立即出现。比如类似某文本翻译工具，需要选定一段文字后出现翻译框。这里我觉得在选定一些需要操作的内容后，或者鼠标指向某些内容后，按某个快捷键来唤醒随航，其余时间则自动隐藏。

**Comment by mushan0x0** [comment]
是的，这个还在优化🙏
