### ISSUE TITLE
[BUG]付费用户可以用GPT4吗

### ISSUE THREAD

**Issue by whckcs** [mushan0x0/AI0x0.com#130]
**描述错误**
清晰而简明地描述错误是什么。
出付费模式了，还有点贵，看到接口里有gpt4，付费用户可以使用吗，有没有什么限制？
**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
用不起，设置后后请求错误
