### ISSUE TITLE
用户体验优化,就是这个跟随导航，应该是监听的是文字是否被选中，而不是长按鼠标左键，这样就不会再拖动窗口就弹出那个搜索框。这样的体验会好点

### ISSUE THREAD

**Issue by xiangedi** [mushan0x0/AI0x0.com#132]
**您的功能请求是否与问题有关？请描述。**  
提供清晰简洁的问题描述。例如："每当......，我总是感到沮丧。"

**描述您想要的解决方案**  
提供清晰简洁的解决方案描述。

**描述您已考虑过的替代方案**  
提供清晰简洁的替代方案或特性说明。

**附加上下文**  
在这里添加有关功能请求的任何其他上下文或截图。

**Comment by mushan0x0** [comment]
随航是长按触发的，以后还有别的用，所以不能用选中文字来判断
