### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jyj12345** [mushan0x0/AI0x0.com#133]
**描述错误**
1.3版本的悬浮球会在鼠标经过时消失

**截图**

https://user-images.githubusercontent.com/68804563/229142465-0a969190-ae54-4260-b139-7caf1c0f63d3.mp4

**系统（请填写以下信息）：**
 - 系统名称：Windows 
 - 系统版本 [11家庭中文版 Insider Preview 25330.1000]

**Comment by mushan0x0** [comment]
收到，已经在看了

**Comment by mushan0x0** [comment]
1.3.5应该已修复了
