### ISSUE TITLE
网络加速BUG

### ISSUE THREAD

**Issue by IMCHALELE** [mushan0x0/AI0x0.com#134]
**描述错误**
启用网络加速并点击提交，关闭窗口再返回设置，网络加速被自动关闭（是会员）

**系统（请填写以下信息）：**
 - 系统名称：Windows
 - 系统版本： 10

**其他上下文**
打开网络加速并且点击提交按钮，跳转页面显示网络加速以打开，但无法使用除ChatOxO以外的所有ai，再次点击设置，发现网络加速被自动关闭。

**Comment by i165** [comment]
我也是同样的问题

**Comment by mushan0x0** [comment]
下个版本修复

**Comment by kuziki-do** [comment]
我也是，你说怎么办。已经投诉

**Comment by mushan0x0** [comment]
1.3.5已修复
