### ISSUE TITLE
ChatGPT用鼠标随航是只有输入没有运行

### ISSUE THREAD

**Issue by Yan-Zhi-Liang** [mushan0x0/AI0x0.com#136]
**描述错误**
切换到GhatGPT（第一个）时，使用鼠标随航选中一段文本，点击“默认查询”后，没有结果显示。
因为它只把内容显示到输入框，没有运行。

**截图**
![image](https://user-images.githubusercontent.com/81853604/229257713-8e8a552b-82b5-4d30-9b3e-fc4d755223cb.png)

**Comment by sy917975354** [comment]
我也有同样的问题

**Comment by mushan0x0** [comment]
1.3.5已修复
