### ISSUE TITLE
高级模式有写bug，不编辑选中这里无法实现

### ISSUE THREAD

**Issue by JaxLam** [mushan0x0/AI0x0.com#137]
**描述错误**
编辑预设的时候，高级模式选择，不编辑选中，但是输出的内容还是会覆盖选择的文本。

**截图**
![image](https://user-images.githubusercontent.com/129572760/229265128-75d341d2-ee16-4fe9-819d-d64f2eefcdf3.png)

**系统（请填写以下信息）：**
 - 系统名称：Windows
 - 系统版本 11

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
升级1.3.5设置预设里的输入位置就可以了
