### ISSUE TITLE
为什么会有两个悬浮小图标

### ISSUE THREAD

**Issue by ChenstarMr** [mushan0x0/AI0x0.com#142]
![image](https://user-images.githubusercontent.com/45536691/229286219-42e9ce4d-016d-4ade-b35f-3115fafae476.png)

**Comment by HNYDDDTONY** [comment]
没事的，你卡着卡着能卡出三个图标，而且这两个图表会让鼠标随航无法运行，其中一个图标在点击之后会让整个桌面除了任务栏的部分无法点击

**Comment by ChenstarMr** [comment]
> 没事的，你卡着卡着能卡出三个图标，而且这两个图表会让鼠标随航无法运行，其中一个图标在点击之后会让整个桌面除了任务栏的部分无法点击
就是这版本经常卡死

**Comment by ChenstarMr** [comment]
这版本就是经常卡死

**Comment by mushan0x0** [comment]
重启一下吧，好像就没了，如果还是有问题的话加一下这个qq群 575539890 反馈看看

**Comment by visenmo** [comment]
两个+1

**Comment by mushan0x0** [comment]
1.3.5已修复
