### ISSUE TITLE
有错误

### ISSUE THREAD

**Issue by anshangtangyuan** [mushan0x0/AI0x0.com#146]
我通过了chatgt4.0的api申请，将api放到0x0中为什么仍然是3.0版本的的，另外0x0不能总是在最外面的界面，会被页面覆盖住啊，有时候都没有反应

**Comment by mushan0x0** [comment]
可以试试1.4.9吗，gpt4.0还没开放

**Comment by mushan0x0** [comment]
置顶已修复
