### ISSUE TITLE
购买了会员网络加速不能用为啥？

### ISSUE THREAD

**Issue by kuziki-do** [mushan0x0/AI0x0.com#147]
**描述错误**
购买了会员网络加速不能用为啥？

**截图**
如果适用，请添加截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/67821909/229339940-69a10c6e-8b8c-4617-b92a-447503255af9.png)

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
这个是bug，下个版本会修复，可以先用chat0x0

**Comment by kuziki-do** [comment]
我要退钱，啥都用不了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 下午3:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mushan0x0/AI0x0.com] 购买了会员网络加速不能用为啥？ (Issue #147)





 
这个是bug，下个版本会修复，可以先用chat0x0

**Comment by mushan0x0** [comment]
chat0x0也用不了吗

**Comment by kuziki-do** [comment]
刚不能用，现状又好了，勉强，我奔着GPT去的。算了。就当回冤大头



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 下午4:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mushan0x0/AI0x0.com] 购买了会员网络加速不能用为啥？ (Issue #147)





 
chat0x0也用不了吗

**Comment by mushan0x0** [comment]
嗯嗯加速明后天就发版修复了，chat0x0和gpt是一样接口，先用chat0x0吧
