### ISSUE TITLE
在文档里面使用时生成文档不能在文档里面显示出来

### ISSUE THREAD

**Issue by clxcoo** [mushan0x0/AI0x0.com#148]
**描述错误**
清晰而简明地描述错误是什么。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
wps他们自己实现了一套输入，所以有时候要自己点一下
