### ISSUE TITLE
用文心一言引擎时，选中引文，点翻译，没反应，为什么

### ISSUE THREAD

**Issue by clxcoo** [mushan0x0/AI0x0.com#149]
**描述错误**
清晰而简明地描述错误是什么。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
下个版本修复，文心改了代码失效了

**Comment by mushan0x0** [comment]
1.3.5已修复
