### ISSUE TITLE
请是不是把baichat接口关闭啦？web上可以进去，用aioxo连接不上？

### ISSUE THREAD

**Issue by clxcoo** [mushan0x0/AI0x0.com#150]
**描述错误**
清晰而简明地描述错误是什么。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by whckcs** [comment]
我也是

**Comment by mushan0x0** [comment]
并没有，baichat需要加速，而且这几天baichat在维护
