### ISSUE TITLE
软件安装后打不开，系统win11，版本1.3.4

### ISSUE THREAD

**Issue by mike20021113** [mushan0x0/AI0x0.com#152]
**描述错误**
清晰而简明地描述错误是什么。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
是装在c盘的吗

**Comment by TheThirdSanta** [comment]
我也是，装在D盘的program file下，显示无法安装uninstall的程序，最后完毕之后也不开

**Comment by mushan0x0** [comment]
先装到c盘吧

**Comment by TheThirdSanta** [comment]
嗯，我把这个软件安装到默认路径就可以了，似乎改到D盘就不行了；还有，安装过程中的进度条显示有点问题，会出现安装界面闪烁的情况，虽然不会影响最终的结果。。。。大佬加油💪
