### ISSUE TITLE
建立一个微信讨论群吧

### ISSUE THREAD

**Issue by dinghaining** [mushan0x0/AI0x0.com#155]
**您的功能请求是否与问题有关？请描述。**  
提供清晰简洁的问题描述。例如："每当......，我总是感到沮丧。"

**描述您想要的解决方案**  
提供清晰简洁的解决方案描述。

**描述您已考虑过的替代方案**  
提供清晰简洁的替代方案或特性说明。

**附加上下文**  
在这里添加有关功能请求的任何其他上下文或截图。

**Comment by mushan0x0** [comment]
![contact_me_qr](https://github.com/mushan0x0/AI0x0.com/assets/29084441/5ff0f16f-d7a0-41ed-b25e-4014f16e8493)

**Comment by mrgzcq** [comment]
已经满员

**Comment by mushan0x0** [comment]
二维码更新了

**Comment by AjianYo** [comment]
> 二维码更新了

老哥，过期了，麻烦更新一下

**Comment by mushan0x0** [comment]
> > 二维码更新了
> 
> 老哥，过期了，麻烦更新一下

可以扫呀
