### ISSUE TITLE
保留离开前的界面和悬浮图标贴边

### ISSUE THREAD

**Issue by Sunshagon** [mushan0x0/AI0x0.com#156]
**您的功能请求是否与问题有关？请描述。**  
每次打开AI 0x0，无法保留上次离开前的界面，因为我key已到期，所以换成了ChatGPT的界面，而每次打开总是Chat0x0的界面，每次都需要切换过去。每次打开AI 0x0，悬浮图标也不再保留上次离开前的贴边，而是出现在屏幕中央，需要手动拉过去
**描述您想要的解决方案**  
希望可以保留离开前的界面和悬浮图标贴边

**描述您已考虑过的替代方案**  
提供清晰简洁的替代方案或特性说明。

**附加上下文**  
在这里添加有关功能请求的任何其他上下文或截图。

**Comment by mushan0x0** [comment]
贴边已保留，因为chat0x0是推荐的chat，所以暂时不记录自己选择的
