### ISSUE TITLE
加入quicker动作

### ISSUE THREAD

**Issue by whckcs** [mushan0x0/AI0x0.com#157]
**您的功能请求是否与问题有关？请描述。**  
提供清晰简洁的问题描述。例如："每当......，我总是感到沮丧。"
不知道大佬有没有用过quicker，能否把这个软件加入quicker动作，可以实现在quicker输入框直接输入问题的功能
**描述您想要的解决方案**  
提供清晰简洁的解决方案描述。

**描述您已考虑过的替代方案**  
提供清晰简洁的替代方案或特性说明。

**附加上下文**  
在这里添加有关功能请求的任何其他上下文或截图。

**Comment by mushan0x0** [comment]
现在不是可以在任意输入框自动生成内容吗

**Comment by whckcs** [comment]
指的是选中文本ctrl 1吗，这个确实方便

**Comment by mushan0x0** [comment]
是的，用随航也是可以的

**Comment by mushan0x0** [comment]
快捷键改为Alt+1应该会更方便，现在新版默认是Alt+1了
