### ISSUE TITLE
建议增加API地址自定义配置

### ISSUE THREAD

**Issue by MeditatorV** [mushan0x0/AI0x0.com#158]
**您的功能请求是否与问题有关？请描述。**  
因为网络原因，自己部署了API的代理，希望可以支持增加API地址的自定义

**附加上下文**  

下图是其他软件替换API的界面，仅供参考：
![image](https://user-images.githubusercontent.com/47035563/229399361-85193fcb-74bb-4312-acb3-be6f0bc03857.png)

**Comment by mushan0x0** [comment]
目前chat0x0是已经代理过的了，输入自己的key就可以直接用
