### ISSUE TITLE
快捷键设置 建议

### ISSUE THREAD

**Issue by iks-s** [mushan0x0/AI0x0.com#16]
1.选择预设的时候可以多加一个快捷键比如ctrl加上下，否则它会在输入框中的文本内容里上下移动
2.预设默认选择可以添加快捷键更改预选，经常出现选择预设有点影响使用
3.输入模式和输出模式，这个如果可以增加快捷键自己设置就好了

**Comment by iks-s** [comment]
第三条我的意思是 默认选择输入输出模式，只有修改快捷键的时候才更改，就不用经常需要多按一步

**Comment by mushan0x0** [comment]
2暂不考虑，别的都已经优化
