### ISSUE TITLE
悬浮窗会显示上一个问题的答案

### ISSUE THREAD

**Issue by whckcs** [mushan0x0/AI0x0.com#160]
**描述错误**
清晰而简明地描述错误是什么。
新bug来了，现在悬浮窗显示的内容里，除了对当前问题的回答，还有上一个问题的回答
**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
用的哪一个chat

**Comment by whckcs** [comment]
就是chatgpt

**Comment by whckcs** [comment]
有时候会出现有时候不会出现，目前没发现触发条件

**Comment by mushan0x0** [comment]
1.4.2应该已经修复
