### ISSUE TITLE
输入和查询能有一个清晰的定位吗？鼠标选定的文字，如果是输入模式不会执行？还是查询模式才会执行，具体操作上需要注意哪些事项？

### ISSUE THREAD

**Issue by clxcoo** [mushan0x0/AI0x0.com#164]
**描述错误**
清晰而简明地描述错误是什么。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
设置里面的教程里有对这两个的说明的
