### ISSUE TITLE
增加预设之后，在随航菜单里面不能看到，是需要在哪里刷新

### ISSUE THREAD

**Issue by clxcoo** [mushan0x0/AI0x0.com#166]
**描述错误**
清晰而简明地描述错误是什么。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
只要添加了就会自动更新，随航菜单里没看到的话看看预设编辑里的随航模式是不是关掉了
