### ISSUE TITLE
鼠标随性问题

### ISSUE THREAD

**Issue by vgetables** [mushan0x0/AI0x0.com#169]
当我的笔记本外接显示屏时，主显示屏能偶尔能显示图标但是一动就消失了无法点击，外接显示器只能在部分区域有随行图标，这部分区域感觉和主显示器大小差不多在左上方。

**Comment by waywaytot** [comment]
我的也是一样的问题，程序只能在屏幕中央的区域才可以正常显示，拖到边缘就会失灵，一闪一闪的功能也时效了。

**Comment by mushan0x0** [comment]
双屏bug，下个版本修复。。

**Comment by mushan0x0** [comment]
试试1.4.0呢，没有双屏这个不好修复
