### ISSUE TITLE
希望对话框也加入收藏功能

### ISSUE THREAD

**Issue by JaxLam** [mushan0x0/AI0x0.com#173]
希望对话框也加入收藏功能，同时加一个收藏导出的功能
每次点入使用随航之后，点入了对话框。或者问了下一个问题。对话框里面就没办法收藏答案和prompt。

**描述您想要的解决方案**  
希望对话框也加入收藏功能
同时加一个收藏导出的功能

**Comment by mushan0x0** [comment]
1.4.2悬浮气泡已经支持，对话界面加入不太能行。。。

**Comment by mushan0x0** [comment]
收藏导出，有什么格式要求吗

**Comment by JaxLam** [comment]
markdown pdf jpg png就行

**Comment by mushan0x0** [comment]
新版lobeChat支持了
