### ISSUE TITLE
登录注册页

### ISSUE THREAD

**Issue by DWY20** [mushan0x0/AI0x0.com#174]
**描述错误**
一、在4K屏幕下，注册时，输入完用户名、邮箱、密码，鼠标移动至验证码时会触发隐藏，在1080时未发现。
二、登录页拖动至二屏（1080），再拖回一屏（4k），会跟随鼠标移动。
ps：有点无关紧要，你看着来，就单纯跟你讲讲。 

**视频**
链接：https://pan.baidu.com/s/1McVzKjv3T9BDgs4VgF293Q?pwd=0000 
提取码：0000 

**系统（请填写以下信息）：**
Windows
11

**其他上下文**

**Comment by mushan0x0** [comment]
试试1.4.0呢，没有双屏这个不好修复
