### ISSUE TITLE
一些功能建议

### ISSUE THREAD

**Issue by alrcatraz** [mushan0x0/AI0x0.com#175]
使用了三四天，感觉这是一个非常好的工具，但是同时我也发现了一些可以增加以便利使用的功能，或是一些小问题，因此在下方依次列出

**关于悬浮球**  
悬浮球每次启动会出现在默认位置，而不是先前拖动固定的屏幕边缘，是否可以增加记忆悬浮球位置的功能？

**关于更新检查**  
我没有在软件设置或关于页内发现检查更新的功能，可否增加检查更新或是自动更新的功能？

**关于开机启动**  
如果可以在软件中设置开机启动将有效提升使用体验，如果可以添加开机启动选项会非常棒。

**关于文字**  
虽然没有什么决定性的意义，但也许会有人想要设置提问和AI回答的字体和颜色（也许也会包含UI界面中的文字）

**关于跨平台**
这么好的工具，请问您是否计划进一步开发安卓或是其他平台的版本，作为智能助手呢？

感谢您在百忙中阅读我的建议，希望我的建议可以为这款工具有所帮助，如果它们对您有价值那就再好不过了。

**Comment by mushan0x0** [comment]
悬浮球位置这个支持了，更新是自动检测的，开机自启下个版本加

**Comment by alrcatraz** [comment]
好的，非常感谢！祝您和您的作品都越来越好！
