### ISSUE TITLE
只输入了一个1，提示了invalid_request_error报错。

### ISSUE THREAD

**Issue by aoaokua** [mushan0x0/AI0x0.com#176]
{
  "error": {
    "message": "This model's maximum context length is 4097 tokens. However, you requested 7595 tokens (3595 in the messages, 4000 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}
我是付费的会员，我输入了一个1，他说我字符过多？

**Comment by mushan0x0** [comment]
这个是gpt的限制，他会把上面的聊天记录也算做token，你可以在设置里把携带的聊天消息数设为1就好了
