### ISSUE TITLE
The model: `gpt-4-0314` does not exist"？

### ISSUE THREAD

**Issue by aoaokua** [mushan0x0/AI0x0.com#177]
{
    "error": {
        "message": "The model: `gpt-4-0314` does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": "model_not_found"
    }
}
所有相关的gpt 4 的都不存在？

**Comment by mushan0x0** [comment]
对的，gpt4还不能商用的，很贵，反应慢，plus用户都会限制条数，别说第三方的了
