### ISSUE TITLE
建议在设置里新增代理设置选项，以及让悬浮球永远保持最高优先级悬浮

### ISSUE THREAD

**Issue by liucan9527** [mushan0x0/AI0x0.com#18]
在win11系统上使用时，经常出现无法回答选中的文字，只会回答复制的文字，并且使用其写文档时，回车后经常出现弹出多任务窗口切换，然后悬浮球被置于最下层，然后才开始回答

**Comment by mushan0x0** [comment]
窗口切换已修复

**Comment by liucan9527** [comment]
设置内新增代理设置，支持一下socks和http代理，chatgpt官方接口还是很需要的，现在软件本身没有提供代理选项，想用官方chatgpt只能全局代理，很不方便

**Comment by liucan9527** [comment]
目前选中文字回答问题时在浏览器中生效，在wps中无效，在wps中选中文字快捷键唤起助手回答时，助手只会将剪贴板内的内容当作问题，并且经常出现无法聚焦到文档中自动输入的情况

**Comment by mushan0x0** [comment]
试试最新版呢，然后可以参考教程里的输入模式教程，如果还不行的话可以录个视频吗

**Comment by mushan0x0** [comment]
输入模式已修复
