### ISSUE TITLE
支持mac系统较低的版本

### ISSUE THREAD

**Issue by datudoude** [mushan0x0/AI0x0.com#180]
我当前的mac版本是11.6，使用上有些问题，在收入进入的时候提示页面下一步无法点击、悬浮球无法拖动等情况

**Comment by datudoude** [comment]
似乎是电脑在外接显示器上才会出现的问题

**Comment by JackHvikee** [comment]
我的外接显示器也是，很难移动

**Comment by mushan0x0** [comment]
https://ai0x0-track.oss-cn-beijing.aliyuncs.com/test-versions/AI%200x0_1.4.4.dmg 这个支持低版本mac了
