### ISSUE TITLE
悬浮图标隐藏显示异常

### ISSUE THREAD

**Issue by welsongit** [mushan0x0/AI0x0.com#181]
**描述错误**
当鼠标指针位于屏幕左侧六分之五区域时，悬浮图标可以正常展示，当鼠标指针位于屏幕右侧六分之一区域时，悬浮图标会被隐藏

**系统（请填写以下信息）：**
 - 系统名称：Windows
 - 系统版本 11

**Comment by mushan0x0** [comment]
试试1.4.0呢，没有双屏这个不好修复
