### ISSUE TITLE
悬浮窗无法选择模式，word文本选中后鼠标移动到指定位置没有任何反应

### ISSUE THREAD

**Issue by wangdongxiafei** [mushan0x0/AI0x0.com#182]
1.悬浮窗无法拖动 鼠标移动到悬浮窗无任何反应
2.在word中编辑完文字全选 出现查询标签 但是鼠标移动到标签并没有任何反应也没有下拉选项无法识别文字 起初以为是我没有付费 但是付费后发现还是不好使。   

<img width="511" alt="WeChatf3097403d4f45c460655b4a47ab92874" src="https://user-images.githubusercontent.com/11972886/230556718-9b6c001b-3857-4c67-a61f-b36c6b712137.png">
![1680849991898](https://user-images.githubusercontent.com/11972886/230556743-102d92af-14d0-4d6e-999e-18dba76cb4f2.jpg)

**Comment by mushan0x0** [comment]
现在还没兼容MacOS13以下的版本。。。
