### ISSUE TITLE
双屏扩展，鼠标碰不到悬浮框，靠近就跑了，关闭双屏，重装也不行...

### ISSUE THREAD

**Issue by sammyzhang2599** [mushan0x0/AI0x0.com#183]
**描述错误**
双屏扩展，鼠标碰不到悬浮框，靠近就跑了，关闭双屏，重装也不行...

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by sammyzhang2599** [comment]
能在 设置里增加 对悬浮框的 设置选项吗？

**Comment by mushan0x0** [comment]
试试1.4.0呢，没有双屏这个不好修复
