### ISSUE TITLE
建议Alt+3快捷键可以隐藏聊天界面、生成内容可以自动输入、悬浮球可以隐藏

### ISSUE THREAD

**Issue by CHNAICORP** [mushan0x0/AI0x0.com#186]
**中文：**
1.建议优化原有功能：当前快捷键Alt + 3点击一次显示聊天界面，再次点击无法隐藏聊天界面；建议更改为Alt + 3快捷键可以重复点击，Alt + 3快捷键显示聊天界面时，再次点击Alt + 3可以隐藏聊天界面。

2.建议优化生成文档、代码、markdown功能，软件自动输入生成的文档、代码、markdown，不用人工复制粘贴进去。

3.上述功能支持Windows、Mac、Android、IOS

4.悬浮球可以隐藏

**English：**
1.Suggestion for optimizing the existing feature: Currently, the shortcut key Alt + 3 can only display the chat interface once and cannot hide the chat interface when clicked again. It is recommended to change it to Alt + 3K, which can be repeatedly clicked. When the Alt + 3 shortcut key displays the chat interface, clicking Alt + 3 again can hide the chat interface.

2.Suggestion for optimizing the feature of generating documents, code, and markdown. The software automatically inputs the generated documents, code, and markdown without manual copy and paste.

3.The above features are supported on Windows, Mac, Android, and iOS platforms.

4.It is suggested to have the option to hide the floating ball.

**Comment by mushan0x0** [comment]
1的下个版本可以加上
2是会自动输入的，可以看教程里的输入模式
3win和mac都是支持的，移动端暂时没有这个财力来做
4在小图标右键就可以隐藏和显示了

**Comment by CHNAICORP** [comment]
一、答复：
1.期待
2-4.经过实践证明（Win11环境，MS Word、Excel、VScode ），确实如此。不过，有一个注意点就是需要光标在指定的地方才能输入。MS PPT还没有实践过，不知道现在是否支持，或者未来版本是否支持PPT生成。期待！
二、提问：
1.图片识别功能是否有演示视频，如何实现？
2.聊天显示设置里面的GPT-4模型是否可以调用，目前是否支持，未来如何实现？
三、祝愿！
期待产品越做越好！功能越来越多！

**Comment by mushan0x0** [comment]
> 1.图片识别功能是否有演示视频，如何实现？
> 2.聊天显示设置里面的GPT-4模型是否可以调用，目前是否支持，未来如何实现？

1和2都需要gpt4的开放

**Comment by mushan0x0** [comment]
>1.建议优化原有功能：当前快捷键Alt + 3点击一次显示聊天界面，再次点击无法隐藏聊天界面；建议更改为Alt + 3快捷键可以重复点击，Alt + 3快捷键显示聊天界面时，再次点击Alt + 3可以隐藏聊天界面。

1.4.2已经支持了
