### ISSUE TITLE
每一个选项卡的AI都无法打开

### ISSUE THREAD

**Issue by N9FFF** [mushan0x0/AI0x0.com#188]
- 每一个选项卡的AI都一直加载
- 设置可以打开
- 各个渠道下载的安装都是同样的情况
- 更新了最新版本同样的情况
- 第一次下载安装的时候是可以使用的，时间：4月9日
- 有无代理都是同样的情况
![image](https://user-images.githubusercontent.com/117291151/231068161-31ba0d30-2b6a-49a4-a411-fcdb1c125853.png)

![image](https://user-images.githubusercontent.com/117291151/231068312-dda61972-295f-4bd3-a87f-03939ad339d2.png)

- 系统名称：Windows
 - 系统版本 10

**Comment by mushan0x0** [comment]
可以试试1.4.2在设置页面重置应用吗
