### ISSUE TITLE
悬浮球

### ISSUE THREAD

**Issue by Thostones** [mushan0x0/AI0x0.com#191]
**描述错误**
1. 当我有一个主屏和一个扩展屏的时候，某种情况下会跟着鼠标在两个屏上跳跃，球相对屏的位置是固定的，但是会跟随鼠标出现在鼠标所在屏，鼠标跟随还是禁用的状态。
2. 会沉底，就是不是置顶的状态。
3. 下弹窗太敏感，鼠标一划过就出现，很久都缩回去
4. 下弹窗缩回迟钝，click桌面其它地方有时能缩回去，有时缩不回去，有时等会儿自己缩回去，有时等很久也不缩回去
5. 有时候单机悬浮窗图标出对话框，有时候单机不出现对话框

**系统（请填写以下信息）：**
win10

建议，
1. 除了老板键Alt+3唤出对话框，对话框出现以后ESC或再次Alt+3隐藏或者退出对话框。
2. 悬浮球鼠标悬停一定时间再跳下拉框或者干脆做个小的标志点一下才出来下拉框，个人觉得加个三角标click下拉比较合适，实现简单逻辑合理。

**Comment by mushan0x0** [comment]
> 会沉底，就是不是置顶的状态。
> 除了老板键Alt+3唤出对话框，对话框出现以后ESC或再次Alt+3隐藏或者退出对话框。

可以在1.4.2试试这两个问题吗

**Comment by mushan0x0** [comment]
试试1.4.6呢
