### ISSUE TITLE
付费后吞付费资格

### ISSUE THREAD

**Issue by zhaoke2023** [mushan0x0/AI0x0.com#192]
我于4月1日使用支付宝付费一个月，近日发现显示状态为未开通，

**Comment by mushan0x0** [comment]
重新登录可以吗，把帐号发给我我看看吧

**Comment by zhaoke2023** [comment]
重新登陆无法解决，账号：13425367997，密码：k33416505
需要提供支付截图吗



1197484542
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mushan0x0/AI0x0.com"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 下午4:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mushan0x0/AI0x0.com] 付费后吞付费资格 (Issue #192)





 
重新登录可以吗，把帐号发给我我看看吧

**Comment by zhaoke2023** [comment]
1197484542
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mushan0x0/AI0x0.com"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月11日(星期二) 晚上7:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mushan0x0/AI0x0.com] 付费后吞付费资格 (Issue #192)





 
@zhaoke2023 这个账号没有查到付费订单，可以发一下订单截图吗
