### ISSUE TITLE
悬浮球

### ISSUE THREAD

**Issue by wxh1526** [mushan0x0/AI0x0.com#193]
悬浮球一直处于查询状态，哪怕断网了依旧是查询状态，点旁边的叉号，关掉之后，又开始了查询状态。

**Comment by mushan0x0** [comment]
chatgpt因为网络延迟太高就会这样，可以用baichat和chat0x0，或者新开一个对话

**Comment by wxh1526** [comment]
好的好的，感谢感谢



| |
wxh15562887102
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月11日 22:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [mushan0x0/AI0x0.com] 悬浮球 (Issue #193) |

Closed #193 as completed.
