### ISSUE TITLE
提示信息关不掉

### ISSUE THREAD

**Issue by nuczzz** [mushan0x0/AI0x0.com#194]
![image](https://user-images.githubusercontent.com/33566732/231179509-61fbe623-4510-4db9-bf48-6cb43fb62ad5.png)
这个提示窗口一直显示，点击没反应。最小化ai0x0后这块还是会显示在屏幕上

**Comment by mushan0x0** [comment]
现在只支持MacOS 13的系统，太低的版本就会这样
