### ISSUE TITLE
内存消化非常大

### ISSUE THREAD

**Issue by mukgong** [mushan0x0/AI0x0.com#195]
**描述错误**
内存非常大，刚开始启动非常小。随着时间运行非常大，整个设备最大内存就是Al OxO Helper (Renderer)进程，麻烦看下是否是一个问题。
刚开始非常正常，如图。设备是M2 air
运行一段时间后，最高是到8-10G。
**截图**
异常
<img width="643" alt="image" src="https://user-images.githubusercontent.com/40912971/231420117-31cfd8c0-797d-43c8-83c1-032c169cb262.png">

刚开始运行，
<img width="665" alt="image" src="https://user-images.githubusercontent.com/40912971/231674203-ff028522-5e9c-41ef-93d6-7785557e13fe.png">

**系统（请填写以下信息）：**
 - 系统名称：Mac
 - 系统版本  13.3.1

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by baikaishui888** [comment]
我也发现这个问题,貌似清理一些对话框会有一些好转

**Comment by mukgong** [comment]
清理了，还是一样

**Comment by mushan0x0** [comment]
在设置界面点三次重置按钮呢

**Comment by mushan0x0** [comment]
在设置界面点三次重置按钮呢

**Comment by mukgong** [comment]
点击三次重置会重置预设规则么？现在有很多自己梳理的预设规则。

**Comment by mushan0x0** [comment]
不会的，只会影响收藏

**Comment by mushan0x0** [comment]
1.4.9 内存已经优化
