### ISSUE TITLE
连不上连不上就是连不上

### ISSUE THREAD

**Issue by mariahlamb31** [mushan0x0/AI0x0.com#197]
**描述错误**
连不上，无论是baichat，0x0还是百度的，都连不上，但是设置界面有，prompt界面能显示。
一直转圈圈，转的我头皮发麻。

**系统（请填写以下信息）：**
 - 系统名称：[windows]
 - 系统版本 [10]

**其他上下文**
C盘也装了，G盘也装了 都好不了。
我前面没掏钱的时候好好的，现在每天看这它转圈圈T_T，我太难了。。
![image](https://user-images.githubusercontent.com/117580900/231691844-c6c1ead4-06a3-473e-b347-af8570c62cb1.png)
![image](https://user-images.githubusercontent.com/117580900/231691986-1a06e82d-0f7d-4cf0-8349-c86868fe019c.png)
大佬你行行好，赶紧修复啊啊啊 ，我真是顶不住了，刚付完钱就挂了。。

**Comment by mushan0x0** [comment]
重启电脑试试呢。。。

**Comment by mariahlamb31** [comment]
我已经三天辣，我是真的憋不住惹，改端口，几个yaml反复横跳，都试过啦。我老觉着是它的chat功能被限制联网了，因为设置和模板都能很快跳出来。但我不晓得怎么排查。

**Comment by mushan0x0** [comment]
文心一言也不行吗，你看看通过连接可以打开不 https://yiyan.baidu.com/welcome

**Comment by mushan0x0** [comment]
可以看看你设置吗。。是不是代理啥的错了

**Comment by mariahlamb31** [comment]
![image](https://user-images.githubusercontent.com/117580900/231743826-ec6e9ce5-efe1-4544-8a69-9f14d5f5dda4.png)
![image](https://user-images.githubusercontent.com/117580900/231743940-9a9e5e5b-d01f-4c60-8df2-05ce8dfbe6cb.png)
![image](https://user-images.githubusercontent.com/117580900/231744335-3064605d-3a01-4847-b601-cb9ec8635d72.png)
![image](https://user-images.githubusercontent.com/117580900/231744956-0960e48f-511a-4d2a-baff-9e1a58c1210e.png)
我也很迷啊。。。

**Comment by mushan0x0** [comment]
要不把代理删了呢，用chat0x0不用代理也能连

**Comment by mushan0x0** [comment]
加速也关了试试呢

**Comment by mariahlamb31** [comment]
![image](https://user-images.githubusercontent.com/117580900/231747524-9139cea9-d455-4f32-b161-54747e3b99bb.png)
![image](https://user-images.githubusercontent.com/117580900/231747691-7c1a0d27-6325-484e-9181-536dafbe893a.png)
![image](https://user-images.githubusercontent.com/117580900/231747780-6835acb3-23ea-495c-b57e-d25ddfa557a9.png)
一样的，，我刚都把猫子给退了，文心一言还是连不上，我就是觉得是不是chat部分的联网是不是有什么冲突。因为我真要是没网，prompt那部分我也看不到，这两天不断换端口换版本试出来了T-T

**Comment by mariahlamb31** [comment]
我真的很希望能用起来，这是我体验感最好的客户端了，和quicker搭配简直绝了。所以，求求了，不然我得重装系统了- -

**Comment by mushan0x0** [comment]
确实不知道怎么回事了。。你看看系统代理是不是设置了一个无效的

**Comment by mushan0x0** [comment]
1.4.2设置界面加入了重置功能，你可以重置后试试吗

**Comment by onewinner** [comment]
这应该是你电脑网络配置或代理有问题，与0x0不相关，有时候开代理，经常会出现一些奇葩问题

**Comment by mariahlamb31** [comment]
> 1.4.2设置界面加入了重置功能，你可以重置后试试吗

哇，一上来就有好消息！我赶紧试试去

**Comment by mariahlamb31** [comment]
> 这应该是你电脑网络配置或代理有问题，与0x0不相关，有时候开代理，经常会出现一些奇葩问题

是的呀，谁晓得是哪个链接里的节点出问题了😓

**Comment by mariahlamb31** [comment]
哇！大佬腻害！！！我能用了！好开心！！
