### ISSUE TITLE
把chat0x0 的模型改成gpt-4后，对话框就进不去了，也没有改回去的地方

### ISSUE THREAD

**Issue by wenhou123** [mushan0x0/AI0x0.com#198]
**描述错误**
清晰而简明地描述错误是什么。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
按刷新快捷键可以吗

**Comment by wenhou123** [comment]
> 按刷新快捷键可以吗

不行，一直都是在这个界面
![image](https://user-images.githubusercontent.com/45194895/231916455-b72c929e-c454-4a21-ba9a-6ca3a55304e2.png)

**Comment by mushan0x0** [comment]
1.4.2设置界面加入了重置功能，你可以重置后试试吗
