### ISSUE TITLE
悬浮球消失和切换当前页面

### ISSUE THREAD

**Issue by YanMu2020** [mushan0x0/AI0x0.com#199]
环境:Windows11 DEV
问题1:长时间挂着以后，多次出现悬浮球消失问题
问题2:选中文本，使用翻译成英文(输入模式)，会切换当前页面（如discord客户端切换到notion客户端）

**Comment by mushan0x0** [comment]
可以试试1.4.2版本吗，这两个bug好像是会偶尔触发

**Comment by YanMu2020** [comment]
测试了几个小时，目前问题1没有发生，问题2发生次数比上一个版本减少👍😊
