### ISSUE TITLE
不知道能不能集成以下两个ai

### ISSUE THREAD

**Issue by moooooooooooooooooooooooooooooooooooooj** [mushan0x0/AI0x0.com#200]
[**您的功能请求是否与问题有关？请描述。**  
https://poe.com/，以及https://beta.character.ai/
**描述您想要的解决方案**  
不知道是否能集成
**描述您已考虑过的替代方案**  
不知道是否能集成
**附加上下文**  
不知道是否能集成
]
![image](https://user-images.githubusercontent.com/38418090/232070089-17a77781-e49e-441d-818f-5981a1709bf4.png)
![image](https://user-images.githubusercontent.com/38418090/232070228-bc12c23b-2daa-404f-9ddf-cab5cfa0d9fb.png)

**Comment by mushan0x0** [comment]
没有太亮点的功能，而且部分功能是付费的。。

**Comment by mushan0x0** [comment]
没有太亮点的功能，而且部分功能是付费的。。

**Comment by mushan0x0** [comment]
https://ai0x0-track.oss-cn-beijing.aliyuncs.com/test-versions/AI%200x0_1.4.5.exe 内测版已经集成了，可以试试看

**Comment by mushan0x0** [comment]
只集成了poe

**Comment by moooooooooooooooooooooooooooooooooooooj** [comment]
大佬牛逼，已经用上了。期待后续的新功能。 目前使用频率不是很高，后期功能齐全会入会支持&nbsp;，还有期待移动端，大佬
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月18日(星期二) 晚上9:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mushan0x0/AI0x0.com] 不知道能不能集成以下两个ai (Issue #200)





 
https://ai0x0-track.oss-cn-beijing.aliyuncs.com/test-versions/AI%200x0_1.4.5.exe 内测版已经集成了，可以试试看

**Comment by moooooooooooooooooooooooooooooooooooooj** [comment]
兄弟 新版本poe有bug 左边选择ai的那个打开poe过两秒就收进去了


01是刚打开poe ， 02是打开过了一两秒&nbsp; GitHub反馈了 不过这边也跟你说下 哈哈 内测版没问题







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mushan0x0/AI0x0.com"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月18日(星期二) 晚上9:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mushan0x0/AI0x0.com] 不知道能不能集成以下两个ai (Issue #200)





 
https://ai0x0-track.oss-cn-beijing.aliyuncs.com/test-versions/AI%200x0_1.4.5.exe 内测版已经集成了，可以试试看
