### ISSUE TITLE
可以给预设包加一个分类功能吗，写了太多预设了，导致找预设会很麻烦

### ISSUE THREAD

**Issue by aquaua** [mushan0x0/AI0x0.com#202]
**您的功能请求是否与问题有关？请描述。**  
提供清晰简洁的问题描述。例如："每当......，我总是感到沮丧。"

**描述您想要的解决方案**  
提供清晰简洁的解决方案描述。

**描述您已考虑过的替代方案**  
提供清晰简洁的替代方案或特性说明。

**附加上下文**  
在这里添加有关功能请求的任何其他上下文或截图。

**Comment by mushan0x0** [comment]
后面会对用户开放预设包功能，开放了就可以进行分类了
