### ISSUE TITLE
多屏工作时的问题

### ISSUE THREAD

**Issue by shi-linyu** [mushan0x0/AI0x0.com#204]
鼠标移动到另一块屏幕时会有明显卡顿，开启鼠标随航后会更明显，并且伴随任务栏闪烁
系统Win11

**Comment by mushan0x0** [comment]
试试1.4.6呢

**Comment by shi-linyu** [comment]
https://user-images.githubusercontent.com/98072300/233276500-5107bda2-ab6a-432f-84f5-cfe278c0e225.mp4

**Comment by shi-linyu** [comment]
最新版本导致的卡顿更严重了

**Comment by xuuou** [comment]
同样遇到多屏幕问题：当悬浮窗停靠并半隐藏在**外接显示器**最右边时，此时鼠标移动到**笔记本屏幕**上，悬浮窗却不会显示在**笔记本屏幕**最右边，而是显示在**笔记本屏幕**中间靠右的位置。

<img width="400" alt="1 (中)" src="https://github.com/mushan0x0/AI0x0.com/assets/111893160/b12cd28e-f5c5-4a74-a194-0022c42f6363">

<img width="400" alt="2 (中)" src="https://github.com/mushan0x0/AI0x0.com/assets/111893160/5d2abc89-1381-4e48-9806-83e8ed0ecbae">

**Comment by mushan0x0** [comment]
可以试试 1.5.3 可以了不

**Comment by xuuou** [comment]
> 可以试试 1.5.3 可以了不

已经没问题了，感谢。
