### ISSUE TITLE
M1 Mac 无响应的频率太高，各种窗口打开、过渡不流畅，很不苹果

### ISSUE THREAD

**Issue by 9Aiwan** [mushan0x0/AI0x0.com#205]
**描述错误**
清晰而简明地描述错误是什么。
M1 Mac 用过十几款这是：想法最好、功能不错、无响应最多、卡顿最严重、
无响应的频率太高，各种窗口打开、过渡不流畅，很不苹果
**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
你是什么系统

**Comment by 9Aiwan** [comment]
16G M1 Mac mini  macOS Ventura 版本13.3.1
主要体现在：
1、拖动屏幕中的GPT那个图标，卡顿瞬移，有时候要拖几次
2、同样是图标那个搜索的放大镜，鼠标放上去会横向拉出输入框，不流畅
3、同样是图标，鼠标放上GPT绿色ICON，会下拉弹出选项，灵敏度希望优化，有时候真的只是路过了下，有时候选择设置的时候会不小心划出范围，最终就是来回移动光标
4、用快捷键呼出“选中文本”，下方出现的预设选择会跳2次，先出现在一个位置，当文字框完全打开后它又会跳到输入框下方，体验不佳
5、查询模式下，鼠标挪到窗口会自动放大，放大缩小不流畅，体验不佳
6、退出时经常卡死，MAC上方菜单栏直接不能用
7、在设置中，你点击个人和关于两个快速切换，很多地方就类似于这样
8、近期ChatGPT网络问题直接影响到使用，已经将APP全局走了Surge

总之，这么多工具用下来是有很多亮点、想法，就是体验上还差点，导致有时候就想在等几个版本的迭代，加油

**Comment by mushan0x0** [comment]
是的这些都是优化项，后面都会完善的

**Comment by 9Aiwan** [comment]
对的，就是些小的优化，
先解决卡、卡死、退出死
然后在搞搞流畅，先正常的高强度的应用起来
加油加油

**Comment by mukgong** [comment]
我的也是M2 air 还是16G的，已经是会员

**Comment by mushan0x0** [comment]
https://ai0x0-track.oss-cn-beijing.aliyuncs.com/test-versions/AI%200x0_1.4.9_arm64.dmg 可以试试这个版本，针对m芯片有优化

**Comment by mushan0x0** [comment]
1.4.9 arm64版本已经推送

**Comment by YaoQ** [comment]
MAC AIR, macOS 13 Intel i5 8G
安装v1.4.15，可能因为历史记录超过了100， 确实很容易无响应，而且直接影响系统运行，甚至直接导致系统退出。
