### ISSUE TITLE
模型选择功能形同虚设

### ISSUE THREAD

**Issue by SmartSunruiyang** [mushan0x0/AI0x0.com#206]
**描述错误**
切换模型切换了跟没切换一样，虽然模型选择了GPT4但是还是GPT3.5。因为这个原因就算选择了GPT-4-32K最大的tokens还是被限制了，动不动就返回报错

**系统（请填写以下信息）：**
 - 系统名称：[Windows, MacOS]
 - 系统版本 [11, 13]

**Comment by mushan0x0** [comment]
gpt4还没开放，不能商用的

**Comment by mushan0x0** [comment]
配置已去掉
