### ISSUE TITLE
添加不自动使用markdown语法开关

### ISSUE THREAD

**Issue by SmartSunruiyang** [mushan0x0/AI0x0.com#207]
**您的功能请求是否与问题有关？请描述。**  
提供清晰简洁的问题描述。例如："每次问代码的时候 总是自动使用Markdown语法"

**描述您想要的解决方案**  
添加不自动使用markdown语法输入的选项。

**Comment by mushan0x0** [comment]
用markdown语法才能知道返回的代码内容
