### ISSUE TITLE
关于NewBing

### ISSUE THREAD

**Issue by alrcatraz** [mushan0x0/AI0x0.com#208]
NewBing在模型列表里放了挺久了的，可以方便问一下什么时候可以使用NewBing吗？

**Comment by mushan0x0** [comment]
NewBing现在已经削成弱智了，而且响应很慢，可能后面不会适配了

**Comment by alrcatraz** [comment]
但是查询资料之类的话我觉得新必应比chatGPT靠谱很多，gpt经常瞎编😂

**Comment by rhouselyn** [comment]
> NewBing现在已经削成弱智了，而且响应很慢，可能后面不会适配了

还是有一些引导词可以让他大致恢复正常的

**Comment by mushan0x0** [comment]
最近我看看要不适配一下吧

**Comment by alrcatraz** [comment]
太感谢了！

**Comment by sfantacy** [comment]
同样需要，希望尽快增加，感谢

**Comment by mushan0x0** [comment]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/29084441/232967892-1bda4b49-e260-49c9-a858-9eefdeb0def6.png">
已经适配了，下个版本上

**Comment by mushan0x0** [comment]
1.4.6已经发布了

**Comment by alrcatraz** [comment]
无法登录新必应耶，只有点击加入等待列表的按钮，按了之后经过跳转还是会跳回来，可以登录自己的微软账号来使用新必应吗？

**Comment by alrcatraz** [comment]
> 1.4.6已经发布了

无法登录新必应耶，只有点击加入等待列表的按钮，按了之后经过跳转还是会跳回来，可以登录自己的微软账号来使用新必应吗？

**Comment by liangxyz** [comment]
> > NewBing现在已经削成弱智了，而且响应很慢，可能后面不会适配了
> 
> 还是有一些引导词可以让他大致恢复正常的

请问有什么引导词啊？急需，谢谢大佬
