### ISSUE TITLE
多屏幕下随航/浮窗存在闪烁/跳跃现象

### ISSUE THREAD

**Issue by ShadovvSinger** [mushan0x0/AI0x0.com#209]
我的电脑使用两个屏幕，并长期开启wallpaper engine

长按鼠标后弹出的选项窗会像躲着我的鼠标一样乱跳，比如跳到角落，或者跳到另一个屏幕的相似位置

在我挪动悬浮球的时候，偶尔也会有类似的情况

**Comment by mushan0x0** [comment]
windows吗，关了wallpaper会正常吗

**Comment by HB-385** [comment]
惊了！回得这么快，是windows，没试过关wallpaper engine，明天试一下

**Comment by mushan0x0** [comment]
好的好的

**Comment by zhihui88** [comment]
我的也有同样的问题

**Comment by sunveternal** [comment]
> 好的好的

只要是多屏就有问题，跟wallpaper engine 没关系；

**Comment by jingran2025** [comment]
我的也是同样的情况，用的是ASUS Zenbook，双屏的。浮窗闪烁，跳跃，飘忽不定，输入不准

**Comment by mushan0x0** [comment]
谁可以录个屏吗

**Comment by ShadovvSinger** [comment]
录屏来了，一个4K屏幕，一个1080P屏幕，使用obs录制成1080P视频。
其中为了方便，在obs中进行了叠放，左下角的是1080P屏幕，背后大的是4K屏幕。
把气泡放在4K屏幕中，鼠标靠近一定的范围内，它就会跳到1080P屏幕去，且在它跳到的地方，鼠标移过去会有下拉菜单反馈，但是无法左键拖动。
mkv无法上传，压缩成zip了
[2023-04-18 21-50-42.zip](https://github.com/mushan0x0/AI0x0.com/files/11262517/2023-04-18.21-50-42.zip)

**Comment by mushan0x0** [comment]
好的我看看

**Comment by mushan0x0** [comment]
试试1.4.6呢

**Comment by 1135288997** [comment]
我也来录个屏，并且仔细描述一下。浮动qiu球在双屏幕下不能像360浮动球一样，靠边。而是随着鼠标左右切换屏幕。遮挡视线。不能固定在一个屏幕上，而是在两个屏幕上来回跑。浮动球在主屏幕上，可以移动。按住Chatgpt和放大镜之外的黑色部分可以移动，但是在副屏幕上的时候无法选中，并且会按住Chatgpt和放大镜之外的黑色部分会按不到，会把其他文档上文字拖出来。我的解决办法：不用浮动球，不用自动输入。自己在对话框，手动复制粘贴即可。


https://user-images.githubusercontent.com/42299380/233768879-f7a61d47-2095-4a8b-a27a-196f31c18149.mp4

**Comment by mushan0x0** [comment]
1.4.9副屏不能选中问题已修复
