### ISSUE TITLE
又是我，这次是mac系统上的问题，悬浮球和鼠标停留位置的“放大镜”图标无法点击和交互

### ISSUE THREAD

**Issue by ShadovvSinger** [mushan0x0/AI0x0.com#210]
<img width="819" alt="截屏2023-04-16 23 24 05" src="https://user-images.githubusercontent.com/59726686/232323381-5721f296-920d-41a8-8135-c82c63fffd4c.png">

<img width="219" alt="截屏2023-04-16 23 27 25" src="https://user-images.githubusercontent.com/59726686/232323411-4b6b964a-028f-4314-a167-26e0e8ddbe61.png">

图二极其抽象，我在尝试着拖动悬浮球，然后“放大镜”就在它后面出现了，不知道什么原因，我截图不能显示鼠标，但是鼠标就在那个位置。

macOS Monterey
版本 12.5.1
MacBook Pro (15-inch, 2019)
处理器 2.6 GHZ 六核Intel Core i7
内存 32 GB 2400 MHZ DDR4
图形卡 Radeon Pro 560x 4 GB
Intel UHD Graphics 630 1536 MB

**Comment by mushan0x0** [comment]
macos12还没兼容的。。13是正常的

**Comment by mushan0x0** [comment]
https://ai0x0-track.oss-cn-beijing.aliyuncs.com/test-versions/AI%200x0_1.4.4.dmg 这个支持低版本mac了
