### ISSUE TITLE
最新版本输入功能无效，请修复

### ISSUE THREAD

**Issue by daniellong0424** [mushan0x0/AI0x0.com#211]
**描述错误**
之前的版本，选中文本进行输入，就会输入文本，现在不行了，只能是查询模式。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：window
 - 系统版本  11

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
可以输入的，有录屏吗

**Comment by mushan0x0** [comment]
输入模式和查询模式对调了，在设置里可以改回以前的

**Comment by daniellong0424** [comment]
> 

请问一下怎么修改呢？这个和以前的不一样。

**Comment by daniellong0424** [comment]
> 输入模式和查询模式对调了，在设置里可以改回以前的

请问一下怎么修改呢？这个和以前的不一样。

**Comment by mushan0x0** [comment]
<img width="544" alt="image" src="https://user-images.githubusercontent.com/29084441/232364312-c7da7a0a-68cf-4334-9845-6b6092242d4b.png">
这个改为输入就行了

**Comment by daniellong0424** [comment]
> <img alt="image" width="544" src="https://user-images.githubusercontent.com/29084441/232364312-c7da7a0a-68cf-4334-9845-6b6092242d4b.png">
> 
> 这个改为输入就行了

你好，尝试了这个设置但是还是不行，

https://user-images.githubusercontent.com/130947078/232367195-05e80207-0e89-4bec-a062-d58395362fa4.mp4

这个是录屏，你看看。

**Comment by YanMu2020** [comment]
这个我也遇到过，我个人测试可能的原因是，鼠标光标消失（电脑将第一显示为悬浮框）

**Comment by daniellong0424** [comment]
> 这个我也遇到过，我个人测试可能的原因是，鼠标光标消失（电脑将第一显示为悬浮框）

请问一下如何有效的避免呢？因为之前的版本是没有这种情况的，今天更新就不行了。

**Comment by mushan0x0** [comment]
可以加这个内测群吗 575539890 ，我打包内测版本让你们试试

**Comment by YanMu2020** [comment]
> > 这个我也遇到过，我个人测试可能的原因是，鼠标光标消失（电脑将第一显示为悬浮框）
> 
> 请问一下如何有效的避免呢？因为之前的版本是没有这种情况的，今天更新就不行了。

我在群里发送了视频，我猜测光标问题，所以，当悬浮框在输出内容的时候，再次点击notepad，将光标显示在notepad即可输入

**Comment by mushan0x0** [comment]
试试1.4.3可以吗

**Comment by mushan0x0** [comment]
1.4.7已修复
