### ISSUE TITLE
更新后聊天页面卡着出不来，一直处于加载状态

### ISSUE THREAD

**Issue by zhangyongzhi123** [mushan0x0/AI0x0.com#212]
但gpt在小窗口还是可以正常使用，就是聊天页面框加载不出来，有小伙伴是这种情况的吗

![1681701207943](https://user-images.githubusercontent.com/62998221/232369242-aa4af6a7-0f23-4948-9d81-4f1d3dcaeb36.jpg)

**Comment by mushan0x0** [comment]
刷新也不行吗，在设置里重置应用呢

**Comment by zhangyongzhi123** [comment]
原来重置软件就可以，刚重装好几次都不行。谢谢大佬指导解决，感谢！

**Comment by mariahlamb31** [comment]
我也是我也是，我好激动，我好几天没用到都有戒断反应了
