### ISSUE TITLE
预设包是咋用的?

### ISSUE THREAD

**Issue by baikaishui888** [mushan0x0/AI0x0.com#214]
**描述错误**
1.升级1.4版本后,预设包里面有内容了,但是不知道怎么使用?可以出个教程吗?
2.内存消耗很高,貌似不会自动释放.
<img width="780" alt="571f0fb397c35d72b5833c7daf323b2" src="https://user-images.githubusercontent.com/126687152/232453213-b935c281-a4ab-4b25-8582-18f5adae41cd.png">

**Comment by mushan0x0** [comment]
<img width="718" alt="image" src="https://user-images.githubusercontent.com/29084441/232482994-f0412081-6b2b-4aea-9e38-1865dc97f265.png">
预设包后面会出教程，内存一般不会超过1g，你的是占用多少

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/wiki 教程已经有了
