### ISSUE TITLE
Chat右上角的“铅笔”按钮没反应

### ISSUE THREAD

**Issue by Otiguy** [mushan0x0/AI0x0.com#216]
**描述错误**
这个铅笔按钮点击有什么用？没任何反馈，我一开始以为是修改session标题，是吗？

**截图**

![image](https://user-images.githubusercontent.com/48633984/232466273-a1adec20-8f36-4596-a3b6-53d77f62c567.png)

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]Win10 64bit
 - 系统版本 [例如，11]

**Comment by mushan0x0** [comment]
是的修改标题的，但是现在有bug，点了没有反应

**Comment by mushan0x0** [comment]
已修复
