### ISSUE TITLE
拜托别强制更新了，拜托悬浮查询功能可选关闭吧。

### ISSUE THREAD

**Issue by Samuelonly** [mushan0x0/AI0x0.com#220]
24小时强制更新了4次，产品真的很好，感谢，尤其是不用梯子！！！
但是
1求求**别强制更新了**，给一个**手动可选项**吧。此时此刻登不上了，不知道为什么。
显示加载失败，检查网络并重试。
2查询功能比较低频，对我个人划词翻译比较高频，这就冲突了。经常误触造成触发。
能不能把它关掉。
而且强迫症，就喜欢桌面是空的，和360小火箭一样看着难受。

**Comment by mushan0x0** [comment]
在设置页点三次重置按钮重置一下呢，悬浮窗可以拖动到屏幕右边会自动隐藏的

**Comment by Samuelonly** [comment]
重置好了，这重置方式跟个彩蛋似的，我才注意到右上角有个提示。
你回复这么快！
感谢感谢感谢感谢！！！

**Comment by mushan0x0** [comment]
没事没事，不也不知道为什么有些用户会连不上，昨天频繁更新是因为有些比较影响的bug
