### ISSUE TITLE
建议不需要鼠标随航，直接变为图标一直存在，由用户使用鼠标自由拖拉至合适位置，然后用户选中内容后直接选对话内容。现在遇到的问题：选中了需要翻译的内容，但是没选到预设的项目，然后图标又消失了，又需要重新选中一遍内容，很麻烦，图标一直存在就不会出现这个问题

### ISSUE THREAD

**Issue by linWiky** [mushan0x0/AI0x0.com#221]
**描述错误**
清晰而简明地描述错误是什么。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
习惯了就会操作很快了，现在图标停留的3秒应该挺久了，图标一直显示也不是很好的方案，后面再优化吧

**Comment by linWiky** [comment]
我的意见是，就放大镜🔍图标持续显示，点图标然后列出预设项目，可以到5s这样



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月18日 16:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [mushan0x0/AI0x0.com] =?UTF-8?Q?_=E5=BB=BA=E8=AE=AE=E4=B8=8D=E9=9C=80=E8=A6=81=E9=BC=A0=E6=A0=87=E9=9A=8F=E8=88=AA=EF=BC=8C=E7=9B=B4=E6=8E=A5=E5=8F=98=E4=B8=BA=E5=9B=BE=E6=A0=87=E4=B8=80=E7=9B=B4=E5=AD=98=E5=9C=A8=EF=BC=8C=E7=94=B1=E7=94=A8=E6=88=B7=E4=BD=BF=E7=94=A8=E9=BC=A0=E6=A0=87=E8=87=AA=E |

习惯了就会操作很快了，现在图标停留的3秒应该挺久了，图标一直显示也不是很好的方案，后面再优化吧

**Comment by mushan0x0** [comment]
5秒太长了吧。。。

**Comment by mushan0x0** [comment]
或者把随航关了，按查询快捷键也是一样的可以操作
