### ISSUE TITLE
已经好几天不能用了

### ISSUE THREAD

**Issue by RiverJJJ** [mushan0x0/AI0x0.com#223]
**您的功能请求是否与问题有关？请描述。**  
提供清晰简洁的问题描述。例如："每当......，我总是感到沮丧。"

**描述您想要的解决方案**  
提供清晰简洁的解决方案描述。

**描述您已考虑过的替代方案**  
提供清晰简洁的替代方案或特性说明。

**附加上下文**  
在这里添加有关功能请求的任何其他上下文或截图。
![image](https://user-images.githubusercontent.com/131218298/232937680-f205abfc-7acd-476d-829a-a545a8be9c41.png)

**Comment by mushan0x0** [comment]
在设置界面点三次重置按钮可以吗

**Comment by RiverJJJ** [comment]
> 

可以了。但是之前的对话不在了，100多条对话啊，我可以是付费了的

**Comment by mushan0x0** [comment]
对话是没有同步到服务器的。。。后面可以考虑做一下。。
