### ISSUE TITLE
会话里对话数较多时，性能就下降很明显，滚动等交互操作变慢

### ISSUE THREAD

**Issue by Otiguy** [mushan0x0/AI0x0.com#227]
**描述错误**
会话里对话数较多时，性能就下降很明显，滚动等交互操作变慢

**截图**

![image](https://user-images.githubusercontent.com/48633984/233140849-75485622-6bd5-4d6c-bd0b-5fde28ff6654.png)

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]  Win10x64
 - 系统版本 [例如，11]

**其他上下文**

**Comment by Yidadaa** [comment]
@mushan0x0 需要升级一下 ChatGPT Next Web，我在新的版本中修复了性能问题。

**Comment by mushan0x0** [comment]
> @mushan0x0 需要升级一下 ChatGPT Next Web，我在新的版本中修复了性能问题。

收到，今晚上安排一下

**Comment by mushan0x0** [comment]
已修复
