### ISSUE TITLE
新版本poe有bug 内测版没有

### ISSUE THREAD

**Issue by moooooooooooooooooooooooooooooooooooooj** [mushan0x0/AI0x0.com#228]
**描述错误**
清晰而简明地描述错误是什么。
兄弟 新版本poe有bug 左边选择ai的那个打开poe过两秒就收进去了
**截图**
如果适用，请添加截图以帮助解释您的问题。
01是刚打开poe ， 02是打开过了一两秒
**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]
win11
**其他上下文**
在此添加有关问题的任何其他上下文。
![01](https://user-images.githubusercontent.com/38418090/233233067-d3bb76b4-b36a-4088-8a2b-039442c066c0.png)
![02](https://user-images.githubusercontent.com/38418090/233233070-fe0e2e43-0ccf-4f10-a1b2-127e609e1b00.png)

**Comment by mushan0x0** [comment]
1.4.7已修复
