### ISSUE TITLE
双屏幕下悬浮窗显示问题.

### ISSUE THREAD

**Issue by canyanol650** [mushan0x0/AI0x0.com#229]
悬浮窗在两个屏幕上乱跳.

![动画1](https://user-images.githubusercontent.com/42194280/233237289-0ee21eb6-21ea-4f56-bbed-a5dd79125fc3.gif)

**Comment by canyanol650** [comment]
录屏已经上传.

**Comment by mushan0x0** [comment]
这个目前是正常的。。为了能在两个屏幕使用
