### ISSUE TITLE
去掉鼠标随航后还是会跟着一起动

### ISSUE THREAD

**Issue by keilau119** [mushan0x0/AI0x0.com#230]
**描述错误**
清晰而简明地描述错误是什么。
去掉鼠标随航后还是会跟着一起动
**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
<img width="132" alt="image" src="https://user-images.githubusercontent.com/29084441/233241047-3b99faed-dd4f-4d5b-a03c-1e182e928381.png">
随航是这个功能，你说的一起动是指的啥

**Comment by keilau119** [comment]
就是这个图标跟着鼠标走
![image](https://user-images.githubusercontent.com/131149190/233241620-d85b133e-1796-4b90-99c7-32644cac04e5.png)

**Comment by mushan0x0** [comment]
那应该是卡住了，退出重新打开一下应用吧

**Comment by keilau119** [comment]
好的，我试试
