### ISSUE TITLE
新必应无法使用

### ISSUE THREAD

**Issue by alrcatraz** [mushan0x0/AI0x0.com#231]
在选择模型为新必应后，页面提示要加入等待列表
但点击加入等待列表、页面跳转处理后，又回到了原来的页面
没有登录，也没有别的选项，也没有变化
或者添加一个用自己账号登录的功能如何？

**Comment by mushan0x0** [comment]
这个是代理的问题，要代理微软服务，然后可以在设置里把自己的代理地址写上去

**Comment by alrcatraz** [comment]
> 这个是代理的问题，要代理微软服务，然后可以在设置里把自己的代理地址写上去

我自己开着梯子（clash）了，但是仍面临这个问题
我应该在哪里填写这些设置呢？

**Comment by mushan0x0** [comment]
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/29084441/233253076-3513338e-045d-45fd-b9df-92ef499d9c9f.png">
这里可以填你的代理软件的地址，然后把微软服务代理上
<img width="309" alt="image" src="https://user-images.githubusercontent.com/29084441/233253160-4514a562-1c9b-4f46-8aa0-40f6c4c50264.png">

**Comment by alrcatraz** [comment]
> <img alt="image" width="1000" src="https://user-images.githubusercontent.com/29084441/233253076-3513338e-045d-45fd-b9df-92ef499d9c9f.png">
> 
> 这里可以填你的代理软件的地址，然后把微软服务代理上
> <img alt="image" width="309" src="https://user-images.githubusercontent.com/29084441/233253160-4514a562-1c9b-4f46-8aa0-40f6c4c50264.png">

还是不太好使

**Comment by mushan0x0** [comment]
你的账号还没有加入白名单吗，要加入了白名单才能使用

**Comment by alrcatraz** [comment]
> 你的账号还没有加入白名单吗，要加入了白名单并且通过了才能使用

我有一个账号加入白名单并通过了，但不是我现在登录Windows系统使用的账号

**Comment by mushan0x0** [comment]
可能自动登录你系统的账号了，这个没办法控制，你可以试试切换一下系统的账号

**Comment by alrcatraz** [comment]
能加一个自己输入账号密码登录的选项吗？

**Comment by mushan0x0** [comment]
不行，这个是newbing自己登录的

**Comment by alrcatraz** [comment]
那就有点可惜了……我的365订阅、网盘什么的都在这个账号，如果单为了能用新必应而换一个账号还是有点不方便的 
如果将来有解决办法了，烦请务必告诉我，感激不尽！

**Comment by mushan0x0** [comment]
你可以先用网页申请一下吧，申请过了应该就可以了

**Comment by alrcatraz** [comment]
> 你可以先用网页申请一下吧，申请过了应该就可以了

我的这个主账号之前申请过，被提示出错了请重试，可能是当时被判定为大陆账号，拒绝给我提供新必应试用

**Comment by mushan0x0** [comment]
好吧悲剧了。。
