### ISSUE TITLE
可以让他学习一种脚本语言的语法后来帮我写代码或者debug

### ISSUE THREAD

**Issue by keilau119** [mushan0x0/AI0x0.com#232]
**您的功能请求是否与问题有关？请描述。**  
我是做集成电路行业的，用到的脚本语言都比较特殊，不是通用的。
所以想让机器人可以先把我的脚本语言语法读入并学习，然后帮我完成工作。
比如skill语言，svrf语言等。可以搜一下

**描述您想要的解决方案**  
把我的脚本语言语法读入并学习，然后帮我完成工作。

**描述您已考虑过的替代方案**  
国外有一款叫My askAI，可以将pdf等文档上传让机器人学习，然后可以根据文档中的内容进行交流。
通过这个我得到的启发。

**附加上下文**  
有问题可以随时跟我交流，jingiceman@126.com

**Comment by mushan0x0** [comment]
后面会加这个功能

**Comment by keilau119** [comment]
老板，这个功能大概什么时候会推出来？我可以协助帮你做测试的

**Comment by mushan0x0** [comment]
应该下个月吧

**Comment by keilau119** [comment]
好的，到时候更新我来试试

**Comment by mushan0x0** [comment]
<img width="608" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/bc162deb-14d6-449b-bff9-b98e14d8b2fe">
用这个功能就能实现了，在里面告诉他你的编程语言怎么使用
