### ISSUE TITLE
poechat窗口打开有问题？只有最大化窗口才能显示完整

### ISSUE THREAD

**Issue by clxcoo** [mushan0x0/AI0x0.com#233]
**描述错误**
清晰而简明地描述错误是什么。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
有截图吗，poechat页面本身做得就比较烂。。

**Comment by negoahz** [comment]
![image](https://user-images.githubusercontent.com/119467577/233281296-b22dba9d-c758-4ffc-ab61-2cf4cef35c5b.png)
目前测试只有在使用sage的时候会这样

**Comment by mushan0x0** [comment]
1.4.7已修复
