### ISSUE TITLE
更新处理太不友好。电脑一晚上没关机，第二天一大堆更新弹窗

### ISSUE THREAD

**Issue by liucheng0325** [mushan0x0/AI0x0.com#234]
![image](https://user-images.githubusercontent.com/30199594/233268568-e90beab6-cd9e-42ca-94fd-2a195006201e.png)

**Comment by mushan0x0** [comment]
下个版本优化一下

**Comment by suidu-pro** [comment]
> 下一个版本优化下一下

是的，动不动就更新，一天能更新N次

**Comment by mushan0x0** [comment]
> > 下一个版本优化下一下
> 
> 是的，动不动就更新，一天能更新N次

公测版本是这样的

**Comment by mushan0x0** [comment]
已经修复，下个版本生效
