### ISSUE TITLE
为什么点了下载没反应

### ISSUE THREAD

**Issue by spongehah** [mushan0x0/AI0x0.com#236]
# 请附上截图或者录屏！！！！！和系统版本！！！！

**描述错误**
清晰而简明地描述错误是什么。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
应该是网太差了，你也可以在这里下载 https://github.com/mushan0x0/AI0x0.com/releases
