### ISSUE TITLE
双屏幕问体

### ISSUE THREAD

**Issue by 1135288997** [mushan0x0/AI0x0.com#237]
# 请附上截图或者

https://user-images.githubusercontent.com/42299380/233752400-fce6c20b-181e-4b73-b458-012167dd90e4.mp4
![11](https://user-images.githubusercontent.com/42299380/233752206-37725005-7707-4cd8-b797-2522638125c1.png)

录屏！！！！！和系统版本！！！！

**描述错误**
双屏幕时候，登陆图窗和切换Chat的小球跟着鼠标左右切换，鼠标在第二屏幕时候，就不能移动。我这里说的并不是鼠标随行，请不要误会。自动输入功能是不好使的。
这里我们用户的需求是1.让小球像360加速球一样，能够用户想放在哪个屏幕都可以不要在第二屏幕上锁定。
                                     2.像360加速或其他软件一样，可以设置自动隐藏在屏幕边缘边缘
每次都跟着动，有完全隐藏功能，就是不想用。
1.在第二屏幕不要锁定小球
2.可以靠边隐藏
3.不要跟着动，这个跟着动实在是太烦了，一直挡视线。包括登陆界面也是有跟着动和锁定的问题。
4.生成文档自动输入功能不好用，没反应，但是我可以手动复制粘贴。这个影响不大可以接受。

希望作者对与用户提出的问题认真负责。我们是真的爱这款软件，才大早上写这么多字的。说这么多话。希望它变得更好有更多人使用。我们并不介意捐赠一些钱，给开发者小哥加加鸡腿。你们辛苦啦，感谢。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]
 - 

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
生成文档自动输入这个1.4.7修复了

**Comment by 1135288997** [comment]
好的，收到了。谢谢。

**Comment by 1135288997** [comment]
但是我的电脑仍然不行。我朋友电脑也是不行。输入根本不好使。请看视频。说实话，我可以手动，复制粘贴，但是有自动输入那就更完美了。昨天试过50多次就成功输入过一次。还有，自动生成到一半，点停止生成也能输入。但生成就不完整了。
两个视频一个是baichat一个是chat0X0都不行。
https://user-images.githubusercontent.com/42299380/233767385-1709a4fa-59bd-4f7c-8fdd-c898a86281eb.mp4

**Comment by 1135288997** [comment]
感觉你好厉害啊，这么年轻就能开发软件。

**Comment by 1135288997** [comment]
我用的是office2019的word，换成WPS已经完美解决了，说明chat0X0和Office兼容性不强，和WPS完全没有问题。但是输入功能对我来说，不重要。我可以手动复制粘贴，另外输入功能在我的Matlab上面也输入不了。不过已经很好了。希望作者可以让浮动球侧边隐藏，不要让它跟着鼠标在左右屏幕跑来跑去的，遮挡视线。

**Comment by 1135288997** [comment]
有相同问题的看过来，想自动输入文档的尽量用WPS，不要用Office。我是忍受不了WPS的广告，一会就卸载了。

**Comment by 1135288997** [comment]
悬浮球问题已经解决，在主屏下按住悬浮球一直拖动，直到把它拖动到副屏幕右上角，就可以自动隐藏了

**Comment by 1135288997** [comment]
已经下载新版了，我提出两个问题已经完美解决了，太感谢你了。我不想买会员，因为baichat和chatgpt和nebing够我用了。对我来说gpt3.5就够用，用不上gpt4.但我想赞助20块钱，我还是学生，钱不多,就想表达心意。希望我们多多贡献力量，别让这个软件停止运营了。在哪里赞助，等我以后有钱会持续赞助的。

**Comment by 1135288997** [comment]
找不到赞助入口，我留下联系方式吧，电话18098868872。你可以叫我龙骑士，哈哈。需要支持，就知会一声，我是你粉色了。电话微信相同。 我不会私聊，就在这里留言吧。加油，兄弟。软件用起来很方便，希望更好，哈哈哈哈。

> 生成文档自动输入这个1.4.7修复了

**Comment by mushan0x0** [comment]
感谢，项目主页最下面有赞助入口哈

**Comment by mushan0x0** [comment]
都没问题了吗

**Comment by mushan0x0** [comment]
看视频好像输入还有问题

**Comment by 1135288997** [comment]
完美没有问题了，我的视频时旧版本还没有更新的

**Comment by mushan0x0** [comment]
好的那就ok
