### ISSUE TITLE
chatgpt一直进不去，一直确认是否真人，用浏览器则不用

### ISSUE THREAD

**Issue by aquaua** [mushan0x0/AI0x0.com#240]
**描述错误**
chatgpt一直进不去，一直确认是否真人，用自己的浏览器则不会出现这种问题
一直显示确认您是真人，点了也进不去，就一直显示

**截图**
以下是使用AI0x0
![image](https://user-images.githubusercontent.com/53467807/233772720-ed29e820-bd46-4e13-9035-904b26e890c8.png)
以下是使用edge dev
![image](https://user-images.githubusercontent.com/53467807/233772850-c52577a3-23f1-41d4-8a35-c8a9e728fa0f.png)

**系统（请填写以下信息）：**
 - 系统名称：Windows
 - 系统版本：11

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/29084441/233772811-87344479-3b94-4ca0-8c23-aad618917679.png">
我这里没问题，你试试在设置里点三次重置按钮呢，这个跟节点也有关系

**Comment by aquaua** [comment]
重置了，还是不行，节点应该是没问题的，因为在edge里面可以秒开

**Comment by aquaua** [comment]
寄了，它好像在一直刷新，根本进不去

**Comment by mushan0x0** [comment]
你试试在设置里的代理地址填自己的代理软件的地址可以吗

**Comment by aquaua** [comment]
试过了，也不行
可能是内置浏览器问题？
因为我在登陆poe时也出现了问题
![image](https://user-images.githubusercontent.com/53467807/233773991-bec433ce-a589-44b2-a8a6-19e5f0afaad6.png)

**Comment by mushan0x0** [comment]
我等会打个包你再试试吧

**Comment by aquaua** [comment]
好的，麻烦你了
ps：你的软件真的非常好用！每天学习工作已经离不开了。
pss：建议未来付费将使用chat0x0和其他功能分开付费，或者推出单个功能订阅或买断功能。

**Comment by mushan0x0** [comment]
谢谢支持，新版更新在 ai0x0.com 官网了，你下载看看可以吗

**Comment by aquaua** [comment]
可以了，谢谢你
