### ISSUE TITLE
可以自定义接入一些其他AI吗，比如Perplexity ai、Paper digest等

### ISSUE THREAD

**Issue by aquaua** [mushan0x0/AI0x0.com#241]
以下为这两个网站：
https://www.perplexity.ai/
一种高效的会话搜索引擎，提供快速流畅的搜索资料且提供参考文献而不失准确性
https://www.paperdigest.org/review/
可以提供相关文献的相关工作，并写成一段文字
还有其他一些有用的网站

建议1：
一种可以自定义的ai网站接入方式，可以方便的将其他非官方ai整合在一起
建议2：
一个聚合搜索，可以同时展现多个ai的回答

ps：简单打赏了30块钱，学生党没钱小小的支持一下。（单纯对开发大大的付出感谢一下）

**Comment by mushan0x0** [comment]
安排

**Comment by Beauforto** [comment]
好强

**Comment by ManCherish** [comment]
牛逼，我也是想着能否把notion AI或者正在使用的LunaBot都集成到OxO里，这样就太好用了。现在使用的是quicker里的一个动作，也是可以集成notion AI和chatgpt的key

**Comment by mushan0x0** [comment]
Perplexity ai 已添加，但自定义不行，因为要处理很多问题
