### ISSUE TITLE
悬浮球能否改为前期可以设置默认是回车输入模式

### ISSUE THREAD

**Issue by mukgong** [mushan0x0/AI0x0.com#243]
# 请附上截图或者录屏！！！！！和系统版本！！！！

**描述错误**
建议将悬浮球的默认输入模式设置为回车键，更加方便地进行操作。目前的操作方式需要按下command+回车，非常不方便。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[m2 air]
 - 系统版本 [最新]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
<img width="371" alt="image" src="https://user-images.githubusercontent.com/29084441/233819449-f38ad2c8-990e-4332-9728-b72497ad7075.png">
可以用气泡里的输入按钮，也可以直接输入

**Comment by mukgong** [comment]
如果开启前台调度无法快速实现这个功能。

**Comment by mushan0x0** [comment]
我试了开启前台调度也不影响使用呀，可以发个录屏看看吗
