### ISSUE TITLE
启用AI0x0时与到了无法定位程序输入点DiscardVirtualMemory于动态链接库KERNEL32.dll上

### ISSUE THREAD

**Issue by moneyzjy2016** [mushan0x0/AI0x0.com#244]
# 请附上截图或者录屏！！！！！和系统版本！！！！
**描述错误**
清晰而简明地描述错误是什么。
启用AI0x0时与到了无法定位程序输入点DiscardVirtualMemory于动态链接库KERNEL32.dll上
**截图**

如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：Windows
 - 系统版本 ：7旗舰版

**其他上下文**
在此添加有关问题的任何其他上下文。
![QQ截图20230423111828](https://user-images.githubusercontent.com/22446233/233817857-35cfa1dd-5ed7-4994-a835-b70e6c47fdc1.png)

**Comment by mushan0x0** [comment]
win7暂不支持
