### ISSUE TITLE
功能建议-输入框

### ISSUE THREAD

**Issue by YanMu2020** [mushan0x0/AI0x0.com#245]
目前直接使用输入框频数不高
如果一直让悬浮框放到中央，感觉比较碍眼
![image](https://user-images.githubusercontent.com/75877299/233819084-8f581b13-638a-43ff-a3c2-96c58c1bbabd.png)
能否像notion这种模式，按一下空格(快捷键)，屏幕中央显示，但不按快捷键，屏幕中央不会显示任何东西
![image](https://user-images.githubusercontent.com/75877299/233819145-e5c06169-ebb0-4ff8-a487-7d03093261e8.png)
这样感觉在写东西的时候，好像更加切合一些

**Comment by mushan0x0** [comment]
不太行，因为需要鼠标移动上去查看对话

**Comment by mushan0x0** [comment]
可以拖动到屏幕右边，可以隐藏
