### ISSUE TITLE
通知栏图标右键检查更新存在BUG

### ISSUE THREAD

**Issue by zhangsong1111** [mushan0x0/AI0x0.com#247]
# 请附上截图或者录屏！！！！！和系统版本！！！！

**描述错误**
通知栏小图标右键点击选择检查更新后，第一次点击会没有反应，然后第二次点击恢复正常，但是过了一会之后，大约1小时左右系统会自己弹出检查更新的结果

**截图**
如果适用，请添加截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/131578937/233825437-ba0fc96d-962a-49eb-9634-396a700dbdc7.png)

**系统（请填写以下信息）：**
 - 系统名称：[WIN10
 - 系统版本 [10]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
已修复
