### ISSUE TITLE
关于一些优化的建议

### ISSUE THREAD

**Issue by Cagsirn** [mushan0x0/AI0x0.com#25]
**1. 快捷键调出+自动隐藏：**

- 使用鼠标或组合快捷键呼出窗口，随用随走
- 打开窗口后可自由选择常驻置顶

**2. 预设调用**

- 建议在问题输入以后再选择预设，目前的版本我不清楚是不是我不会用，点击搜索按钮打开输入框，点击选择预设，然后输入框就自动关闭了，再打开还需要重新选择预设，陷入了死循环，建议优化

**Comment by Cagsirn** [comment]
New bing 我通过了，魔法我也有了，所以到底要怎么在这个插件里调用New bing

**Comment by mushan0x0** [comment]
newbing使用门槛太高现在还不能使用

**Comment by mushan0x0** [comment]
选择预设要用键盘上下按键选择

**Comment by mushan0x0** [comment]
已优化
