### ISSUE TITLE
双屏 跳闪问题

### ISSUE THREAD

**Issue by 195255** [mushan0x0/AI0x0.com#251]
win10 系统

34寸 带鱼屏 +27寸 1080

附上视频

https://user-images.githubusercontent.com/32062892/234273496-a3f8d6f9-de16-4d09-946b-21a725439d30.mp4

无法跨屏 
![image](https://user-images.githubusercontent.com/32062892/234272302-9acb8862-5d68-47ec-8046-50e1866c85a8.png)

这个图标 比较碍事 最好能贴上隐藏

**Comment by mushan0x0** [comment]
贴到右边可以隐藏

**Comment by 195255** [comment]
![image](https://user-images.githubusercontent.com/32062892/234286534-04033408-fb28-43f9-b416-b85dfe4136c3.png)
左边的屏幕 依然不能隐藏

**Comment by hudonghu** [comment]
我也遇到了这个问题

**Comment by mingliao** [comment]
同样碰到这个问题，而且cpu占用过高

**Comment by callhong** [comment]
mac m1 双屏悬浮窗一直闪动

**Comment by mushan0x0** [comment]
> mac m1 双屏悬浮窗一直闪动

闪动可以录屏看看吗

**Comment by callhong** [comment]
![image](https://github.com/mushan0x0/AI0x0.com/assets/24239721/7ef7b158-44f7-4dd8-b575-7b3f9af10dbc)

**Comment by callhong** [comment]
https://github.com/mushan0x0/AI0x0.com/assets/24239721/8352ebe3-f1d5-4edb-9f95-4c81e7a73fc5

**Comment by callhong** [comment]
![image](https://github.com/mushan0x0/AI0x0.com/assets/24239721/7f49dc4f-eae0-4707-a266-fb1b09b371ea)

**Comment by mushan0x0** [comment]
> ![image](https://user-images.githubusercontent.com/24239721/238525057-7f49dc4f-eae0-4707-a266-fb1b09b371ea.png)

好的收到

**Comment by mushan0x0** [comment]
可以试试 1.5.3 可以了不
