### ISSUE TITLE
一直验证是否真人

### ISSUE THREAD

**Issue by cqzqxq** [mushan0x0/AI0x0.com#252]
# 请附上截图或者录屏！！！！！和系统版本！！！！
![image](https://user-images.githubusercontent.com/131844076/234560170-42bc004b-6ef6-4800-9da2-bd68ea497abb.png)

**描述错误**
清晰而简明地描述错误是什么。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
没有复现，可以换节点试试，应该是代理的问题
