### ISSUE TITLE
mac链接多个屏幕的时候，在副屏上图标无法移动，点击无效

### ISSUE THREAD

**Issue by liangliangwqy** [mushan0x0/AI0x0.com#253]
Mac OS 13.2.1

**Comment by mushan0x0** [comment]
mac x64下载地址：https://ai0x0-track.oss-cn-beijing.aliyuncs.com/test-versions/AI%200x0_1.4.9_x64.dmg

mac arm64下载地址：https://ai0x0-track.oss-cn-beijing.aliyuncs.com/test-versions/AI%200x0_1.4.9_arm64.dmg

试试这个版本可以吗
