### ISSUE TITLE
0x0集成的chatGPT出现不能运行的问题。

### ISSUE THREAD

**Issue by rosn7828** [mushan0x0/AI0x0.com#257]
0x0升级后，chatGPT不能做出回应（如截图）
![image](https://user-images.githubusercontent.com/17957518/235289199-d2887c37-96d9-4312-8df0-19a960e37edd.png)

**Comment by mushan0x0** [comment]
感谢反馈已经修复，chatgpt升级导致的，你在 http://ai0x0.com/ 重新下一次看看呢

**Comment by rosn7828** [comment]
----- 原始邮件 -----
发件人：mushan0x0 ***@***.***>
收件人："mushan0x0/AI0x0.com" ***@***.***>
抄送人：rosn7828 ***@***.***>,  Author ***@***.***>
主题：Re:_[mushan0x0/AI0x0.com]_0x0集成的chatGPT出现不能运行的问题。_(Issue_#257)
日期：2023年04月29日 16点28分


感谢反馈已经修复，chatgpt升级导致的，你在 http://ai0x0.com/ 重新下一次看看呢

**Comment by mushan0x0** [comment]
刷新几次界面呢

**Comment by rosn7828** [comment]
刷新后仍然存在，至我反馈问题的现在chatGPT仍一直处于旋转状态。

**Comment by rosn7828** [comment]
![image](https://user-images.githubusercontent.com/17957518/235299582-14b021c9-b7af-47b7-a7d5-ce2043f3ca7a.png)

**Comment by mushan0x0** [comment]
应该跟网络也有点关系

**Comment by rosn7828** [comment]
网络是很好的，到今天4月30日问题仍然没有解决啊。

**Comment by mushan0x0** [comment]
<img width="999" alt="image" src="https://user-images.githubusercontent.com/29084441/235335545-b81c5004-5750-4613-9a95-e771bc98355f.png">
我这里没问题，看看还没有人会遇到吧

**Comment by rosn7828** [comment]
问题修复了，辛苦你们了，请问下，如果我成为了会员 ，只能用chat0x0吗？其他的能用吗？比如：Perplexity、ChatGPT、PoeChat、NewBing、BaiChat能用吗？
----- 原始邮件 -----
发件人：mushan0x0 ***@***.***>
收件人："mushan0x0/AI0x0.com" ***@***.***>
抄送人：rosn7828 ***@***.***>,  Author ***@***.***>
主题：Re:_[mushan0x0/AI0x0.com]_0x0集成的chatGPT出现不能运行的问题。_(Issue_#257)
日期：2023年04月30日 12点30分



我这里没问题，看看还没有人会遇到吧

&mdash;

**Comment by mushan0x0** [comment]
其他的免费也能用的，只要有梯子，付了费会有个加速服务，用了加速就可以不用梯子了

**Comment by rosn7828** [comment]
好的，意思是付了费不仅可以用chat0x0，其他的如Perplexity、ChatGPT、PoeChat、NewBing、BaiChat也能用是吧。

**Comment by mushan0x0** [comment]
别的都能用，只要你有梯子，付了费用加速的话就可以不用梯子了
