### ISSUE TITLE
更新到最新版本后出现这个。

### ISSUE THREAD

**Issue by laley235** [mushan0x0/AI0x0.com#258]
![image](https://user-images.githubusercontent.com/99822044/235296656-99a69332-edeb-41e2-8384-c6aea2c2cd7f.png)

**Comment by mushan0x0** [comment]
https://ai0x0.com/ 官网重新下载可以吗

**Comment by laley235** [comment]
可以重新下载，但是还是这样

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.4.9 这个版本可以不

**Comment by laley235** [comment]
![image](https://user-images.githubusercontent.com/99822044/235297005-698b8b59-3c63-4b0a-ba79-46dcf0c0c1f7.png)
安装后提示这样

**Comment by laley235** [comment]
更新前可以用，更新后就这样了

**Comment by mushan0x0** [comment]
重启电脑试试呢。。。

**Comment by laley235** [comment]
![image](https://user-images.githubusercontent.com/99822044/235297182-536f3a1b-3c82-4e79-9056-54b60bad2f7a.png)
重启了，重新安装，依然不行

**Comment by mushan0x0** [comment]
管理员身份运行呢

**Comment by laley235** [comment]
![image](https://user-images.githubusercontent.com/99822044/235299385-93f9a546-3a3c-4c4b-b19f-8577fb7105a3.png)
还是不行

**Comment by roczhou2018** [comment]
升级到 1.4.12 后刷不出来了，重装了 1.4.2 可以了，不过卸载时手快删掉了以前的聊天记录 (lll￢ω￢)

**Comment by laley235** [comment]
问题解决了ma ?

**Comment by mushan0x0** [comment]
可能是什么安全软件导致的把快捷方式删掉了，实际上应该是已经安装了

**Comment by laley235** [comment]
奇怪，我并没有安装杀毒软件，系统自带的也给我禁止了
