### ISSUE TITLE
1.4.10 依然出现的问题 右下角图标 无法双击显示

### ISSUE THREAD

**Issue by 195255** [mushan0x0/AI0x0.com#259]
**问题1：**
右下角图片 双击 无法激活 窗体
这个用起来很窝心

还有那个图标 能不能不显示

非常鸡肋 不如就老老实实 窗体运行~

也许就是那个顶上的 图标 弄的 不能夸屏

这个软件挺不错 不过不能夸屏的 这个也是第一个

**问题2**
自动更新问题
请不要直接后台强制更新！给个选项 是否愿意自动升级！
有时候比较稳定的时候 未必想升级到新版本
起码看了新版本更新了什么内容 再决定要不要升级啊

**Comment by 195255** [comment]
https://user-images.githubusercontent.com/32062892/235309874-63c9c478-9416-4c98-a066-715ea59845a8.mp4

附上图标点击无响应视频

**Comment by mushan0x0** [comment]
已经支持了，悬浮球在小图标右键可以隐藏的，因为没有win电脑和显示器所以双屏问题不太好完美支持，更新是需用用户点了更新才会更新的
