### ISSUE TITLE
没什么大用

### ISSUE THREAD

**Issue by Hunterho528** [mushan0x0/AI0x0.com#260]
没什么价值，不能提供ai早就能做到的创造性解决问题方案：输入大数据、大文本、或多模态资料，从中提取关联信息、建立联系、规律和模型。你产品的唯一亮点仅仅是提供了便利的提示词，而提示语哪里都可以找到和生成。所谓集成、多选、通用，没必要。建议抓住痛点，让你的集成和通用功能服务于解决创造性问题。

**Comment by mushan0x0** [comment]
需要gpt4开放
