### ISSUE TITLE
5月2号更显后 chatgpt 的模型登录不上 

### ISSUE THREAD

**Issue by momoddo** [mushan0x0/AI0x0.com#262]
在设置中添加了API后 CHATGPT也不能免登录

5月2号更显后 chatgpt 的模型登录不上

**Comment by mushan0x0** [comment]
添加api只会对chat0x0生效，chatgpt需要自己账号的，登录不上是指什么情况

**Comment by momoddo** [comment]
选了CHATGPT的模型后就一直这样 右上的按钮一直转圈
从 Windows 版邮件发送

发件人: mushan0x0
发送时间: 2023年5月2日 22:41
收件人: mushan0x0/AI0x0.com
抄送: momoddo; Author
主题: Re: [mushan0x0/AI0x0.com] 5月2号更显后 chatgpt 的模型登录不上 (Issue #262)

添加api只会对chat0x0生效，chatgpt需要自己账号的，登录不上是指什么情况

**Comment by mushan0x0** [comment]
在 ai0x0.com 再下载一次看看可以不呢，刚才更新了一下

**Comment by momoddo** [comment]
好的 我一会试试重新下载



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mushan0x0 ***@***.***&gt;
发送时间: 2023年5月3日 13:40
收件人: mushan0x0/AI0x0.com ***@***.***&gt;
抄送: momoddo ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [mushan0x0/AI0x0.com] 5月2号更显后 chatgpt 的模型登录不上  (Issue #262)





 
在 ai0x0.com 再下载一次看看可以不呢，刚才更新了一下
