### ISSUE TITLE
2023-5-3号除了自带Chat0*0,其它界面用魔法都上不去

### ISSUE THREAD

**Issue by JqZhou-DLMU** [mushan0x0/AI0x0.com#264]
**描述错误**
基于win10系统，ChatGPT官方原版界面都能进入，但是AI 0*0进不去。排除了梯子的问题。

**Comment by JqZhou-DLMU** [comment]
已经能进去了，清楚具体原因是什么，一个小时一直转圈圈。刷新不出来界面。

**Comment by mushan0x0** [comment]
ai0x0.com 下载最新的试试呢

**Comment by Swinden** [comment]
> ai0x0.com 下载最新的试试呢

新版的也这样

**Comment by mushan0x0** [comment]
今天的版本呢

**Comment by Swinden** [comment]
> 今天的版本呢

现在CR刷新一下好像行了

**Comment by JqZhou-DLMU** [comment]
新版本可以了，上一个版本，刷半天都出不来，急死人了，谢谢大神
