### ISSUE TITLE
将文库按钮添加到主界面上

### ISSUE THREAD

**Issue by x18613770815** [mushan0x0/AI0x0.com#268]
是否考虑将文库按钮添加到主界面上，新增两项功能
1.可以指定一个/多个文件进行分析
2.文库内可添加文件夹，将文件按用途进行分类

![1111111111](https://user-images.githubusercontent.com/50504551/236368593-447bd5da-1157-493c-aa76-6ed4b2c60e63.png)

**Comment by mushan0x0** [comment]
<img width="1468" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/b306b504-36bd-46fa-b716-7d26dfcfefb0">
用这个吧，方便好用很多
