### ISSUE TITLE
当前版本联网搜索没有跳转的网页连接

### ISSUE THREAD

**Issue by gyk185yyds** [mushan0x0/AI0x0.com#269]
# 请附上截图或者录屏！！！！！和系统版本！！！！
![image](https://user-images.githubusercontent.com/124658969/236370729-a82d42cd-6852-44a8-8b07-fa76a5ecf7a2.png)

**描述错误**
清晰而简明地描述错误是什么。
当前版本联网搜索没有跳转的网页连接，上一个版本可以
**截图**
如果适用，请添加截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/124658969/236370729-a82d42cd-6852-44a8-8b07-fa76a5ecf7a2.png)
![image](https://user-images.githubusercontent.com/124658969/236370811-de1dbbe8-ecca-42c9-a221-3507876d9cc1.png)

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]
 - 系统名称：Windows
 - 系统版本 10
**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
加上了
