### ISSUE TITLE
mac 软件退出容易崩溃

### ISSUE THREAD

**Issue by tao-xiaoxin** [mushan0x0/AI0x0.com#27]
只要退出软件就会提示软件崩溃,请问这是正常的吗?
<img width="296" alt="image" src="https://user-images.githubusercontent.com/77662409/226183960-9974ec80-cfa7-46eb-a46a-653e769ab347.png">

**Comment by mushan0x0** [comment]
不正常，这个我们这边观察一下

**Comment by tao-xiaoxin** [comment]
更新软件后解决了
