### ISSUE TITLE
谷歌登录问题

### ISSUE THREAD

**Issue by Swinden** [mushan0x0/AI0x0.com#270]
# 请附上截图或者录屏！！！！！和系统版本！！！！

**描述错误**
清晰而简明地描述错误是什么。
谷歌登录出现截图中的问题，之前也出现过，不知道怎么还没又可以登录了，现在又这样
**截图**
如果适用，请添加截图以帮助解释您的问题。
![image](https://user-images.githubusercontent.com/96880842/236383196-4b7ede8b-4a8e-4560-9eb8-a50b91cc1e85.png)

**系统（请填写以下信息）：**
 - 系统名称：[例如，Windows]
 - 系统版本 [例如，11]
win10

**其他上下文**
在此添加有关问题的任何其他上下文。

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.5.9 可以试试这个可以不

**Comment by mushan0x0** [comment]
已修复
