### ISSUE TITLE
外面放出来的安卓版本是你做的吗？简直一模一样

### ISSUE THREAD

**Issue by manzhonglu** [mushan0x0/AI0x0.com#272]
- 

![2](https://user-images.githubusercontent.com/131781092/236593476-44b2d939-278e-4655-b2d3-5813caef70a4.jpg)
![3](https://user-images.githubusercontent.com/131781092/236593477-ca965c37-f022-4497-817b-7b57a46929cb.jpg)
![4](https://user-images.githubusercontent.com/131781092/236593483-70b6abd5-0a04-4920-a86d-ae5172f23693.jpg)
![5](https://user-images.githubusercontent.com/131781092/236593486-4063338a-89e3-429e-bfc9-12d78ac1f4ca.jpg)
![1](https://user-images.githubusercontent.com/131781092/236593490-869b01c4-85ad-43b9-a0ff-b12c632d97a9.jpg)

**Comment by 1173922902** [comment]
> ![2](https://user-images.githubusercontent.com/131781092/236593476-44b2d939-278e-4655-b2d3-5813caef70a4.jpg) ![3](https://user-images.githubusercontent.com/131781092/236593477-ca965c37-f022-4497-817b-7b57a46929cb.jpg) ![4](https://user-images.githubusercontent.com/131781092/236593483-70b6abd5-0a04-4920-a86d-ae5172f23693.jpg) ![5](https://user-images.githubusercontent.com/131781092/236593486-4063338a-89e3-429e-bfc9-12d78ac1f4ca.jpg) ![1](https://user-images.githubusercontent.com/131781092/236593490-869b01c4-85ad-43b9-a0ff-b12c632d97a9.jpg)

应该是个简单的内置浏览器APP，还是访问的作者的网站chat.ai0x0.com
不过访问密码不知道如何拿到的，可能是抓包一类吧

**Comment by 1173922902** [comment]
应该是个简单的内置浏览器APP，还是访问的作者的网站chat.ai0x0.com
不过访问密码不知道如何拿到的，可能是抓包一类吧

**Comment by mushan0x0** [comment]
https://github.com/Yidadaa/ChatGPT-Next-Web 这个是一个开源项目，人人都可以部署的
