### ISSUE TITLE
希望可以增加聊天历史记录随账号同步功能

### ISSUE THREAD

**Issue by LI-100** [mushan0x0/AI0x0.com#273]
想要在不同设备登录的时候总能同步之前的聊天记录

**Comment by wc4443329445** [comment]
gpt3.5不支持

**Comment by JackloveJam** [comment]
目前我用的最频繁、最多的是 Claude。是在slack中集成的应用。有手机端！并且聊天记录是实时同步的！
回答问题比3.5的gpt 好很多，可能是数据比较新?

**Comment by JackloveJam** [comment]
补充一下。
该公司现在又出来一个Claude 2.
https://claude.ai/
请使用英国和美国IP注册账号即可使用。
//

并且我看到最新的AI0X0也集成了。
1.5.45 [Latest](https://github.com/mushan0x0/AI0x0.com/releases/latest)
新增：

**Claud 200k 模型**
邀请用户注册可得佣金
鼠标随航可以上传文件，目前只支持 Claud 200k

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v3.4.0-alpha 已支持
