### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by billgrandon** [mushan0x0/AI0x0.com#274]
Mac 电脑更新最新版本，用不了。一直显示A JavaScript error occurred in the main process。

**Comment by mushan0x0** [comment]
有截图吗

**Comment by billgrandon** [comment]
A Javascript error occurred in
the main process
Uncaught Exception:
TypeError: Cannot read properties of
undefined (reading 'show")
at App.sanonymous> (Applications/Al
0x0.app/Contents/Resources/app.asar/
dist-electron/main/create-window/init-
chat-window.jjs:51:14)
at App.emit (node:events:513:28)
这是全部内容。截图上传不了，麻烦看看。谢谢👍

**Comment by mushan0x0** [comment]
ai0x0.com 在官网下载一下最新版吧

**Comment by billgrandon** [comment]
就是最新版才有这个问题，之前旧的版本都没有这个问题。

**Comment by mushan0x0** [comment]
官网下载一下吧，自动更新的有点问题

**Comment by billgrandon** [comment]
没问题了，官网下载的可以了。谢谢
