### ISSUE TITLE
登录页面一直在1毫米的左右晃动，鼠标点击时候是正常的，有时候不正常

### ISSUE THREAD

**Issue by gumdamxxx** [mushan0x0/AI0x0.com#277]

**Comment by mushan0x0** [comment]
可以发一下录屏吗

**Comment by gumdamxxx** [comment]
不仅仅是晃动 还会影响quicker软件获取当前鼠标所在窗口
从 网易邮箱大师 发来的云附件
|
| |
| |
|
| |
| VID_20230510_094723.mp4 |
| |
| (31.2M,2023年05月25日 09:49 到期) |
| |
| 下载 |
| |
| |




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月08日 19:00 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [mushan0x0/AI0x0.com] 登录页面一直在1毫米的左右晃动，鼠标点击时候是正常的，有时候不正常 (Issue #277) |

可以发一下录屏吗

**Comment by mushan0x0** [comment]
看不到录屏，可以到issue里来上传一下吗..

**Comment by gumdamxxx** [comment]
邮箱发了录屏，更新了版本，还是抖动，而且和净网大师之类的软件有冲突，我抓取别的软件页面句柄时候，抓到的是你的软件。

**Comment by mushan0x0** [comment]
可以传到issues里吗，邮箱看不到...
