### ISSUE TITLE
预设包一直加载是怎么回事？？？

### ISSUE THREAD

**Issue by billlhuhuhu** [mushan0x0/AI0x0.com#278]
设置里预设那里一直显示暂无数据

**Comment by billlhuhuhu** [comment]
就是通过浮窗点击添加预设，之后那个预设那里一直转圈。

**Comment by mushan0x0** [comment]
是最新版吗，重新打开可以不

**Comment by billlhuhuhu** [comment]
是最新版的

**Comment by billlhuhuhu** [comment]
<img width="499" alt="gpt" src="https://user-images.githubusercontent.com/132970255/236988761-68ee32f0-dbc0-4b13-8155-ecca4e04b5e4.png">

**Comment by billlhuhuhu** [comment]
请你看一下呢，就一直转圈，是我还需要下载什么东西吗，还是需要做什么操作，这样那个功能就用不了了，好难受

**Comment by mushan0x0** [comment]
是不是开了加速或者代理啥的
