### ISSUE TITLE
一直转圈圈点不开

### ISSUE THREAD

**Issue by xiaosongcailanzi** [mushan0x0/AI0x0.com#281]
一直转圈圈点不开是什么原因呀，卸载了重装还是一样
![1](https://github.com/mushan0x0/AI0x0.com/assets/133093035/06d04290-7baf-4273-b373-14a0f4d9b029)

**Comment by xiaosongcailanzi** [comment]
还是不行哎，之前都是好的，有一天忽然提示要更新，然后我点了下就变成这样了

**Comment by xiaosongcailanzi** [comment]
还是不行哎，之前都是好的，有一天忽然提示要更新，然后我点了下就变成这样了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mushan0x0/AI0x0.com"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月10日(星期三) 下午3:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mushan0x0/AI0x0.com] 一直转圈圈点不开 (Issue #281)





 
https://cowtransfer.com/s/3143ef1557224d 点击链接查看 [ AI 0x0_1.4.15_x64.exe ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 kcxp89 查看；
 
试试这个版本可以不

**Comment by mushan0x0** [comment]
https://cowtransfer.com/s/3491246ff02842 点击链接查看 [ AI 0x0_1.4.15_x64.exe ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 5q8ssv 查看；

那再试试这个可以不。。

**Comment by xiaosongcailanzi** [comment]
还是不得行

**Comment by mushan0x0** [comment]
575539890 你加一下这个群吧，我帮你看看
