### ISSUE TITLE
权限申请有点可怕

### ISSUE THREAD

**Issue by Dcell** [mushan0x0/AI0x0.com#29]
Mac 打开App，就提示申请控制电脑，麦克风，屏幕等，不敢用

**Comment by mushan0x0** [comment]
以后这部分会优化的，目前只有预设列表同步了服务器，其他都是本地使用的

**Comment by marxlan** [comment]
Mac安装1.2.6  怎么都没有看到GPT悬浮按钮啊？

**Comment by JackHvikee** [comment]
> 以后这部分会优化的，目前只有预设列表同步了服务器，其他都是本地使用的

悬浮球是否可以增加一个关闭按钮呢，很多时候我仅想在app内使用（主要是悬浮球现在有bug压根点不动，马车外接显示器）

**Comment by mushan0x0** [comment]
申请提示已经优化
