### ISSUE TITLE
目前发现2个位置比较卡。

### ISSUE THREAD

**Issue by es3344520** [mushan0x0/AI0x0.com#292]
一个是设置的时候调参数，这里是指Chatoxo里面的设置，调整模型参数的时候有点卡。 另一个桌面就是这个搜索框， 反应比较慢， 而且有时候文字输入太多的话会卡，复制文字直接粘贴进去的时候文字太多的时候也会卡。 明明已经是在搜索了，但是就是反应慢没出来。 最后直接搜索了好几遍。 不知道为啥就是用起来整体没有网页版流畅，用的1.5.2版本  苹果m1设备。       另外没有Claude，这个也挺好用的。

**Comment by mushan0x0** [comment]
你下载的是arm64的版本的吗，claude在poe里面

**Comment by es3344520** [comment]
> 你下载的是arm64的版本吗，claude在poe里面  

是ARM64   另外软件里面定制ChatGPT Next Web不能够切换模型。以及余额查询。
 
我再说一下这个联网功能。可能对于普通的文章可以查得到，当然我也没有全部测试。不过我尝试 搜索关于股票或者加密货币之类的专业信息，就感觉到明显是有问题的， 信息来源主要是 知乎。 这里面的信息不准确，主要体现在价格方面以及最新消息方面。这个和没有联网差别不大。 
还有就是比如这个问题，查一下中欧医疗创新股票a。目前它的负责人是谁。 这个信息也不准确。  所以联网功能对于普通问题应该是可以的。但涉及到数据相关的或者投资理财类的还不行。 
联网功能还需优化。 看好它。  继续加油 

 
另外我使用的时候会出现这个问题，不知道什么情况。 我在网页版用没问题哎 哪怕是1分钟请求多次。用的key。

{
    "error": {
        "message": "Rate limit reached for default-gpt-3.5-turbo in organization org-P0neYyqz08Usx7UxdQb4RVba on requests per min. Limit: 3 / min. Please try again in 20s. Contact us through our help center at help.openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.",
        "type": "requests",
        "param": null,
        "code": null
    }
}

**Comment by mushan0x0** [comment]
用自己的key都容易出现这个错误的，自己的免费key openai会有限制。卡顿的问题可以录屏看看吗

**Comment by es3344520** [comment]
> 用自己的key都容易出现这个错误的，自己的免费key openai会有限制。卡顿的问题可以录屏看看吗

可能我这边也有原因，这个软件包200多m，安装之后更大， 我还要运行其它软件。所以导致了这个问题。 不用那个小框搜索就没事。 刚刚又发现， 有时候会出现无法输入中文的情况， 能输入英文， 但是把中文粘贴进去之后 可以输入中文了。这个在定制的定制ChatGPT Next Web里面会出现， 其他地方还需要检查一下。  目前主要是联网搜索 比较鸡肋。 可以先优化这方面

**Comment by mushan0x0** [comment]
联网搜索目前就是搜索用的，要搜索特定网站或者领域的数据这个需要插件来完成的，中文那个可以录屏看一下吗，不然不好排查

**Comment by es3344520** [comment]
> 联网搜索目前就是搜索用的，要搜索特定网站或领域的数据这个需要插件来完成的，中文那个可以录屏看一下吗，不然不好排查 
 
那再碰到了再录屏。
 
主要是这个联网搜索，比如查一下中欧医疗创新股票a。目前它的负责人是谁。百度可以搜到。 定制的ChatGPT Next Web就不行。 能不能这样，在配置角色的时候，可以自定义网站，然后采集相关信息，这样就不需要完全依赖搜索

**Comment by mushan0x0** [comment]
可以直接打开浏览器的这个页面，使用应用查询就可以了，不用那么麻烦

**Comment by es3344520** [comment]
> 可以直接打开浏览器的这个页面，使用应用查询就可以了，不用那么麻烦

 
我的意思是配置人设  然后自定义几个网站。 那么这个人设只能采集来自自定义网站的信息。  现在的搜索只适用于普通信息。 领域或者投资理财类的最新信息都不行。 即便是目前的应用查询，也只是从网站获取关键词然后 搜索信息。 但是信息的来源却不是网站的， 就比如网站有最新的消息，但是通过应用查询 的信息反馈是不精准信息或者是以前的信息。

**Comment by mushan0x0** [comment]
这个现在实现不了的，这个需要他们的网站提供接口做成插件才可以，不会不会像人一样去浏览这些网站的

**Comment by es3344520** [comment]
> 这个现在实现不了的，这个需要他们的网站提供接口做成插件才可以，gpt不会像人一样去浏览这些网站的

 
那只能先解决目前的问题了，简单的问题， 百度搜索回复正常， 联网功能搜索回复不准确。  下面给出的参考链接，打开页面信息显示都是准确的。

**Comment by mushan0x0** [comment]
用的数据源不一样，百度的大部分都是无效的数据，现在用的bing的，至少能保证大部分数据是正常的，不可能所有情况都覆盖到的

**Comment by mushan0x0** [comment]
不能复现卡顿问题
