### ISSUE TITLE
360报毒，被查杀

### ISSUE THREAD

**Issue by KS-OTO** [mushan0x0/AI0x0.com#293]
最新版本：V1.5.2.0

本是低版本，开启360情况下，无法自动完成更新，无奈关闭360后进行升级操作，升级成功后，360报毒；
下载渠道：安装包直接在 GitHub 释放下载的
![image](https://github.com/mushan0x0/AI0x0.com/assets/6616413/418ba8d6-861b-4696-8de2-0b767b371c69)
![image](https://github.com/mushan0x0/AI0x0.com/assets/6616413/a91d1f6a-2efa-47e6-94e6-afd208eec77b)

**Comment by mushan0x0** [comment]
没事这个是误报的
