### ISSUE TITLE
悬浮窗显示异常

### ISSUE THREAD

**Issue by miracle1103** [mushan0x0/AI0x0.com#294]
悬浮窗会莫名其妙显示各种各样的小图标,像微信,谷歌,资源管理器等的图标.之前都没有出现过,就更新到最新版本后出现了,如下面所示,请作者大大帮忙看看哈!
![微信截图_20230515135825](https://github.com/mushan0x0/AI0x0.com/assets/37585258/1e1580cc-7946-4690-b26d-74a37cc716d5)

**Comment by mushan0x0** [comment]
这是新功能 https://www.bilibili.com/video/BV1Hk4y1L72q

**Comment by miracle1103** [comment]
@mushan0x0    Soga,还以为Bug呢,大佬🐂🍺!
