### ISSUE TITLE
悬浮球不显示

### ISSUE THREAD

**Issue by callhong** [mushan0x0/AI0x0.com#299]

**Comment by mushan0x0** [comment]
你是什么系统什么软件版本的，是用的多屏吗，退出软件重新打开也不行吗

**Comment by callhong** [comment]
昨天mac M1 1.5.2 是双屏跳闪，然后因为一个对话超时一直输出中，一直转圈，就不知道怎么把球关了
球一直不显示了，今天特意升到1.5.3 还是不行
退出软件不行，重启mac还没试过

**Comment by mushan0x0** [comment]
在设置里，点三次重置按钮重置一下软件试试吧

**Comment by callhong** [comment]
重置可以了
