### ISSUE TITLE
小白提问，怎么安装？

### ISSUE THREAD

**Issue by H153243048** [mushan0x0/AI0x0.com#30]
怎么安装？

**Comment by lllkkkwert** [comment]
ai0x0.com去下载

**Comment by H153243048** [comment]
即使科学上网也打不开
&nbsp;


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mushan0x0/AI0x0.com"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月20日(星期一) 下午5:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mushan0x0/AI0x0.com] 小白提问，怎么安装？ (Issue #30)





 
ai0x0.com去下载

**Comment by lixiang666-rgb** [comment]
安装提示 需要64位Windows 系统   有解决方案吗

**Comment by lllkkkwert** [comment]
你的难道不是64位的？！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月21日(周二) 下午3:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mushan0x0/AI0x0.com] 小白提问，怎么安装？ (Issue #30)




 
安装提示 需要64位Windows 系统   有解决方案吗

**Comment by mushan0x0** [comment]
不支持32位的。。
