### ISSUE TITLE
Poe经常会处于转圈加载的状态

### ISSUE THREAD

**Issue by negoahz** [mushan0x0/AI0x0.com#303]
Poe经常会处于转圈加载的状态，虽然能够正常使用，但是悬浮图标下面会一直显示查询后的内容，且悬浮图标一直转圈，切换其他AI时比较麻烦

**Comment by mushan0x0** [comment]
下个版本修复

**Comment by Pa55w0rd** [comment]
> 下个版本修复

第一个P开头的ai工具，选择了联网，现在都好几个小时了，还在转圈，也没有办法切换其他的工具，一直没有管他，还在转圈

**Comment by mushan0x0** [comment]
已修复
