### ISSUE TITLE
是否是强制需要开会员呢？那种模式都是报网络错误，能否可以自己设置api代理使用呢？这样就无需翻墙了

### ISSUE THREAD

**Issue by itxtl** [mushan0x0/AI0x0.com#304]
<img width="186" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/28883383/1bbc9fe4-3916-4970-8cbc-199566d29dd0">
<img width="941" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/28883383/2f965ea1-183f-4c8b-a839-f076cda47a10">

**Comment by mushan0x0** [comment]
梯子问题，可以在设置里设置自己的代理，并不会强制用户开会员

**Comment by mushan0x0** [comment]
chat0x0是不需要翻墙的，无法访问应该是网络运营商的问题

**Comment by Pa55w0rd** [comment]
> chat0x0是不需要翻墙的，无法访问应该是网络运营商的问题

建议增加自己的代理api使用
