### ISSUE TITLE
毛玻璃界面在哪里关闭

### ISSUE THREAD

**Issue by Pa55w0rd** [mushan0x0/AI0x0.com#306]
![image](https://github.com/mushan0x0/AI0x0.com/assets/16274549/c006e100-7bf1-4af6-b47d-ae76068607f3)
kanbuqing看不清楚字体

**Comment by Pa55w0rd** [comment]
> 刷新一下就好了

刷新了也是这样，看不清楚

**Comment by mushan0x0** [comment]
你改过chat0x0主题吗，在悬浮球设置里切换一下主题可以不

**Comment by mushan0x0** [comment]
已经修复，在 ai0x0.com 重新下载就行了
