### ISSUE TITLE
poe怎么登录

### ISSUE THREAD

**Issue by UncleSunQvQ** [mushan0x0/AI0x0.com#310]
1.用谷歌账号登录的话会显示“不安全”
![1](https://github.com/mushan0x0/AI0x0.com/assets/86462354/7420582c-a025-4604-8177-af50cf6c1f34)

2.用邮箱登录的话一直loading
![2](https://github.com/mushan0x0/AI0x0.com/assets/86462354/1733a413-f4ac-4ab8-ba40-e79cb01671bf)

3.用手机号的话最后还是要绑定邮箱
请教一下现在怎么登录poe啊！

**Comment by mushan0x0** [comment]
用手机号就可以了，绑定一下吧

**Comment by UncleSunQvQ** [comment]
但是绑定邮箱的时候还是会一直loading，所以现在登录不上去

**Comment by pyroxenites** [comment]
用邮箱，poe会给你的gmail发验证码

**Comment by mushan0x0** [comment]
也可以现在网页上 https://poe.com/ 注册后在 0x0 里使用

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.5.9 可以试试这个可以不

**Comment by UncleSunQvQ** [comment]
我现在已经1.5.11了  还是不行，能不能想想办法把显示不安全给通过啊

**Comment by UncleSunQvQ** [comment]
解决了

**Comment by UncleSunQvQ** [comment]
解决了

**Comment by xiaobei666** [comment]
楼上怎么解决的  我和一直loading 我是谷歌邮箱直接可以

**Comment by Llxyyds666** [comment]
只是节点没有挂全局,我看了一下F12网络请求里面还是zh-cn

**Comment by Llxyyds666** [comment]
> > 楼上怎么解决的 我和一直loading 我是谷歌邮箱直接可以
> 
> 
> 
> 我也是这个问题
> 
> 

挂全局试一下喽
