### ISSUE TITLE
请添加  讯飞星火认知大模型.

### ISSUE THREAD

**Issue by ryanzhaorx** [mushan0x0/AI0x0.com#315]
请添加  讯飞星火认知大模型.

**Comment by mushan0x0** [comment]
<img width="1320" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/130c1296-e21a-4c4f-bef6-9c8377c8a576">

已经有了，在 ai0x0.com 重新下载一次吧

**Comment by Pa55w0rd** [comment]
> <img alt="image" width="1320" src="https://user-images.githubusercontent.com/29084441/240698954-130c1296-e21a-4c4f-bef6-9c8377c8a576.png">
> 已经有了，在 ai0x0.com 重新下载一次吧

每次都触发行为验证，不好用
