### ISSUE TITLE
聊天窗口控件问题

### ISSUE THREAD

**Issue by axunrun** [mushan0x0/AI0x0.com#321]
不知道是个案还是都有，我的系统是WIN11,当我想把聊天窗口通过鼠标在窗口边拖拽进行缩放的时候。这个缩放的过程变得非常的卡顿，整个缩放动态感觉像慢动作一样，鼠标很容易拉过头。

**Comment by mushan0x0** [comment]
这个确实有点问题，后面修复一下

**Comment by lbj-007** [comment]
> 这个确实有点问题，后面修复一下

dalao啥时候修复啊，鼠标一拖动整个窗口直接变形了，很影响体验

**Comment by mushan0x0** [comment]
已修复
