### ISSUE TITLE
macos 11.2.3 (20D91)不能使用

### ISSUE THREAD

**Issue by timesNuku** [mushan0x0/AI0x0.com#323]
系统版本需要多少才能用？

**Comment by mushan0x0** [comment]
11应该可以吧，有报什么错吗

**Comment by mushan0x0** [comment]
你是不是下载到arm64的版本了

**Comment by timesNuku** [comment]
<img width="540" alt="图片" src="https://github.com/mushan0x0/AI0x0.com/assets/134681587/6c2364e9-4ea8-44a2-8e8f-3c2178fba1f4">

确实是下载的默认的arm64，直接显示不能使用

**Comment by mushan0x0** [comment]
https://ghproxy.com/https://github.com/mushan0x0/AI0x0.com/releases/download/v1.5.12/AI-0x0_1.5.11_x64.dmg

**Comment by mushan0x0** [comment]
用这个吧
