### ISSUE TITLE
谷歌的Bard咋样，是否考虑添加呢

### ISSUE THREAD

**Issue by LiSonglin-xidian** [mushan0x0/AI0x0.com#326]
谷歌推出的Bard是否考虑呢？https://bard.google.com/?hl=en

**Comment by mushan0x0** [comment]
bard不支持中文，不好用

**Comment by shdsj5784** [comment]
加入一下360智脑，这个国产第一，画图逼真已经有博主测评了

**Comment by mushan0x0** [comment]
360的没有开放

**Comment by shdsj5784** [comment]
已经可以申请内测了

**Comment by jerryliang122** [comment]
是否可以增加Chatglm-6B？

**Comment by shdsj5784** [comment]
![image](https://github.com/mushan0x0/AI0x0.com/assets/103811922/266d8aa6-8ea5-43e8-9a13-d3a128253352)

**Comment by shdsj5784** [comment]
> 360的没有开放

![image](https://github.com/mushan0x0/AI0x0.com/assets/103811922/c9e052b2-5870-42fb-9a3b-02d63f3d8b97)

**Comment by shdsj5784** [comment]
> 360的没有开放

![image](https://github.com/mushan0x0/AI0x0.com/assets/103811922/50ea6383-9843-4d6d-9836-cfda4d448cea)

**Comment by Pa55w0rd** [comment]
> 60的没有开

申请试用，大概一天就通过了    ，https://ai.360.cn/
![1688438247333](https://github.com/mushan0x0/AI0x0.com/assets/16274549/b0790e2b-56fd-4778-87a5-e91012e8b5d8)

**Comment by mushan0x0** [comment]
360太low了
