### ISSUE TITLE
建议给“毛玻璃界面”设置一个开关

### ISSUE THREAD

**Issue by RealZST** [mushan0x0/AI0x0.com#327]
毛玻璃界面的透明度太高，在深色背景的时候，会看不清字。希望设置一个开关，或用户自定义透明度，谢谢。
![CleanShot 2023-05-27 at 17 51 16](https://github.com/mushan0x0/AI0x0.com/assets/53246001/e4413145-5723-4955-ac20-f7aa35d72c36)

**Comment by mushan0x0** [comment]
应该是chatgpt没有背景色导致的，下个版本修复一下

**Comment by mushan0x0** [comment]
1.5.12已修复
