### ISSUE TITLE
鼠标跟随在word上的BUG

### ISSUE THREAD

**Issue by axunrun** [mushan0x0/AI0x0.com#330]
在word打一行字，然后全选后让AI书写内容。全选的时候能够看到word的图标显示在0x0上，如果这个时候操作很快，选择书写内容，就可以正常使用。但如果操作较慢，word图标就会换掉，这个时候就算选择了书写内容，也无法在word上正常输出。感觉是这个识别软件的锁定锁到别的软件上去了。

**Comment by mushan0x0** [comment]
你看看这个时候的悬浮球上的应用是啥，可能跟这个应用冲突了

**Comment by mushan0x0** [comment]
可以再提供一下录屏吗

**Comment by axunrun** [comment]
> 可以再提供一下录屏吗

https://github.com/mushan0x0/AI0x0.com/assets/97007105/b93ab948-3cf2-4c7c-b776-2aa61f1c8295

可以从视频看出，当鼠标在悬浮上停留后，后台程序被切换，然后被锁定在上面，具体锁定的是什么程序看不出来。感觉是0X0本身。

**Comment by mushan0x0** [comment]
<img width="433" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/514d3f18-3df0-4ac0-b42e-a1db57b6a926">
好像跟这个程序冲突了，这是个啥程序

**Comment by axunrun** [comment]
> <img alt="image" width="433" src="https://user-images.githubusercontent.com/29084441/241652082-514d3f18-3df0-4ac0-b42e-a1db57b6a926.png"> 好像跟这个程序冲突了，这是个啥程序

问题已经找到，因为开启了输入法的悬浮窗，遇到同类问题的可以参考
<img width="265" alt="微信截图_20230529140055" src="https://github.com/mushan0x0/AI0x0.com/assets/97007105/757a3f7a-7d1d-4816-9b4a-bc6e8afd4529">

**Comment by mushan0x0** [comment]
我看看可以修复不

**Comment by mushan0x0** [comment]
1.5.12已修复
