### ISSUE TITLE
改进查询体验

### ISSUE THREAD

**Issue by ggbondpx** [mushan0x0/AI0x0.com#331]
我觉得作者还有几个方面可以考虑改进一下的：
1.浮窗菜单消失时间可以自定义，现在有时候消失得太快了；
2.浮窗选择AI类型或者选择预设的时候是否可以提供额外的选择，例如设置成不展开，而是用滚轮进行滚动选择，感觉这样会大大提高效率。
谢谢！

**Comment by mushan0x0** [comment]
感谢反馈，后面会优化一下

**Comment by ggbondpx** [comment]
感谢开发大神对各种Bug的及时改进。浅浅提一下查询体验的改进意见：浮窗小界面可做考虑增加一个预设的提示图标。这样一来，浮动小窗=AI图标+预设图标（可以用设置表情包提示对应预设文字，减少面积占用）+搜索图标。鼠标位于每一个图标区域后可以鼠标滚轮滚动选择不同选项，左键确认。这样子就可以不展开AI菜单实现选择AI，不展开预设菜单选择预设（如果当前任务是润色英文，而目前老是处于默认查询，每次都要重新选就很烦）。还有关于菜单消失的问题，我觉得其实可以提供一个不会自动消失的选项，其实很多翻译软件都是提示图标出现后，如果不需要只需要点击其他区域就可以，这样子就不会老是焦虑菜单会消失，其实提示图标足够小的话不自动消失影响不大。最后，只是个人小小的意见，谢谢~

**Comment by mushan0x0** [comment]
已经优化，预设可以通过场景隐藏部分
