### ISSUE TITLE
MAC 版里面顶部菜单栏里不显示这个软件的相关信息

### ISSUE THREAD

**Issue by HH40012SWFU** [mushan0x0/AI0x0.com#335]
MAC 版里面顶部菜单栏里不显示这个软件的相关信息

**Comment by mushan0x0** [comment]
已修复

**Comment by HH40012SWFU** [comment]
仍然没有解决。之前的版本反而没有这个问题。

**Comment by mushan0x0** [comment]
你具体指的啥，这个不显示吗
<img width="152" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/0ec027ea-797b-44a4-b22d-f352621e35f4">

**Comment by HH40012SWFU** [comment]
是的，没有显示。

**Comment by mushan0x0** [comment]
不会吧，这个怎么可能不显示，是不是哪里设置了
