### ISSUE TITLE
无法打开官网，

### ISSUE THREAD

**Issue by wank1st** [mushan0x0/AI0x0.com#336]
我无法打开官网请尝试：

检查连接
[检查代理和防火墙](chrome-error://chromewebdata/#buttons)
[运行 Windows 网络诊断](javascript:diagnoseErrors())
ERR_CONNECTION_RESET
我是充值了的软件提示加载失败也是打不开，以前没有这种问题
通过刷新有时候能打开官网或者软件，很小的几率

**Comment by mushan0x0** [comment]
这个是你使用网络运营商的问题，如果实在用不了可以发账号发我邮箱，给你退一下费

**Comment by wank1st** [comment]
我想用啊，你这个需要墙么现在

**Comment by mushan0x0** [comment]
不需要翻墙，但是可能被你的运营商屏蔽了，但是翻墙应该可以解决

**Comment by wank1st** [comment]
那为啥有时候 可以用，但是需要不停的点刷新

**Comment by mushan0x0** [comment]
不太清楚，这个大部分人都是可以直接使用，没有问题的

**Comment by wank1st** [comment]
我用的是移动的网络

**Comment by mushan0x0** [comment]
有几个人跟你一样的问题，他们也是移动网络，估计是移动网络的锅

**Comment by wank1st** [comment]
我去网上搜搜看解决问题吧，你的软件不错，我很支持，希望得到更好的优化

**Comment by mushan0x0** [comment]
嗯嗯这个问题我这边也不知道怎么解决，那先关了吧

**Comment by mushan0x0** [comment]
https://www.ai-chat.top/ 你看看这个可以访问不

**Comment by wank1st** [comment]
网站已经正常了，

**Comment by mushan0x0** [comment]
那就好
