### ISSUE TITLE
我是抖音技术博主IT老邪，希望能跟您建立联系

### ISSUE THREAD

**Issue by ice3270** [mushan0x0/AI0x0.com#337]
我是抖音技术博主IT老邪（目前抖音也有近15W粉丝），希望能跟您建立联系，最近我有计划出一套跟AI相关的课程内容，所以也在找相关的工具。看您这个工具比较适合在课程里面使用，我目前也有很多学员，想着是否能将这个产品推广给我目前以及将来的学员。能否有一些优惠的扶持。比如试用或者是付费的专属优惠等。ice_wan@msn.cn是我的个人邮箱，希望得到您的回复。

**Comment by mushan0x0** [comment]
感谢你对 AI0x0 的认可，但是目前我们还没有分销系统，或者兑换码系统，所以暂时还不能满足你的需求，后面有了这类功能我会发邮件告知你的，感谢。
