### ISSUE TITLE
启动时报错: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by alrcatraz** [mushan0x0/AI0x0.com#338]
![image](https://github.com/mushan0x0/AI0x0.com/assets/45288295/7ce586f7-de04-4620-8732-9a86bb562665)

**Comment by mushan0x0** [comment]
重启一下电脑试试呢

**Comment by alrcatraz** [comment]
最近用过大约三次AI 0x0，都报这个错。虽然软件似乎能正常用，但是报错还是报了

**Comment by mushan0x0** [comment]
https://juejin.cn/post/7012177280944472095

你看看7047端口是被啥占用了

**Comment by alrcatraz** [comment]
查了一下，好像没有占用

**Comment by mushan0x0** [comment]
无法复现
