### ISSUE TITLE
用你们工具对话出字的速度明显慢于我此前用原生的侧边栏bing的出字速度。

### ISSUE THREAD

**Issue by ffgg536956** [mushan0x0/AI0x0.com#340]
我是没有付费用户。。 使用你们工具里面内置的 po e里面的chatGPT模型的 对话速度明显慢于我此前用浏览器直接打开的 po e里面的chatGPT模型速度， 当我切换到 new   bing的时候发现速度更慢了。我是哪里设置出错了吗？ 我所开的代理速度挺快的呢，我用 edge浏览器 的侧边栏对话速度也是非常快，为什么同样的网络代理网络。在你们工具这里速度这么慢呢。下面图片就是我做了一个实验对比，同样的一个问题，在相同时间内。你们这个工具出字的速度比我用原声的侧边栏bing 要慢很多。我是哪里设置出错了吗？

![360截图20230531151340745](https://github.com/mushan0x0/AI0x0.com/assets/133084034/16e2476b-6987-4c8d-a126-424e78c87b1f)

**Comment by mushan0x0** [comment]
可以录屏对比一下吗

**Comment by ffgg536956** [comment]
上面的图片就是一个对比图，同样的时间， 同样的问题。左边的是用你们的软件的只有几行字，而原生侧边栏bing 出了特别多的字了。 但刚才更新了最新版之后，你们的软件出字速度提升了很多。目前已经 可以接受了。 @mushan0x0 
![360截图20230531151340745](https://github.com/mushan0x0/AI0x0.com/assets/133084034/2f5d4e19-f459-42d8-874e-6bddc38a69f9)
