### ISSUE TITLE
能不能在一些提示词里面添加一个判断

### ISSUE THREAD

**Issue by jyj12345** [mushan0x0/AI0x0.com#342]
能不能在一些提示词中添加判断，如果我没有写要求，就不会有要求这两个字
比如文章润色：
![image](https://github.com/mushan0x0/AI0x0.com/assets/68804563/bfab1878-b328-4004-98b8-62ca776d8e5c)

![image](https://github.com/mushan0x0/AI0x0.com/assets/68804563/e85a1a41-0cf0-4373-9f3d-39cc175d2d7f)

**Comment by mushan0x0** [comment]
我调整了一下，重新打开应用试试吧

**Comment by jyj12345** [comment]
可以
