### ISSUE TITLE
chatgpt被锁

### ISSUE THREAD

**Issue by Kidleyh** [mushan0x0/AI0x0.com#347]
更新最新版gpt就被锁，回退版本gpt就正常

**Comment by fgaoyang** [comment]
最新版的GPT用不了

**Comment by mushan0x0** [comment]
<img width="507" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/b0343b78-486c-4a06-b1a9-f7a9337795aa">
可以先在这里填上自己的代理地址

**Comment by mushan0x0** [comment]
1.5.16已修复
