### ISSUE TITLE
连接显示器的时候，显示器这一侧的悬浮球一直在闪烁

### ISSUE THREAD

**Issue by codecomeon** [mushan0x0/AI0x0.com#349]

**Comment by codecomeon** [comment]
macos 13.4
![CleanShot 2023-06-07 at 14 12 09](https://github.com/mushan0x0/AI0x0.com/assets/39626330/05546989-0e01-4810-9dba-7b34f0b7009c)

**Comment by mushan0x0** [comment]
可以录屏看看吗

**Comment by codecomeon** [comment]
![CleanShot 2023-06-08 at 09 55 44](https://github.com/mushan0x0/AI0x0.com/assets/39626330/e6259ad7-f0b1-4748-8d31-3986d5234079)
这个是闪烁的效果，在我连的显示器上。然后如果焦点在我内置显示器上面，是没问题的，一旦聚焦到外接显示器，就开始这样闪烁了。

**Comment by mushan0x0** [comment]
同样使用外接显示器，无法复现
