### ISSUE TITLE
newbing作画时候，提示登陆必应图像创建器，这个能怎样联动？

### ISSUE THREAD

**Issue by sfantacy** [mushan0x0/AI0x0.com#353]
![image](https://github.com/mushan0x0/AI0x0.com/assets/36142262/2fac7999-8fcb-447a-80dd-1f6b027d7c63)
[https://github-production-user-asset-6210df.s3.amazonaws.com/36142262/245049596-2fac7999-8fcb-447a-80dd-1f6b027d7c63.png](url)

**Comment by sfantacy** [comment]
![image](https://github.com/mushan0x0/AI0x0.com/assets/36142262/59a4a4c0-afd8-4690-9e2f-e92afd415ac6)

**Comment by mushan0x0** [comment]
只能在官网使用
