### ISSUE TITLE
在多屏幕使用时，浮球的问题

### ISSUE THREAD

**Issue by 498271674** [mushan0x0/AI0x0.com#357]
因为两块屏幕分辨率不一样，所以把浮球放在a屏幕上合适的位置，操作b屏幕时浮球自动转移到b屏幕后就会出现在一个很尴尬的位置。
比如在1920*1080屏幕上拖到[1880.560]，当我去2560*1440的屏幕上操作时，浮球的位置仍然在[1800.560]，然而这个位置在小屏幕上是差不多贴靠屏幕右侧边缘，在大屏幕上则是右侧3/4的位置。
反之，如果先在2560*1440屏幕上把浮球放到屏幕最右侧，浮球从大屏幕移动到小屏幕时会自动展开输入框随后自动关闭，从小屏幕移动到大屏幕则会在“之前在小屏上的绝对位置”处闪现一次再回到正确位置。
建议增加一个浮球不随鼠标在屏幕间移动，或者在移动浮球时使用相对位置而非绝对位置，又或者（最希望）能够独立定义浮球在每块屏幕上的位置。

**Comment by mushan0x0** [comment]
1.5.41已修复
