### ISSUE TITLE
似乎在有界面，比如橙瓜码字上，无法有效引出指针

### ISSUE THREAD

**Issue by kevin9406** [mushan0x0/AI0x0.com#359]
显示的页面不对，就是GPT左上角哪个，要么是上一个在别的页面勾选的，要么就是无效空输入

**Comment by mushan0x0** [comment]
录屏看看呢

**Comment by kevin9406** [comment]
> 录屏看看呢

首先在码字界面，指针唤起无用，其次选中了之后用ALT+1的方式，显示的是空页面
不好意思，WIN自带的录屏没办法去弄多个界面的录屏，结果只能显示码字界面的，看不出问题，只能用截图来- -如果不清楚，我再去下个截屏软件
![1](https://github.com/mushan0x0/AI0x0.com/assets/49649311/6145722c-53b4-4966-92aa-fe8cce4bbd8e)

![2](https://github.com/mushan0x0/AI0x0.com/assets/49649311/8cc407ec-73df-4668-a402-04d4f1691ed1)

**Comment by mushan0x0** [comment]
别的应用是正常的对吧，可以试试截图对话功能

**Comment by kevin9406** [comment]
> 别的应用是正常的对吧，可以试试截图对话功能

其他的正常，截图似乎还是不行，另外文库的资料他无法读取吗？正确的指令是什么，我让他查询到了文库对应的文档，但是似乎无法完成读取内容，因为测试小说的第一章就告诉了时间和地点
1955年，北京。
![3](https://github.com/mushan0x0/AI0x0.com/assets/49649311/4e2f483e-b7ab-4962-8275-d5307bff621e)

**Comment by mushan0x0** [comment]
今天会优化文库搜索这些功能

**Comment by kevin9406** [comment]
> 常，截图似乎还是不行，另外文库的资料他无法读取吗？正确的指令是什么，我让他查询到了文库对应的文档，但是似乎无法完成读取内容，因为测试小说的第一章就

辛苦大佬了
