### ISSUE TITLE
chat0x0 一直连接错误 ，输入问题显示错误

### ISSUE THREAD

**Issue by happykkAi** [mushan0x0/AI0x0.com#362]
1.ping chat.ai0x0.com 发现网络延迟造成 ，通过修改hosts 更换 ip 地址后还是不能使用。
2.重新安装后，只有第一次输入 可以正常反应，第二次查询就会出现以下代码 。

这是返回的错误代码 
{
  "error": {
    "message": "You exceeded your current quota, please check your plan and billing details.",
    "type": "insufficient_quota",
    "param": null,
    "code": null
  }
}

**Comment by mushan0x0** [comment]
账号余额过期了

**Comment by happykkAi** [comment]
我刚买了季度会员

**Comment by happykkAi** [comment]
昨天买的 正常应该不会  不知道什么原因

**Comment by mushan0x0** [comment]
是不是在设置里输入了自己的key

**Comment by happykkAi** [comment]
是的 我现在删除重置后 恢复了  可以正常使用了
