### ISSUE TITLE
关于对话窗口大小调整及隐藏大模型图标显示的问题

### ISSUE THREAD

**Issue by yud657** [mushan0x0/AI0x0.com#363]
1.希望可以让用户选择显示仅用户需要的大模型，比如我不需要NEW BING或其中任何一个，可以让他不显示在前端
2.用户每次调整完对话框的大小，再次打开的时候会恢复到默认的大小，希望可以保留用户设置过的对话窗口大小

**Comment by mushan0x0** [comment]
1.暂不考虑
2.已支持

**Comment by yud657** [comment]
谢谢采纳！
