### ISSUE TITLE
百度文心窗口不能使用了

### ISSUE THREAD

**Issue by sfantacy** [mushan0x0/AI0x0.com#365]
![image](https://github.com/mushan0x0/AI0x0.com/assets/36142262/445f6b7d-5127-42f9-8d55-057f8133063e)
之前可以，现在突然无法刷新出来了

**Comment by mushan0x0** [comment]
下个版本修复一下

**Comment by mushan0x0** [comment]
已修复，在 ai0x0.com 下载最新版就行了
