### ISSUE TITLE
手机端扫二维码无法显示下载

### ISSUE THREAD

**Issue by wank1st** [mushan0x0/AI0x0.com#366]
手机端扫二维码显示
无法打开页面
错误信息（-6.net::ERR_CONNECTION_RESET）
轻触屏幕重新加载

**Comment by mushan0x0** [comment]
https://ai0x0-chat.zijiancode.cn/ 用手机打开这个地址吧

**Comment by wank1st** [comment]
这是个网页端把嗯。

**Comment by wank1st** [comment]
这是个网页版。打开后说弹出添加到桌面，点了后显示安装，然后就没有反应了。我的是小米手机

**Comment by mushan0x0** [comment]
在桌面搜索一下chat0x0看看呢

**Comment by wank1st** [comment]
桌面的搜索直接对接的是百度
