### ISSUE TITLE
[Bug] chat0x0 页面很不稳定

### ISSUE THREAD

**Issue by NNGTHB** [mushan0x0/AI0x0.com#367]
1. 拖动时窗口会突然变小
2. 拖动时很卡顿，不流畅
3. 拖动时UI页面中的元素不稳定，闪烁和移位
4. 鼠标移上到图标按钮时常乱跳

![动画5](https://github.com/mushan0x0/AI0x0.com/assets/115760745/a9ccb5a4-cc2a-49f1-a358-54838cc09d35)

![动画4](https://github.com/mushan0x0/AI0x0.com/assets/115760745/3a85e056-267e-4ee0-94d6-e8bc1506e0a5)

**Comment by mushan0x0** [comment]
重启一下电脑试试呢

**Comment by NNGTHB** [comment]
> 重启一下电脑试试呢

重启后问题并没有解决，而且设置页面也存在这种问题

![动画6](https://github.com/mushan0x0/AI0x0.com/assets/115760745/0a0654a7-a05e-4deb-8227-9c396c4ad017)

我在想是不是这种玻璃背景样式导致的

![image](https://github.com/mushan0x0/AI0x0.com/assets/115760745/de832d83-61b1-42c6-a79a-de4edcb5d4a6)

**Comment by mushan0x0** [comment]
拖动延迟是透明背景导致的，这个问题不大，下面操作项闪动是因为你窗口设置得太窄了，你可以把左边的对话列表也设置窄一点

**Comment by NNGTHB** [comment]
> 拖动延迟是透明背景导致的，这个问题不大，下面操作项闪动是因为你窗口设置得太窄了，你可以把左边的对话列表也设置窄一点

能不能切换不用透明背景这种样式，就用原版chatgpt-next-web那种就行了，而且问题就在于我把窗口放大后然拖动它直接会自动缩小窗口，反而会让窗口变得更小

**Comment by mushan0x0** [comment]
好像是系统屏幕缩放导致的，你可以设置试试看
