### ISSUE TITLE
今天的Chat0x0是不是有点不稳定？

### ISSUE THREAD

**Issue by MarchBeta2087** [mushan0x0/AI0x0.com#369]
不是说Chat0x0不需要翻墙吗？怎么今天我刷新了好多次，Chat0x0就是用不了（况且我可没配置代理、挂梯子）

**Comment by mushan0x0** [comment]
https://www.zhihu.com/question/602813176 泉州电信的问题

**Comment by MarchBeta2087** [comment]
> https://www.zhihu.com/question/602813176 泉州电信的问题

我知道了，确实如此
