### ISSUE TITLE
关于无法使用的问题

### ISSUE THREAD

**Issue by mushan0x0** [mushan0x0/AI0x0.com#37]
1.ChatGPT 需要账号和梯子
2.NewBing 暂时还没开放
3.BaiChat 服务有时候不稳定，稳定的时候不需要梯子也可以访问
4.文心一言 需要账号

**Comment by 203430** [comment]
所以baichat会出现服务器波动的问题导致无法使用，用梯子是可以解决的是吧？

**Comment by happysusi** [comment]
文心一言点了没反应

**Comment by 203430** [comment]
他是百度的，要预约内测好像

**Comment by happysusi** [comment]
交互体验有点问题，经常点了没反应或者反应慢，点好几次才弹出

**Comment by 203430** [comment]
毕竟是开发中的软件，谅解谅解

**Comment by KissyAllen** [comment]
> 1.ChatGPT 需要账号和梯子 2.NewBing 暂时还没开放 3.BaiChat 服务有时候不稳定，稳定的时候不需要梯子也可以访问 4.文心一言 需要账号

方便加个联系方式合作一下嘛？qq1421655246

**Comment by bunkmr** [comment]
页面写的油箱注册，填写邮箱后，提示不正确的手机号

**Comment by KissyAllen** [comment]
你好，我这边在网上看到了你开发的这款AI0x0软件觉得非常不错，因此想和你这边聊下关于这方面的合作，期待收到你的回复，谢谢




ン梦醒人离╰つ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mushan0x0/AI0x0.com"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月23日(星期四) 下午5:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mushan0x0/AI0x0.com] 关于无法使用的问题 (Issue #37)





 
页面写的油箱注册，填写邮箱后，提示不正确的手机号

**Comment by Martin-dq** [comment]
基于梯子的问题，是否可以在软件内增加代理？

**Comment by KissyAllen** [comment]
那请问你这个是用python和electron框架去实现的嘛？目前我看客户端代码是没有开源的，这边能出售源代码嘛，可以付费购买我想在此基础上做二次开发使用




ン梦醒人离╰つ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mushan0x0/AI0x0.com"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月24日(星期五) 上午10:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mushan0x0/AI0x0.com] 关于无法使用的问题 (Issue #37)





 
如果在软件内增加代理，就产生了收费项目，可以自己找cat的啊便宜且好用

**Comment by hurricanetx** [comment]
> 那请问你这个是用python和electron框架去实现的嘛？目前我看客户端代码是没有开源的，这边能出售源代码嘛，可以付费购买我想在此基础上做二次开发使用 ン梦醒人离╰つ ***@***.*** &nbsp;
> […](#)

electron nodejs 项目

**Comment by 1073661783** [comment]
我的情况是悬浮球只能在桌面显示，不能置顶在所有程序之上，想要使用只能退回桌面

**Comment by hangzaiqy27** [comment]
您好，请问梯子如何搭建？

**Comment by mushan0x0** [comment]
> 您好，请问梯子如何搭建？

新版开加速就行了

**Comment by hangzaiqy27** [comment]
您好，作者 ，我开了加速的，但是还是无法刷新，请问如何解决？

**Comment by hangzaiqy27** [comment]
都是加载失败，请刷新
可以购买嘛？

**Comment by mushan0x0** [comment]
> 都是加载失败，请刷新 可以购买嘛？

要多点几次刷新，收费版本还需要等几天

**Comment by hangzaiqy27** [comment]
点了一下午……请问收费版本，是一次性买断嘛？还是包月的？

**Comment by 1073661783** [comment]
> > 我的情况是悬浮球只能在桌面显示，不能置顶在所有程序之上，想要使用只能退回桌面
> 
> 试试1.2.6可以了吗

更新了，重装好几次，还是不行，悬浮球就是不置顶，一直在最底层，只能在桌面使用。

**Comment by mushan0x0** [comment]
@xingran521 有链接或者截图吗

**Comment by hangzaiqy27** [comment]
到底还能不能用啦……

**Comment by 203430** [comment]
能用啊
