### ISSUE TITLE
打开AI 0x0 1.5.19x64版本后，资源管理器无法双击返回上一层

### ISSUE THREAD

**Issue by yaonai** [mushan0x0/AI0x0.com#372]
打开AI 0x0 1.5.19x64版本后，资源管理器无法双击返回上一层文件夹，退出AI 0x0恢复正常。系统安装有QTTabBar 2048 Beta2，一直可以双击文件夹空白处返回上一层文件夹的。

**Comment by mushan0x0** [comment]
QTTabBar的bug，0x0这边解决不了
