### ISSUE TITLE
Bing无法使用了

### ISSUE THREAD

**Issue by SilenceOBrea1** [mushan0x0/AI0x0.com#374]
自己是可以正常联网使用bing的，0X0显示

**Comment by SilenceOBrea1** [comment]
加载失败
请检查你的网络并重试。如果你频繁遇到网络问题，建议开启网络加速服务后多次点击刷新按钮重试。
或者可以切换到 Chat0x0 聊天通道，稳定不卡顿。

**Comment by mushan0x0** [comment]
已经使用国内nwebing代替

**Comment by Pa55w0rd** [comment]
> 已经使用国内nwebing代替

国内代理的太慢了
