### ISSUE TITLE
使用文心一言的时候，会经常弹出‘’已停止生成‘’

### ISSUE THREAD

**Issue by yud657** [mushan0x0/AI0x0.com#375]
不知是大模型本身的问题，还是咱们软件的问题，盼尽快解决！！！
![99887a5ad8f86bf604c1bde03ba542f](https://github.com/mushan0x0/AI0x0.com/assets/129239394/13a21f76-794f-4c0e-bbac-d80e1f38cab7)

**Comment by mushan0x0** [comment]
是文心一言自己停的，可以使用继续
