### ISSUE TITLE
优化：场景功能里有的软件识别不到

### ISSUE THREAD

**Issue by letianpai-lpt** [mushan0x0/AI0x0.com#379]
建议可以让用户选择软件的文件地址，或者可以设置的时候用一个选择器选择到正在运行的软件窗口。

**Comment by letianpai-lpt** [comment]
比如打游戏，这个窗口
![image](https://github.com/mushan0x0/AI0x0.com/assets/96228495/b5e4976e-4058-438b-8071-0d2d0f5a76fc)

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.5.28 试试这个版本呢

**Comment by letianpai-lpt** [comment]
刚试了试还是没识别到

**Comment by mushan0x0** [comment]
现在会对全屏状态自动隐藏了
