### ISSUE TITLE
软件点不到

### ISSUE THREAD

**Issue by 374046604** [mushan0x0/AI0x0.com#38]
我想问问就我一个MAC 使用根本点不到这软件，就是点击点不到？

**Comment by mushan0x0** [comment]
应该是bug，近期会修复

**Comment by mcyrj** [comment]
我也是mac,M1芯片，系统Monterey。无法点击。目前使用快捷键的时候。可以点击一下。一会就不能点了。

**Comment by mushan0x0** [comment]
> 我也是mac,M1芯片，系统Monterey。无法点击。目前使用快捷键的时候。可以点击一下。一会就不能点了。

升级13系统试试吧，老系统暂时没兼容
