### ISSUE TITLE
添加新的模型以及悬浮气泡弹出问题

### ISSUE THREAD

**Issue by Jing-Loog** [mushan0x0/AI0x0.com#381]
是否考虑集成Forefront Chat。以及。点击屏幕时，出现悬浮搜索气泡的时间过短，很容易造成点击屏幕时间稍长，气泡就会浮现，框选一些文件时，由于时间较长，气泡也会出现。这给我造成了很大影响，以至于不得不关闭开机自启功能，以减少这种经常出现的干扰。希望增加单击屏幕时，悬浮气泡出现时间的设置，以消除这种不经意产生的干扰。

**Comment by Jing-Loog** [comment]
还希望增加一个设置功能，在设置界面可以提前选择是生成还是查询：选中一段文本时，可以自动出现翻译的结果

**Comment by Jing-Loog** [comment]
其实我到目前为止，还没用到过单击屏幕（有稍微的延时）出现气泡的功能，只用过选中文本的。作者也可以考虑设置一下用户可以自行取消或保留单击出现气泡的功能，同时保留选中文本时，出现气泡。单击出现气泡影响太大了，有时拖动一个进度条也会出现。

**Comment by mushan0x0** [comment]
<img width="149" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/1a4f959b-6f50-46ca-b328-2f6323ddc139">
可以先临时关掉这个随航，下个版本会调整一下这个透明度，减少影响
