### ISSUE TITLE
开启AI 0x0 后，AI 0x0 Helper (Renderer)  cpu占用率一直在25% -50%

### ISSUE THREAD

**Issue by qazhyb** [mushan0x0/AI0x0.com#382]
mac os  13.2.1 (22D68)    macbook pro  13-inch, 2017

当前 AI 0x0  软件版本为1.5.26 

没有进行搜索或者其他操作，也没有打开AI 0x0的主页面，AI 0x0  Helper (Renderer)  cpu占用率一直在25% -50%
切换chat类型 例如从chatgpt 切换到chat0x0后，AI 0x0  Helper (Renderer)  cpu占用率恢复到1%
鼠标移动到浏览器或者其他应用程序，点击应用程序后，cpu占用率会上升到25% -50%

PID    COMMAND      %CPU TIME     #TH   #WQ  #PORT MEM    PURG   CMPRS  PGRP
87595  AI 0x0 Helpe 25.4 26:36.80 15    1    136   114M-  0B     66M    87584
139    WindowServer 15.7 36:23:39 18    8    8380+ 1796M- 8064K+ 546M   139
88603  TencentMeeti 15.5 03:30.87 68/1  4    1414  386M   3148K  188M   88603
0      kernel_task  14.4 41:17:10 233/4 0    0     604M-  0B     0B     0
75186  coreaudiod   12.0 69:56.53 12    4    1740  28M    0B     22M    75186
90592  top          10.9 00:04.41 1/1   0    30    8540K  0B     0B     9059

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.5.27

感谢反馈，你试一下这个版本呢

**Comment by AjianYo** [comment]
> 

我的也是这款机子，但13系统不卡？11最适合养老

**Comment by chenyusheng** [comment]
用了 1.5.27 版本，cpu占用率还是在 30% 左右

**Comment by mushan0x0** [comment]
> 用了 1.5.27 版本，cpu占用率还是在 30% 左右

不会吧

**Comment by mushan0x0** [comment]
可以试试1.5.41
