### ISSUE TITLE
建议增加一个设置项

### ISSUE THREAD

**Issue by UncleSunQvQ** [mushan0x0/AI0x0.com#383]
建议给鼠标随航增加一个按键设置，长按自定义键  并且  鼠标选中文本才触发随航功能，不知道可不可以。

**Comment by chenyajunai** [comment]
或者随航可以，把自动复制取消或者添加个开关，这样随航开关一直在，自动复制可以按需开启或关闭，这样不影响操作体验

**Comment by mushan0x0** [comment]
换成长按了，用自动复制始终会影响操作
