### ISSUE TITLE
当我开启两个软件并且分屏后，ai0x0的小球会自动隐藏

### ISSUE THREAD

**Issue by jyj12345** [mushan0x0/AI0x0.com#384]
# 问题
当我在使用浏览器和obsidian的时候，我将两个软件进行分屏操作时，我的光标放在obsidian中编辑时，ai0x0的小球会自动隐藏。
目前我测出只有obsidian和思源笔记进行分屏操作时会出现这种情况

# 版本号
+ 系统版本：Windows 11 家庭中文版23H2 25393.1
+ ai0x0软件版本：目前最新版本

https://github.com/mushan0x0/AI0x0.com/assets/68804563/0efd1fca-70d3-4353-b245-376b9173bacc

**Comment by mushan0x0** [comment]
感谢反馈已经修复，在 ai0x0.com 重新下一次就好了
