### ISSUE TITLE
希望增加一个手动更新的设置项

### ISSUE THREAD

**Issue by jyj12345** [mushan0x0/AI0x0.com#385]
希望能够在设置界面增加一个手动更新的选择项，而不是一有新版就会自动检查并且在全局跳出更新框。有很多时候在全屏看视频或者打游戏的时候会直接调回桌面。

**Comment by mushan0x0** [comment]
安排

**Comment by mushan0x0** [comment]
新版本已经判断了悬浮球隐藏状态不检查更新
