### ISSUE TITLE
当选择pdf文档中文本时，没有清洗干净

### ISSUE THREAD

**Issue by personalsrc-git** [mushan0x0/AI0x0.com#386]
当选择pdf文档中文本时，没有清洗干净，在用chatgpt web时，还残余“换行符”。

**Comment by mushan0x0** [comment]
这个不影响吧，选中什么文本就是什么文本，没有进行过清洗

**Comment by personalsrc-git** [comment]
如果做markdown笔记时，源文本有换行符是非常难看。即便是大语言模型，换行符对语义也有一定影响，我比较过，没有换行符语义比较通顺。

**Comment by mushan0x0** [comment]
这个不会进行清洗，你可以告诉gpt说忽略换行符，如果进行清洗了对写代码的场景有影响
