### ISSUE TITLE
chat0x0没有退出登录功能，续费了还是提示是非付费用户，要重新登录，但是没有重登入口

### ISSUE THREAD

**Issue by codecomeon** [mushan0x0/AI0x0.com#388]

**Comment by mushan0x0** [comment]
<img width="196" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/eb4422f3-c336-45aa-92da-0771465eb43b">

在这里可以退出登录，重新打开一下软件应该也可以
