### ISSUE TITLE
随航失效，并且ai0x0的小球不能拖动

### ISSUE THREAD

**Issue by jyj12345** [mushan0x0/AI0x0.com#391]
# 问题

当我打开ai0x0一段时间之后，再使用ai0x0的随航功能，鼠标的小手会变成选中的图标，而且ai0x0的小球也不能拖动。重启应用之后才会变好。

https://github.com/mushan0x0/AI0x0.com/assets/68804563/1645f7cf-97ba-4be9-8bb5-d0435ce1049e

# 版本

系统版本：win11 家庭中文版 25393.1

**Comment by mushan0x0** [comment]
刚才发了个版本，在 ai0x0.com 重新下载一次试试呢

**Comment by jyj12345** [comment]
不行，还是会这样

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/issues/393 可以加这个内测群反馈一下吗

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.5.39-alpha 试试这个版本呢
