### ISSUE TITLE
希望能添加cloude2

### ISSUE THREAD

**Issue by ryanzhaorx** [mushan0x0/AI0x0.com#395]
希望能添加cloude2
官网 : https://claude.ai/chats
注册URL : https://www.anthropic.com/index/claude-2

**Comment by ryanzhaorx** [comment]
需要使用外网

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.5.43-alpha 内测版已加上

**Comment by mushan0x0** [comment]
正式版已发布

**Comment by Tony-Wuchang** [comment]
你好
