### ISSUE TITLE
悬浮球无法全局隐藏，只能设置场景来隐藏

### ISSUE THREAD

**Issue by jiangjiji** [mushan0x0/AI0x0.com#398]
希望增加开关，控制悬浮球全局隐藏

**Comment by mushan0x0** [comment]
<img width="104" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/e7000ffa-8d1d-49a3-b10f-ab5d61e7baa6">
在托盘小图标右键就可以隐藏了，还可以在场景里设置打开什么应用时隐藏

**Comment by jiangjiji** [comment]
感谢收到，入口太隐蔽了。

如果在悬浮框的右键菜单中，出现勾选框 显示和隐藏会更符合预期。

**Comment by mushan0x0** [comment]
好的，我后面看看可以改进不
