### ISSUE TITLE
鼠标随行的触发

### ISSUE THREAD

**Issue by zhi244037992** [mushan0x0/AI0x0.com#401]
鼠标随航的触发的两次ctrl和wox 的触发冲突了。。每次使用鼠标随航就会把我的wox唤出来

**Comment by zhi244037992** [comment]
wox是默认两次ctrl 而且不能修改

**Comment by mushan0x0** [comment]
下个版本修复一下

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.5.54-alpha 试试这个内测版呢，下载 x64 后缀的文件

**Comment by zhi244037992** [comment]
直接点击放大镜图标插入输入框依然会唤醒wox，用出现的菜单栏点默认查询或者预设等则不会，同时这个版本点击查询之后需要点开窗口才能看到对话窗口，没有右上角的小浮框了

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.5.55-alpha 这个应该可以了吧

**Comment by mushan0x0** [comment]
没有右上角的小浮框这个重启软件看看呢，没有改动过这个地方

**Comment by zhi244037992** [comment]
好了 感恩大佬
