### ISSUE TITLE
无法打开软件

### ISSUE THREAD

**Issue by xulei-shl** [mushan0x0/AI0x0.com#402]
系统：Win11 22H2 家庭版

问题：

- 双击打开后，一直在转圈圈，无法正常显示。必须重启系统才能打开。
- 系统睡眠后，长时间不用也有可能突然就开始一直转圈圈，即使之前是可以正常使用

**Comment by mushan0x0** [comment]
转圈是悬浮球上赚钱吗，右边有个刷新按钮点一下就好了

**Comment by mushan0x0** [comment]
1.5.56已修复，1的话应该是偶发的，跟电脑网络有关

**Comment by xulei-shl** [comment]
版本1.5.56，系统自动休眠后，再次唤醒系统。软件还是转圈圈，无法正常打开，重启软件也不行。 

图1：桌面小图标的样式
<img width="281" alt="fd4c1036a62469058f8aa2871badfee" src="https://github.com/mushan0x0/AI0x0.com/assets/13896259/fdd44171-53a3-4d74-855d-59a4f46a004e">

图2：工具栏小图标，右键--设置，弹出的界面
![image](https://github.com/mushan0x0/AI0x0.com/assets/13896259/fceb492c-8a9c-4b74-b49b-3f75ead83647)

**Comment by mushan0x0** [comment]
![image](https://github.com/mushan0x0/AI0x0.com/assets/29084441/5b1beff7-9dbd-4555-85bb-e27d888a49d0)

加一下这个群吧我给你看看

**Comment by mushan0x0** [comment]
@2658026014 也是一直转圈吗
