### ISSUE TITLE
第三方的Bing不可用,建议换回原版的Bing

### ISSUE THREAD

**Issue by OpenX123** [mushan0x0/AI0x0.com#403]
![无标题](https://github.com/mushan0x0/AI0x0.com/assets/136779645/a8fcc160-1fc8-4290-a28d-e765c9363b7d)

**Comment by sfantacy** [comment]
赞同，换回原来的把。
![Uploading image.png…]()

**Comment by YCWHYDIE** [comment]
确实....好像是被墙了不维护了

**Comment by mushan0x0** [comment]
下个版本换个新的，官方的也用不了

**Comment by shdsj5784** [comment]
可以用魔法使用

**Comment by strongasahorse** [comment]
官方的魔法可以用 .这么多模型还是bing最好用.

**Comment by shdsj5784** [comment]
把必应换成这个https://copilot.microsoft.com/

**Comment by mushan0x0** [comment]
2.1.1已经支持
