### ISSUE TITLE
更新后悬浮组件体验差

### ISSUE THREAD

**Issue by JefferyGG** [mushan0x0/AI0x0.com#405]
我需要用时消失了，不清楚是什么规则。还有点击悬浮时会穿透。

**Comment by mushan0x0** [comment]
你是win吗，是不是使用全屏应用时消失了，可以在场景里添加为始终显示

**Comment by JefferyGG** [comment]
是win，还是觉得之前的好用，还有这个穿透问题，鼠标移到悬浮组件上不是手指，点击会穿透

**Comment by mushan0x0** [comment]
在 ai0x0.com 重新下载一下看看吧，穿透应该修复了，消失是全屏会自动隐藏，可能某些软件会误判，在悬浮球设置的场景里设置一下始终显示就行了
