### ISSUE TITLE
更新后主题选择窗口选不了去不掉

### ISSUE THREAD

**Issue by liwei90666** [mushan0x0/AI0x0.com#406]
<img width="591" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/5237649/f22c7ece-bb63-46ef-890e-4315e35227a5">

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.5.56 先用回老版本吧，下载exe后缀的

**Comment by mushan0x0** [comment]
应该修复了，在 ai0x0.com 下载新版看看呢
