### ISSUE TITLE
更新后主题选择卡主

### ISSUE THREAD

**Issue by FY1001** [mushan0x0/AI0x0.com#407]
![9f64b13202ee36a6e42761480fd055f9](https://github.com/mushan0x0/AI0x0.com/assets/59157941/98487c9a-813a-471a-9528-6029b3b3abe9)
三个选项无法选中，点击继续也点不了。
好像是透明的一样，只能点到窗口背后的内容。意思是这个界面不能选中

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.5.60-alpha 看看这个版本可以不，win系统下exe后缀的

**Comment by mushan0x0** [comment]
1.5.61 已修复
