### ISSUE TITLE
点击后退出

### ISSUE THREAD

**Issue by houchaowei** [mushan0x0/AI0x0.com#408]
下载版本：AI-0x0_1.5.58_arm64
系统：M1 macOS ventura13.0

**Comment by houchaowei** [comment]
![转gif - Made with Clipchamp](https://github.com/mushan0x0/AI0x0.com/assets/17643027/310113d9-0551-4580-8a23-4f7890ed80f7)

**Comment by houchaowei** [comment]
轻轻的它走了，什么也没有留下

**Comment by mushan0x0** [comment]
![image](https://github.com/mushan0x0/AI0x0.com/assets/29084441/8f2f8502-1d21-44c6-a705-a8433bfe6cea)
加这个群吧，我帮你看看
