### ISSUE TITLE
win11系统很卡直接卡死

### ISSUE THREAD

**Issue by DTtracy** [mushan0x0/AI0x0.com#411]

**Comment by mushan0x0** [comment]
在关于界面看看用的是什么版本的0x0呢

**Comment by HNYDDDTONY-ANU** [comment]
这个问题挺奇怪的，我的笔记本在仅使用外接屏幕的时候流畅度还好，但是直接使用笔记本屏幕的时候就会卡死。而且聊天气泡在多次使用之后感觉会堆积过多的信息造成过渡动画卡顿

**Comment by DTtracy** [comment]
> 

1.5.61的版本，直接在官网下的

**Comment by DTtracy** [comment]
> 在关于界面看看用的是什么版本的0x0呢

官网下的1.5.61

**Comment by DTtracy** [comment]
> 这个问题挺奇怪的，我的笔记本在仅使用外接屏幕的时候流畅度还好，但是直接使用笔记本屏幕的时候就会卡死。而且聊天气泡在多次使用之后感觉会堆积过多的信息造成过渡动画卡顿

我直接用的是笔记本电脑，直接卡死，刚开始还能登录，现在在登录界面就卡死了

**Comment by mushan0x0** [comment]
![image](https://github.com/mushan0x0/AI0x0.com/assets/29084441/256cf160-4784-482e-8cec-5f09f3074328)

加一下内测群我看一下日志吧

**Comment by mushan0x0** [comment]
1.5.68 已修复
