### ISSUE TITLE
建议恢复baichat

### ISSUE THREAD

**Issue by 203430** [mushan0x0/AI0x0.com#412]
我觉得baichat这个ai挺好用的，能不能考虑加回来？

**Comment by yuliang72123** [comment]
我也挺喜欢baichat，希望能加回来

**Comment by mushan0x0** [comment]
<img width="1155" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/ed3b06de-1250-45a0-b30d-6523fb4d37e6">

baichat马上要被关闭了 https://chatbot.theb.ai/#/chat/1002
