### ISSUE TITLE
对话气泡会反复读取PoeChat的最新一条的回复信息（仅限PoeChat）

### ISSUE THREAD

**Issue by HNYDDDTONY-ANU** [mushan0x0/AI0x0.com#413]
使用PoeChat模型的时候，在停止给模型发送提示词之后，聊天气泡会重复读取最后一个回复，通常会间隔一段时间读取一次，间隔时间未知。经测试，如果一晚上不使用电脑并将AI0x0保持运行状态，使用PoeChat，对话气泡重复读取了最后一条模型回复，总计10次。

版本：1.5.61

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.5.62-alpha 试试这个内测版呢，下 exe 后缀的文件

**Comment by mushan0x0** [comment]
1.5.68 已修复
