### ISSUE TITLE
这个软件在Windows11上已经彻底没有办法用了

### ISSUE THREAD

**Issue by nameddd** [mushan0x0/AI0x0.com#415]
现在卡在登录界面无响应。CPU占用率非常高，下载最新版本也没有解决。

**Comment by mushan0x0** [comment]
https://ghproxy.com/https://github.com/mushan0x0/AI0x0.com/releases/download/v1.5.56/AI-0x0_1.5.56_x64.exe 先下载这个版本看看吧，提示更新的时候点取消就行了

**Comment by mushan0x0** [comment]
https://ghproxy.com/https://github.com/mushan0x0/AI0x0.com/releases/download/v1.5.64-alpha/AI-0x0_1.5.64-alpha_x64.exe  试试看这个内测版本吧

**Comment by xiao2131** [comment]
说实话，解决流畅性吧，功能再好，卡顿过程中用了一两次就不想用了

**Comment by mushan0x0** [comment]
![image](https://github.com/mushan0x0/AI0x0.com/assets/29084441/ae2e1dd3-4b93-486e-bdb9-05cbb870e312)
我在解决流畅的，你们加这个群麻烦试试看内测版正常不

**Comment by mushan0x0** [comment]
https://ghproxy.com/https://github.com/mushan0x0/AI0x0.com/releases/download/v1.5.66-alpha/AI-0x0_1.5.66-alpha_x64.exe  可以再看看这个卡不卡

**Comment by mushan0x0** [comment]
1.5.68 已修复
