### ISSUE TITLE
对话气泡读取模型的回复信息失败（仅限ChatGPT）

### ISSUE THREAD

**Issue by HNYDDDTONY-ANU** [mushan0x0/AI0x0.com#416]
对话气泡读取ChatGPT模型的回复失败；
bug出现时间：2023/08/03 02:00，不早于2023/08/02 23:00（该时间前运行正常）
模型：ChatGPT；
操作：使用鼠标随行，选中的文本和提示词成功发送给ChatGPT，ChatGPT成功给出回复，对话气泡仅显示发送的消息，悬浮球一直为加载状态，对话气泡无法显示模型的回复信息
版本：1.5.65 / 1.5.64-alpha / 1.5.63-alpha / 1.5.62-alpha
![屏幕截图 2023-08-03 042504](https://github.com/mushan0x0/AI0x0.com/assets/140160683/09b81287-2cd8-4dfc-9762-b5b0871707cc)

**Comment by mushan0x0** [comment]
https://ghproxy.com/https://github.com/mushan0x0/AI0x0.com/releases/download/v1.5.66-alpha/AI-0x0_1.5.66-alpha_x64.exe 1.5.66的修复了
