### ISSUE TITLE
大神你好，有个技术问题想要咨询一下

### ISSUE THREAD

**Issue by coolRoger** [mushan0x0/AI0x0.com#419]
大佬好，@mushan0x0。

看了一下这个软件是基于electron开发的，有个技术问题想要请教一下大佬，请问如何在electron中监听用户在electron应用外的text selection，然后在selection的地方弹出一个frameless window？

我们可以通过微信交流吗？我的微信是: rliao1992

谢谢～～～

**Comment by mushan0x0** [comment]
问chatgpt吧，这个应用是chatgpt教我写的
