### ISSUE TITLE
功能建议：浮窗位置，自定义API，自定义文本界面等

### ISSUE THREAD

**Issue by peiyun1982** [mushan0x0/AI0x0.com#42]
AI0x0真是一个超好用的工具（虽然我还没能用上）
说几点需求，不知道是否可以加上。

1. 浮窗现在只能在主屏幕范围内拖动。比如我就有3个显示器，现在它还无法被拖动到其他显示器上。
2. 现在无论调用哪个GPT，好像都是直接链接到官网聊天页面。这就导致ChatGPT就算挂了梯子，也经常提示IP所在地不可用（当然，如果能访问的话这样最省钱）。那么是否可以做个中转页面，通过ChatGPT的API接口进行问答。这样就不会受梯子的限制了。（就好像OpenAI Translator这样的逻辑
![微信截图_20230322224643](https://user-images.githubusercontent.com/16250376/226941897-7ac36c9d-aaa2-4e1b-b814-2ed153c0c831.jpg)
3. 既然用自定义的API，自然就得有自己的对话框，最好兼容代码块，图片显示等。

当然，提需求的人是异想天开，能不能实现，就得看老板心情了。

**Comment by mushan0x0** [comment]
收到，一般来说创意比实现更重要

**Comment by mushan0x0** [comment]
123都已支持，1不知道win上表现怎么样
