### ISSUE TITLE
AI0x0内置浏览器bug（极端情况）

### ISSUE THREAD

**Issue by HNYDDDTONY-ANU** [mushan0x0/AI0x0.com#420]
1. 在使用AI0x0内置浏览器浏览模型聊天时，如果内置浏览器窗口未关闭，再次使用鼠标随行时会自动关闭（预期：浏览器保持打开状态）
2. 如果内置浏览器界面为打开状态，AI0x0会将当前使用的应用固定，如果不关闭浏览器并切换到其他应用，鼠标随行不会识别当前正在使用的应用，而且鼠标随行无法复制其他应用中选中的文字，它会自动读取剪贴板最新一条文本。

**Comment by mushan0x0** [comment]
![image](https://github.com/mushan0x0/AI0x0.com/assets/29084441/f1aaece0-2d95-4e16-8562-50befd4d4e10)

可以加内测群录屏看看吗，光看描述有点抽象
