### ISSUE TITLE
无法唤出ChatGPT Next Web 界面

### ISSUE THREAD

**Issue by cxyna6** [mushan0x0/AI0x0.com#421]
MacOS 13.5 使用快捷键 或者点击Chat0x0均无法唤出对话框界面，点击其他具体服务如ChatGPT能够出现对应服务界面

**Comment by mushan0x0** [comment]
![image](https://github.com/mushan0x0/AI0x0.com/assets/29084441/92f77be8-8710-4e65-bcba-890dc66ccfac)

可以加内测群我看看吗

**Comment by mushan0x0** [comment]
无法复现，也许是快捷键冲突了
