### ISSUE TITLE
输入openai的API之后依然提问不了

### ISSUE THREAD

**Issue by zqzzhou** [mushan0x0/AI0x0.com#424]
![问题图片](https://github.com/mushan0x0/AI0x0.com/assets/129175455/e061c17f-9c3c-432a-b27e-13731c41fc38)
![api图片-1](https://github.com/mushan0x0/AI0x0.com/assets/129175455/daa9f057-37f7-4b7e-9d90-3f6ac185a65a)
这是为什么呢

**Comment by mushan0x0** [comment]
你的key无效了

**Comment by zqzzhou** [comment]
> 你的key无效了

那怎么办，是充值还是创一个新的GPT账号

**Comment by mushan0x0** [comment]
充值0x0吧
