### ISSUE TITLE
版本1.6.9有非常严重的资源占用问题，会导致电脑卡死

### ISSUE THREAD

**Issue by fiyen** [mushan0x0/AI0x0.com#428]
如题，上个版本正常使用没有问题，但是从应用直接更新1.6.9后，电脑被卡到无限重新刷新，无法做任何操作，重启后开启应用不就就会出现同样的问题。直接下载1.6.9后无此问题，但是在代码编辑器如pycharm中会触发严重卡顿，导致电脑奇卡，无法使用。

**Comment by mushan0x0** [comment]
![image](https://github.com/mushan0x0/AI0x0.com/assets/29084441/00f21796-e7c4-4b90-b08b-44bc9d33db6f)

麻烦加一下内测群我看看了

**Comment by WayneOoO** [comment]
昨天下载使用，今天就遇到了，用Mac有史以来第一次死机。mac m1 16G运存版本

**Comment by mushan0x0** [comment]
> 昨天下载使用，今天就遇到了，用Mac有史以来第一次死机。mac m1 16G运存版本

mac似乎和win的情况不一样，这几天会修复一下

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.6.10-alpha @WayneOoO 这个内测版应该修复了

**Comment by WayneOoO** [comment]
我没有更新1.6.10版本，但我等来了1.6.11正式版。

由于更新后，使用频率过低，目前资源卡死的问题还没有复现。
但，就修复内容第一条结果验证： 是失败的

在Win11上，快捷键查询仍然无法选中内容，只能是剪贴板的内容

请看演示图：
***@***.***

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年8月26日 23:33
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [mushan0x0/AI0x0.com] 版本1.6.9有非常严重的资源占用问题，会导致电脑卡死 (Issue #428)


https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.6.10-alpha @WayneOoO<https://github.com/WayneOoO> 这个内测版应该修复了

―

**Comment by mushan0x0** [comment]
已修复

**Comment by WayneOoO** [comment]
如题，经过我的体验，豆包 在速度上和体验上，比国内其他 AI 模型都要好很多，背靠抖音百科，在资料的准确度上，也强于其他模型，如能在下个版本添加该模型，会是一个不错的选择
