### ISSUE TITLE
AI0x0，macbook pro电脑将对话框打开最大化，再关闭对话框，就再也无法打开对话框了，后台杀进程、重新安装都不行

### ISSUE THREAD

**Issue by lmf-2021** [mushan0x0/AI0x0.com#430]
AI0x0，macbook pro电脑将对话框打开最大化，再关闭对话框，就再也无法打开对话框了，后台杀进程、重新安装都不行

**Comment by mushan0x0** [comment]
没有复现。。但是你可以进入悬浮球设置里，在设置页点几次重置按钮就可以重置了

**Comment by lmf-2021** [comment]
感谢，在很多次重置之后，成功打开了
