### ISSUE TITLE
我看到最新更新内容有：修复：  Win 端选择查询文本按查询快捷键不生效

### ISSUE THREAD

**Issue by WayneOoO** [mushan0x0/AI0x0.com#431]
但是根据我实际使用情况来看，这个最新版本并没有修复上述问题。Mac卡顿问题暂时没有复现，可能跟更新后基本没使用也有关。但Win的快捷键查询，很明显 是不生效的，仍然只会粘贴剪贴板的内容到搜索框

**Comment by mushan0x0** [comment]
试试这个版本呢：https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.6.13-alpha

**Comment by mushan0x0** [comment]
最新版还有问题吗

**Comment by WayneOoO** [comment]
仍然只能获取剪贴板内容，无法获取选中目标。即使是Edge浏览器网页内容。 

我已经陷入了自我怀疑，是不是需要卸载清理重装？覆盖安装的问题？

**Comment by WayneOoO** [comment]
【Mac版本】

你好，目前软件可能处于初始阶段，很多功能持续上线，更新频率很高。但是，迭代太快带来的问题是，更新推送过于频繁，一天内推更三次，对用户不太友好。建议是，将推送更新关闭，或者增加一个选项，一周内不推送更新。给用户自主更新的权利，让推送通知不至于影响用户使用观感

**Comment by mushan0x0** [comment]
你装的是内测版吧，在 ai0x0.com 下载正式版就行了

**Comment by WayneOoO** [comment]
啊。 尴尬了😅。 OK

**Comment by mushan0x0** [comment]
win这个bug在 ai0x0.com 重新下载1.6.21版本应该就可以了
