### ISSUE TITLE
悬浮按钮消失

### ISSUE THREAD

**Issue by phfyb1** [mushan0x0/AI0x0.com#432]
刚启动程序时的悬浮按钮，在过一段时间不操作后，悬浮按钮消失，且无法直接唤出，只能关闭进程后重新启动才能唤出悬浮钮，导致无法切换使用的AI模型

**Comment by phfyb1** [comment]
用了两个屏幕，关闭打开毛玻璃效果时可以看见悬浮按钮，但是往第二屏幕的方向快速隐藏掉了，找不到在哪里

**Comment by phfyb1** [comment]
用了两个屏幕，关闭打开毛玻璃效果时可以看见悬浮按钮，但是往第二屏幕的方向快速隐藏掉了，找不到在哪里

**Comment by mushan0x0** [comment]
好的我看看这个问题

**Comment by mushan0x0** [comment]
试试这个版本呢：https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.6.13-alpha

**Comment by mushan0x0** [comment]
应该修复了
