### ISSUE TITLE
only part of the response will be displayed

### ISSUE THREAD

**Issue by liyun95** [mushan0x0/AI0x0.com#434]
As shown in the following figure, the response has not been fully displayed
<img width="609" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/105278390/f59722cd-2778-435a-80a6-273b11a6dfec">

**Comment by mushan0x0** [comment]
Hello, please try downloading version 1.6.21 of this bug from ai0x0.com. It may have better support for third-party chat. Alternatively, you can use chat0x0 for the best experience.
