### ISSUE TITLE
关闭应用后 会回到第一个默认的chat0x0，期望选中对应的模型后，会保持之前选中的模型

### ISSUE THREAD

**Issue by hunghoo** [mushan0x0/AI0x0.com#435]
期望：关闭后重新打开，仍会保持之前选中的模型

**Comment by hunghoo** [comment]
最好选择的其他配置也可以进行保留，比如 固定屏幕，悬浮球外观等配置项

**Comment by mushan0x0** [comment]
第一个是故意这样设计的，最推荐的是使用chat0x0，别的在这个内测版修复了 https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.6.21-alpha
