### ISSUE TITLE
必应不可以使用

### ISSUE THREAD

**Issue by wuwenrui** [mushan0x0/AI0x0.com#438]
<img width="145" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/20716568/ab298426-e820-483d-a17e-86d7d30533b8">
必应显示灰色，不可使用

**Comment by mushan0x0** [comment]
是的暂时还不能用

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/issues/403 重复
