### ISSUE TITLE
更新1.6.26后，打开随航时任意操作按住鼠标并拖动会自动输入ctrl+c

### ISSUE THREAD

**Issue by Vinzelles** [mushan0x0/AI0x0.com#439]
今天开机提示更新，没多想就更新了，结果发现编辑器一拖动terminal的高度，服务就会自动终止，其他应用也是一拖动就自动最小化，折磨了一整天不知道是啥问题，最后发现是更新后鼠标随航导致拖动鼠标会自动键入ctrl+c，关掉就不会了
![image](https://github.com/mushan0x0/AI0x0.com/assets/67829622/1b91aa13-188f-4233-923f-ab611746b2e2)
![image](https://github.com/mushan0x0/AI0x0.com/assets/67829622/0874c9c7-945b-4d0f-9e1f-b157d9f3ed8c)

**Comment by mushan0x0** [comment]
可以重启看看电脑还会这样吗

**Comment by mushan0x0** [comment]
vscode 这个修复了，拖动自动copy这个是正常的，只要不影响使用就行

**Comment by Vinzelles** [comment]
> vscode 这个修复了，拖动自动copy这个是正常的，只要不影响使用就行

vscode是修复了，但是webstorm还是会，我主要用webstorm的，vscode只是一起做个演示，除此之外包括MPC-HC、系统Terminal、CMD仍然因为这个导致拖动窗口大小出现问题

**Comment by mushan0x0** [comment]
好的，下个版本都处理一下

**Comment by mushan0x0** [comment]
新版已修复
