### ISSUE TITLE
现在APP不可以用API key了吗？可以怎么设置，以及可以使用那个模型

### ISSUE THREAD

**Issue by jerkran81** [mushan0x0/AI0x0.com#441]
现在APP不可以用API key了吗？可以怎么设置，以及可以使用那个模型

**Comment by mushan0x0** [comment]
在Chat0x0左下角设置里设置key就行了

**Comment by jerkran81** [comment]
是这样设置的，但是回复你自定义key余额不足或者失效，我才申请的新key，是不是现在key不能免费用啦，要给openai充钱发自我的 iPhone在 2023年9月12日，22:47，mushan0x0 ***@***.***> 写道：﻿
Closed #441 as completed.

**Comment by jerkran81** [comment]
谢谢，那要自己充钱了哦，买你们的划算不

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月13日 00:54 |
| 收件人 | ***@***.***> |
| 抄送人 | jerkran81 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [mushan0x0/AI0x0.com] 现在APP不可以用API key了吗？可以怎么设置，以及可以使用那个模型 (Issue #441) |

说明你的key余额过期了

**Comment by mushan0x0** [comment]
买年费很划算的，不限次数使用
