### ISSUE TITLE
希望开发者考虑一下增加买断的付费方式，我只需要软件预设提示词的功能，不需要无限制使用的AI

### ISSUE THREAD

**Issue by jingminglang** [mushan0x0/AI0x0.com#444]
希望开发者考虑一下增加买断的付费方式，我只需要软件预设提示词的功能，不需要无限制使用的AI

**Comment by mushan0x0** [comment]
我下个版本把内测版的限制打开吧，不需要付费

**Comment by mushan0x0** [comment]
参考这个 https://github.com/mushan0x0/AI0x0.com/issues/393
