### ISSUE TITLE
切换到，桌面数字人形象旁边的小窗口不自动收起也无法手动处理

### ISSUE THREAD

**Issue by sfantacy** [mushan0x0/AI0x0.com#445]
![image](https://github.com/mushan0x0/AI0x0.com/assets/36142262/3099b872-5526-43ac-b159-a8db897fa5d4)

每次切换到perplexity这个会有问题，查询后就会出现如上问题
但是其他的模型好像没有类似的。

**Comment by mushan0x0** [comment]
perplexity更新导致的，下个版本我修复一下

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.6.33 已修复
