### ISSUE TITLE
使用天工搜索模型时默认查询结尾为英文时的回车不会映射到查询框中

### ISSUE THREAD

**Issue by shicxin** [mushan0x0/AI0x0.com#446]
![image](https://github.com/mushan0x0/AI0x0.com/assets/83284782/51884ea1-7de6-45f8-9129-f63a68c12133)
今天测试了一下天工搜索，发现使用快捷键调出默认查询后输出框无反应，调出对话窗口后发现已被输入但是没有执行回车，
![image](https://github.com/mushan0x0/AI0x0.com/assets/83284782/75a33549-1c19-431b-8ef2-1a4ae8425c71)
紧接着测试后发现只有结尾为英文有这个问题，中文正常

**Comment by mushan0x0** [comment]
谢谢反馈，我看看这个问题

**Comment by shicxin** [comment]
> 谢谢反馈，我看看这个问题

感觉是在结尾为英文时的回车变成了换行

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v1.6.33 已修复
