### ISSUE TITLE
主窗口关闭后，没主动调用前，总是自行弹出

### ISSUE THREAD

**Issue by sfantacy** [mushan0x0/AI0x0.com#456]
先是桌面虚拟人那边弹出提示：正在加载中，然后主窗口就出来了，
关闭了仍然自行刷新、弹出

没什么特别设置，选择了固定屏幕

**Comment by mushan0x0** [comment]
有的抽象，可以录屏看看吗

**Comment by sfantacy** [comment]
> 有的抽象，可以录屏看看吗

我再反复测试下场景，关闭很久后。现在感觉没出现。
之前是开机自动启动后，一直出现。我退出后，下午在登陆感觉没在出现。后面观察出现我再录屏

**Comment by sfantacy** [comment]
测试下了，问题场景是这样：
关闭主窗口，点击更换下一个桌面背景或者自动更换背景后，，就会自动刷新出来主窗口，虚拟人也是会感觉刷新了下。

**Comment by mushan0x0** [comment]
你是否使用了什么第三方的桌面插件呢

**Comment by sfantacy** [comment]
确实用了，star11。
主题是win10默认下载的

**Comment by sfantacy** [comment]
> 你是否使用了什么第三方的桌面插件呢

搞不清楚为啥star11，更换背景会刷新了桌面的虚拟人，进而初始化了窗口

**Comment by sfantacy** [comment]
测试了下，是这个配置导致的。感觉不是第三方软件问题，是任务栏背景色刷新问题
![image](https://github.com/mushan0x0/AI0x0.com/assets/36142262/badf31dc-428f-4814-a140-7ba96d63bf49)

**Comment by mushan0x0** [comment]
好的，我看看可以解决不

**Comment by sfantacy** [comment]
ok。开启主题色自动选取和任务栏显示主题色
![image](https://github.com/mushan0x0/AI0x0.com/assets/36142262/8278ba7b-3cab-4d25-8542-54b6077eef55)

**Comment by mushan0x0** [comment]
已修复
