### ISSUE TITLE
使用poe的时候，会一直卡在运行中，无法选择提示词

### ISSUE THREAD

**Issue by 852569069** [mushan0x0/AI0x0.com#457]
![iShot_2023-10-11_16 49 01](https://github.com/mushan0x0/AI0x0.com/assets/30398478/37142612-fda0-44a3-ae3a-5519479c8068)
使用chatgpt就不会

**Comment by 852569069** [comment]
前一个任务是已经回答完了的

**Comment by mushan0x0** [comment]
可能是poe更新导致的，下个版本修复

**Comment by mushan0x0** [comment]
已修复
