### ISSUE TITLE
perplexity模型无法登录，邮件登录他会跳转到浏览器。还有鼠标随航选中文字没有放大镜出现

### ISSUE THREAD

**Issue by DJ133104** [mushan0x0/AI0x0.com#463]

**Comment by mushan0x0** [comment]
perplexity不支持邮箱登录，只能用google这些，因为链接跳不到0x0里

**Comment by mushan0x0** [comment]
鼠标随航选中文字没有放大镜，你是什么版本号的AI0x0呢，是不是用了双屏的

**Comment by DJ133104** [comment]
16.46内测版，双屏是什么

**Comment by mushan0x0** [comment]
就是外接显示器，没有放大镜这个问题是不是悬浮球设置里的鼠标随航优化是打开的，把这个关了看看呢

**Comment by DJ133104** [comment]
不是，我的笔记本电脑，优化我关了也没有放大镜出现在word中

**Comment by DJ133104** [comment]
别的应用也不行qq里试了一下，悬浮球的是打开的
