### ISSUE TITLE
太大了

### ISSUE THREAD

**Issue by changzhongxinxin** [mushan0x0/AI0x0.com#466]
感觉好臃肿啊，模糊关闭每次重启都会默认打开，建议和chatgpt next web一样使用windows的webview，一下轻量90%

**Comment by mushan0x0** [comment]
webview坑很多的

**Comment by mushan0x0** [comment]
模糊这个应该是bug，后面修复一下

**Comment by changzhongxinxin** [comment]
好的辛苦了，垃圾办公本只能关闭模糊换取性能了
![00883C38](https://github.com/mushan0x0/AI0x0.com/assets/68383493/75073ba8-1f1c-4c25-bf09-50813f4b948c)

**Comment by mushan0x0** [comment]
模糊关闭每次重启都会默认打开这个没有复现，更新到最新版看看吧
