### ISSUE TITLE
触发随航悬浮球时，一些其他应用的复制操作会失败。

### ISSUE THREAD

**Issue by Arbor-Hun** [mushan0x0/AI0x0.com#469]
长按鼠标中键也会触发随航，导致与utools等软件冲突，因为utools长按中键会复制选择的内容，而触发随航导致复制失败。

关键是，AI0X0没必要让中键也触发随航吧？希望作者能把中键触发方式屏蔽掉。

**Comment by Arbor-Huan** [comment]
试了下，应该是随航悬浮球存在的期间内，utools的复制操作都会失败。不知道能否更改一下随航悬浮球的消失逻辑？：当有其他鼠标操作时（包括左右键、中键），随航悬浮球立即消失。

不确定这样可不可以解决，但是至少用起来会舒服一点，因为现在的随航常常消失太慢，点击空白处也不能让它立刻消失，很影响观感和操作。

**Comment by mushan0x0** [comment]
家里没有鼠标，暂时复现不了。。。正常来说只有长按左键才会显示的，而且点击空白处会隐藏

**Comment by Arbor-Huan** [comment]
> 家里没有鼠标，暂时复现不了。。。正常来说只有长按左键才会显示的，而且点击空白处会隐藏

我的版本是最新的alpha，Windows10，我重装了几次都还是一样，点击空白处不会隐藏，只能等待它自动消失……

**Comment by Arbor-Huan** [comment]
话说chat0X0好像该更新了，这个版本没有GPT4 turbo 1106

**Comment by mushan0x0** [comment]
> 话说chat0X0好像该更新了，这个版本没有GPT4 turbo 1106

可以在设置里手动加一个，这个模型还没发正式版的容易报错

**Comment by mushan0x0** [comment]
> > 家里没有鼠标，暂时复现不了。。。正常来说只有长按左键才会显示的，而且点击空白处会隐藏
> 
> 我的版本是最新的alpha，Windows10，我重装了几次都还是一样，点击空白处不会隐藏，只能等待它自动消失……

我后面修复一下

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v3.3.6-alpha 已支持点击空白隐藏放大镜
