### ISSUE TITLE
新版需要注册，但是把qq邮箱输入后 获取验证码，试了很多次都没有收到验证码

### ISSUE THREAD

**Issue by djh12345678** [mushan0x0/AI0x0.com#47]
新版需要注册，但是把qq邮箱输入后 获取验证码，试了很多次都没有收到验证码

**Comment by 203430** [comment]
是的，我也是这样

**Comment by mushan0x0** [comment]
再试试呢，注册人太多了

**Comment by 203430** [comment]
我建议可以搞成手机号，这样应该方便一点

**Comment by 203430** [comment]
楼主成功没，我还没搞好ੈ♡‧₊˚_( :⁍ 」 )_已晕……

**Comment by djh12345678** [comment]
没弄，明天再说吧，手里还有工作，本来就是个辅助的东西，不行我就挂梯子直接访问了，本身我也有GPT的账号跟GPT4的资格

**Comment by 203430** [comment]
蹲，搞好了踢一下，感谢道友

**Comment by mushan0x0** [comment]
验证码可以了

**Comment by 203430** [comment]
好的，开发者勤奋啊，加油(ง ˙o˙)ว

**Comment by 203430** [comment]
刚刚试了一下，为啥还是不行，要开梯子注册吗？

**Comment by 203430** [comment]
好了，刚刚有延迟，抱歉

**Comment by 203430** [comment]
楼主，去试试，可以了踢一下，我刚刚输了之后他说网络错误啥啥啥的

**Comment by 123Eleven** [comment]
还是收不到噢，我试了QQ邮箱和163邮箱

**Comment by lovecomic** [comment]
同样QQ邮箱收不到验证码 无法正常注册

**Comment by 1061127386** [comment]
QQ邮箱收不到验证码

**Comment by zhaolie1989** [comment]
我也没收到,修复了吗

**Comment by 203430** [comment]
要不然试试网易？刚刚有个道友说网易的可以诶，可以的话踢一下，现在亲身试验不了

**Comment by zhaolie1989** [comment]
网易试了也不行啊

**Comment by 203430** [comment]
那就不知道了，等开发者修复修复吧

**Comment by mushan0x0** [comment]
注册人太多了，验证码接口坏了，只能等阿里云把短信接口通过，用短信注册了

**Comment by 203430** [comment]
那就辛苦开发者了，我们耐心等待

**Comment by 203430** [comment]
大概要多久能通过？

**Comment by 203430** [comment]
兄弟们快试水😚

**Comment by jjqqwz** [comment]
QQ邮箱接收不了验证码，怎么解决

**Comment by mushan0x0** [comment]
> QQ邮箱接收不了验证码，怎么解决

我才试了没问题，看看是不是邮箱输入错了呢
