### ISSUE TITLE
有代码的情况下，滑动会抽搐

### ISSUE THREAD

**Issue by li1243893836** [mushan0x0/AI0x0.com#471]
系统 macos
描述 像图上这种情况，往上或往下滚动的时候，在经过代码时会抽搐。我感觉是代码框上的滑动条跟全局的滑动条没有处理好
![image](https://github.com/mushan0x0/AI0x0.com/assets/56986669/10dfb62e-97d0-4f37-ac87-bcee0b5393db)

**Comment by mushan0x0** [comment]
是用的鼠标还是触控板啊

**Comment by li1243893836** [comment]
> 是用的鼠标还是触控板啊

用的鼠标
