### ISSUE TITLE
在有输入框的情况下无法出现历史记录

### ISSUE THREAD

**Issue by li1243893836** [mushan0x0/AI0x0.com#472]
系统 macos
描述 看视频

https://github.com/mushan0x0/AI0x0.com/assets/56986669/d4fc7bc1-3861-41a2-ba42-f8afa8127da1

**Comment by mushan0x0** [comment]
目前是这样设计的，后面可以考虑优化下

**Comment by mushan0x0** [comment]
暂不考虑显示输入框的同时显示对话气泡
