### ISSUE TITLE
代理地址填写内网地址，请求不通

### ISSUE THREAD

**Issue by Jesn** [mushan0x0/AI0x0.com#474]
代理地址是本机部署的OneApi ，填写内网地址请求不通，ChatGPT Next调用可以正常，确定接口是没问题的

<img width="940" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/5728274/f2758dbd-039a-4581-ae22-d77e6ff334f5">

**Comment by mushan0x0** [comment]
<img width="284" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/c06c386b-2c01-4ba1-96a1-210462e77777">
后面要加一个/v1

**Comment by Jesn** [comment]
> <img alt="image" width="284" src="https://user-images.githubusercontent.com/29084441/285416791-c06c386b-2c01-4ba1-96a1-210462e77777.png"> 后面要加一个v1

试过，还是一样
<img width="896" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/5728274/8d8bf8ac-3316-44b4-b3b5-5638c4fc41c6">

**Comment by Jesn** [comment]
知道了 模型切换下就行了
<img width="306" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/5728274/e5bf7fe0-9d41-4a90-ba89-5e2cf5916d73">

**Comment by mushan0x0** [comment]
哦第一个可能确实不能访问内网的，因为要经过服务器
