### ISSUE TITLE
鼠标随航失效，对话框最小化后经常被自动关闭

### ISSUE THREAD

**Issue by Emmawoods598** [mushan0x0/AI0x0.com#475]
如题所述，更新到最新版本仍然存在这两个问题

**Comment by mushan0x0** [comment]
mac吗，确实还会被关闭，下个版本会再修一下

**Comment by Emmawoods598** [comment]
> mac吗，确实还会被关闭，下个版本会再修一下

win11，随航失效也经常发生

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v2.1.0-alpha 试试这个版本呢

**Comment by mushan0x0** [comment]
被自动关闭已修复，随航失效没有复现。。。
