### ISSUE TITLE
Mac 远程WIndows系统，导致鼠标左键选中出现问题

### ISSUE THREAD

**Issue by Jesn** [mushan0x0/AI0x0.com#476]
在Mac上使用 `Microsoft Remote Desktop` 远程连接WIndows系统，  鼠标左键选中一段文本，松开鼠标后该段被选中的文本会被替换成字母`c`。

该问题可重复复现

**Comment by Jesn** [comment]
> 在悬浮球设置里看看是否开启了鼠标随航优化，关掉看看呢

确实是那个功能影响的，关掉就行了,  但是我mac和WIndows之间复制好像有问题

**Comment by mushan0x0** [comment]
复制不了吗

**Comment by mushan0x0** [comment]
远程连接软件已经自动排除

**Comment by Jesn** [comment]
刚把版本升级了，好像是没问题了
