### ISSUE TITLE
Copilot点击登录没反应

### ISSUE THREAD

**Issue by FAIING** [mushan0x0/AI0x0.com#477]
![image](https://github.com/mushan0x0/AI0x0.com/assets/22023619/394831ab-1dd3-4695-ad2b-ba4a02741be7)
点击登录没有任何反应（第一次使用是正常进入，后面直接跳出登录，然后就点击没反应）

**Comment by mushan0x0** [comment]
多点几次登录也这样吗

**Comment by shdsj5784** [comment]
需要开魔法

**Comment by mushan0x0** [comment]
开加速或者魔法，还是不行就是被微软限制了
