### ISSUE TITLE
悬浮窗一直转圈圈

### ISSUE THREAD

**Issue by wei-seven** [mushan0x0/AI0x0.com#480]
回答完问题后，悬浮窗会一直转圈圈，影响体验。
![image](https://github.com/mushan0x0/AI0x0.com/assets/63662290/7fc93b43-7423-4e82-b7ee-5c16890edcae)

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v2.2.5 这个版本已修复
