### ISSUE TITLE
模拟按键Ctrl+C的导致的各种冲突

### ISSUE THREAD

**Issue by Arbor-Huan** [mushan0x0/AI0x0.com#481]
因为悬浮球的触发方式是长按鼠标，在拖动、截图、滑动等操作中极易触发Ctrl+C，导致误操作。比如：截图被中断、Shell终端被中断、浏览器在滚动中键时容易缩放页面大小（大概是触发了Ctrl+中键，在页面选中文本之后立即滚动中键可以百分百触发）。经测试，似乎涉及两次有关Ctrl的模拟按键：①长按完刚浮现悬浮球时有一次Ctrl相关操作；②鼠标移动到悬浮球时触发Ctrl+C。

我想到的解决办法：
1. 优化“长按--悬浮球浮现（第一次Ctrl）--复制文本（第二次Ctrl）”的逻辑。
2. 直接不用Ctrl+C的模拟按键，用其他替代。我也是代码小白，刚问GPT4的：
---
【GPT的回答】

如果您不想通过模拟按键来实现复制功能，您可以直接操作系统的剪贴板来实现复制粘贴的功能。以下是一些在不同编程语言中直接操作剪贴板的方法：

1. **Windows API（C++）**：
   使用 Windows API 直接与剪贴板交互。

   ```cpp
   #include <windows.h>

   // 打开剪贴板
   OpenClipboard(nullptr);
   // 清空剪贴板
   EmptyClipboard();

   // 将文本放入剪贴板
   HGLOBAL hGlobal = GlobalAlloc(GMEM_MOVEABLE, (text.size() + 1) * sizeof(wchar_t));
   if (hGlobal) {
       memcpy(GlobalLock(hGlobal), text.c_str(), (text.size() + 1) * sizeof(wchar_t));
       GlobalUnlock(hGlobal);
       SetClipboardData(CF_UNICODETEXT, hGlobal);
   }

   // 关闭剪贴板
   CloseClipboard();
   ```

2. **.NET（C#）**：
   使用 `Clipboard` 类来操作剪贴板。

   ```csharp
   using System.Windows.Forms;

   // 将文本复制到剪贴板
   Clipboard.SetText("要复制的文本");
   ```

3. **Python**：
   使用 `pyperclip` 或 `clipboard` 库来操作剪贴板。

   ```python
   import pyperclip

   # 将文本复制到剪贴板
   pyperclip.copy('要复制的文本')
   ```

4. **Java**：
   使用 `Toolkit` 和 `Clipboard` 类来操作剪贴板。

   ```java
   import java.awt.Toolkit;
   import java.awt.datatransfer.Clipboard;
   import java.awt.datatransfer.StringSelection;

   // 获取系统剪贴板
   Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
   // 封装文本内容
   StringSelection selection = new StringSelection("要复制的文本");
   // 将文本内容设置到剪贴板
   clipboard.setContents(selection, null);
   ```

使用这些方法，您可以直接将文本数据放入剪贴板，而无需模拟按键操作。这些方法通常更为直接和可靠，因为它们不依赖于键盘事件的生成和处理。在实现时，请确保您的应用程序有权限操作剪贴板，并且在多线程环境中正确地同步剪贴板的访问。

**Comment by mushan0x0** [comment]
在悬浮球设置里打开鼠标随航优化看看呢

**Comment by mushan0x0** [comment]
这些代码是假的，现在没有系统api能够直接获取选中文本，很影响的话可以先把鼠标随航关了

**Comment by Arbor-Huan** [comment]
> 在悬浮球设置里打开鼠标随航优化看看呢

哈哈哈，这就尴尬了，我之前因为中键触发悬浮的BUG一直都勾选这随航优化，没想到上文所说的第一次Ctrl都是因为勾选了这个……我取消勾选反而不会触发第一次Ctrl了，截图和浏览器的问题目前算解决了。

**Comment by mushan0x0** [comment]
好吧😂

**Comment by Arbor-Huan** [comment]
> 好吧😂

多谢作者，早些休息。👍
