### ISSUE TITLE
会影响微信聊天内容的选择（Mac OS）

### ISSUE THREAD

**Issue by tychoon** [mushan0x0/AI0x0.com#484]
https://github.com/mushan0x0/AI0x0.com/assets/5457353/37fee55f-d8b6-4cf9-a10b-eeced9223305

选择微信聊天内容收到影响，无法选择转发微信聊天内容。Mac Sonoma 14.1.2 (23B92)

**Comment by mushan0x0** [comment]
<img width="525" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/35667ee1-697a-4873-89ad-af1cf4d8d0d1">

在设置里把这个关了就行了

**Comment by mushan0x0** [comment]
下个版本这个功能将自动排除微信
