### ISSUE TITLE
AI0x0 模型是否可以支持 gpt-3.5-turbo-1106， gpt-3.5-turbo-16k

### ISSUE THREAD

**Issue by xulei-shl** [mushan0x0/AI0x0.com#488]
如下图，LobeHub官网是可以选gpt-3.5-turbo-1106， gpt-3.5-turbo-16k的。不知AI0x0是否支持

![image](https://github.com/mushan0x0/AI0x0.com/assets/13896259/a2ccc150-1743-49cd-98e4-994ff36e1928)

**Comment by mushan0x0** [comment]
<img width="1257" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/f53d1c6d-4b20-4880-9df6-4771d355d0a0">
在这里添加你需要的模型就可以了
