### ISSUE TITLE
在macOS 14.2使用会导致Rectangle拖拽窗口功能失效，请问有解决办法吗？

### ISSUE THREAD

**Issue by yffat** [mushan0x0/AI0x0.com#489]
您好：

在MacBook M1 macOS 14.2使用会导致Rectangle拖拽窗口（Snap Areas）功能失效，请问可以关闭悬浮球功能吗？或是有其它解决办法吗？谢谢。

**Comment by mushan0x0** [comment]
<img width="138" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/2e70844a-c7ac-460b-a1e7-8005918dbb4b">
点击这个就可以隐藏悬浮球了，你试试把鼠标随航关了看看呢

**Comment by yffat** [comment]
您好：

尝试了分别隐藏悬浮球和关闭鼠标随航，Rectangle的拖拽窗口（Snap Areas）还是失效，需要关闭AI 0x0才能正常使用。暂时改用Rectangle的快捷键来取代拖拽窗口。

**Comment by mushan0x0** [comment]
> 您好：
> 
> 尝试了分别隐藏悬浮球和关闭鼠标随航，Rectangle的拖拽窗口（Snap Areas）还是失效，需要关闭AI 0x0才能正常使用。暂时改用Rectangle的快捷键来取代拖拽窗口。

好吧，那应该需要Rectangle来修复了，一般悬浮球隐藏了就不会做什么系统事件的处理了
