### ISSUE TITLE
无法使用ai0x0

### ISSUE THREAD

**Issue by ziweiyuerai** [mushan0x0/AI0x0.com#491]
![image](https://github.com/mushan0x0/AI0x0.com/assets/105401668/bb8fc93e-1fb9-4f0c-b371-b58074612f12)
报错
证书失效？我的api秘钥还在有效期之中

**Comment by yuhaosimba** [comment]
我在使用私人api-key的时候也出现相同报错，应当不是api-key的问题

**Comment by mushan0x0** [comment]
再试试呢，应该可以了

**Comment by yuhaosimba** [comment]
我修改了接口地址为https://api.openai.com解决了这个问题，之前报错是在应用默认的接口地址下发生的。我会在默认接口地址下再试一试，感谢回复！

------ 原始信息 ------
来自 "mushan0x0" ***@***.***>
收件人 "mushan0x0/AI0x0.com" ***@***.***>
抄送 "nezumi" ***@***.***>; "Comment" 
***@***.***>
日期 2023/12/24 17:27:02
主题 Re: [mushan0x0/AI0x0.com] 无法使用ai0x0 (Issue #491)
