### ISSUE TITLE
在Mac使用鼠标随航时无法与PopClip和Easydict并存使用，但是只使用PopClip与Easydict时两者可以并存使用。

### ISSUE THREAD

**Issue by yffat** [mushan0x0/AI0x0.com#492]
在Mac使用鼠标随航时无法与PopClip和Easydict并存使用，但是只使用PopClip与Easydict时两者可以并存使用。

1、关闭鼠标随航时，PopClip和Easydict的图标可以并存及选择需要的功能使用。

https://github.com/mushan0x0/AI0x0.com/assets/3946395/f8ecb7ae-e0c5-46ab-ab34-f2272fc2b493

2、打开鼠标随航时，PopClip和Easydict的图标会立即被鼠标随航的图标取代。希望可以和PopClip、Easydict与鼠标随航的图标同时并存，再根据需求选择功能使用。

https://github.com/mushan0x0/AI0x0.com/assets/3946395/98056c8e-371a-426f-89d5-bc68eae4bbeb

**Comment by mushan0x0** [comment]
在悬浮球设置里把鼠标随航优化关了试试呢
<img width="476" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/2e9b71f2-d17a-49bb-aaec-ee9a71113ac4">

**Comment by mushan0x0** [comment]
关了随航优化应该就可以了
