### ISSUE TITLE
出现这个问题 A JavaScript error occurred in the main process.

### ISSUE THREAD

**Issue by iogeda** [mushan0x0/AI0x0.com#495]
![PixPin_2024-01-05_10-25-39](https://github.com/mushan0x0/AI0x0.com/assets/42607836/70961239-98d0-4348-b8db-7349c5a487f7)

**Comment by mushan0x0** [comment]
是怎么出现的呢

**Comment by iogeda** [comment]
> 是怎么出现的呢

在任务栏图标点击右键  ，选择 显示/隐藏  功能 ，就这样。

**Comment by iogeda** [comment]
> 是怎么出现的呢

软件重装了很多次，打开软件还会出现这个。然后无法使用，而且没有悬浮按钮。不能使用
![PixPin_2024-01-05_11-34-32](https://github.com/mushan0x0/AI0x0.com/assets/42607836/eb7ec2ec-a7b2-499e-a050-2798063efb98)

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v2.1.7 先用这个旧版吧，下载exe后缀的文件

**Comment by iogeda** [comment]
> https://github.com/mushan0x0/AI0x0.com/releases/tag/v2.1.7 先用这个旧版吧，下载exe后缀的文件

好的。谢谢。请问是不是我系统问题？

**Comment by mushan0x0** [comment]
有可能是跟cpu不兼容导致的，我等会修复一下看看

**Comment by iogeda** [comment]
> 有可能是跟cpu不兼容导致的，我等会修复一下看看

ok

**Comment by mushan0x0** [comment]
https://cdn.ai0x0.com/versions/AI-0x0_2.2.5-alpha_x64.exe 你试试这个版本呢

**Comment by mushan0x0** [comment]
最新版已修复
