### ISSUE TITLE
更新程序提示卸载失败，随后发现主程序无法结束堪比病毒

### ISSUE THREAD

**Issue by Vinzelles** [mushan0x0/AI0x0.com#496]
先是更新版本提示这个
![image](https://github.com/mushan0x0/AI0x0.com/assets/67829622/c256c036-ab5c-4d0b-8742-221768355824)
随后直接到安装目录运行卸载程序，提示无法关闭
![image](https://github.com/mushan0x0/AI0x0.com/assets/67829622/03dee258-c4a8-4404-af0a-ef4a7ee5276a)
任务管理器显示有3个进程，均无法结束任务
![image](https://github.com/mushan0x0/AI0x0.com/assets/67829622/a3cd07b6-405b-461b-9590-698cb61bbcde)
使用杀软仍然无法结束
![f19a14e176823ef58aaa802782c95e93](https://github.com/mushan0x0/AI0x0.com/assets/67829622/58e47a3d-07ee-48fd-9dee-1655c4e81b54)
使用火绒粉碎主程序文件后，进程和上述问题仍然存在
![image](https://github.com/mushan0x0/AI0x0.com/assets/67829622/910a6e9e-0643-4c74-bae1-57e00254e657)

**Comment by mushan0x0** [comment]
重启一下看看呢
