### ISSUE TITLE
使用建议

### ISSUE THREAD

**Issue by Passerby1011** [mushan0x0/AI0x0.com#497]
有那么几点的使用感受和建议 ：
1.项目动画的流畅度，有非常大的提升空间，本人的轻薄笔记本，虽说性能不强7840，运行起来动画有非常大的掉帧，给人感觉非常难受，
2.鼠标随航的查询和自己创建的对话进行隔离，在使用对话时，使用鼠标随航的查询内容会混进对话中，给人感觉很难受，很混乱。
3.鼠标随航的查询建议只输出结果，有些文字我需要进对话调整，而有些查询我只需要一个结果，举例翻译说明，我只想知道翻译结果，不想知道你的提示词是什么，我使用时的感受，感觉是在提示词里找答案，答案不够明确
4.鼠标随航的查询窗口可以适当的做大一点，个人感觉有点小
5.对话中对于插件的调用不够积极，类似与联网搜索的插件，感觉只有特别明确的支持需要搜索他才会去搜索，举个例子：我让他介绍一下GPT4 Vision，此时应该去调用搜索里，他搁哪胡扯，其他插件也是这样调用的不够积极。

**Comment by mushan0x0** [comment]
感谢建议，后面会再优化
