### ISSUE TITLE
1.2.1.0更新后bug

### ISSUE THREAD

**Issue by yimi1943** [mushan0x0/AI0x0.com#50]
win11系统22H2，更新1.2.1.0版本以后，悬浮图标，一直在页面前端闪现，无法直接悬浮在页面最前端，也无法点击。导致使用体感非常不好。

**Comment by mushan0x0** [comment]
被部分窗口挡住了，近期修复

**Comment by canyanol650** [comment]
win10 用搜狗输入法 悬浮窗 不停闪动

**Comment by ShenShizhe** [comment]
> win11系统22H2，更新1.2.1.0版本以后，悬浮图标，一直在页面前端闪现，无法直接悬浮在页面最前端，也无法点击。导致使用体感非常不好。

哈哈哈，会蹦迪的图标！！！
