### ISSUE TITLE
AI0x0填入中转api后聊天失败，但是同样的方法chat0x0却成功

### ISSUE THREAD

**Issue by KingStoning** [mushan0x0/AI0x0.com#500]
1.   在AI0x0模型设置中填入了中转的api，无法回应问答信息。（图一和图二）
2.   当我把链接和API填入chat0x0时，问答能够正常反馈（图三图四）
总结，希望能够早日得到回复，我不知道是AI0x0本来就不支持还是出现了问题
![微信图片_20240129150708](https://github.com/mushan0x0/AI0x0.com/assets/157497163/d18d1be3-eb61-4b3e-8c44-e03e61b1abe8)
![微信图片_20240129150710](https://github.com/mushan0x0/AI0x0.com/assets/157497163/39e77037-e04e-43ea-a97d-551d576beeb9)
![微信图片_20240129151256](https://github.com/mushan0x0/AI0x0.com/assets/157497163/ecd3030b-69b2-4c9d-b99d-c2d4ec08b5b7)
![微信图片_20240129155101](https://github.com/mushan0x0/AI0x0.com/assets/157497163/4426fd8e-fb1d-49ad-8a3d-04607683040e)

**Comment by mushan0x0** [comment]
代理地址后面要加/v1

**Comment by KingStoning** [comment]
谢谢你的回复，都怪我观察不到位
________________________________
发件人: mushan0x0 ***@***.***>
发送时间: 2024年1月29日 17:05
收件人: mushan0x0/AI0x0.com ***@***.***>
抄送: KingStoning ***@***.***>; Author ***@***.***>
主题: Re: [mushan0x0/AI0x0.com] AI0x0填入中转api后聊天失败，但是同样的方法chat0x0却成功 (Issue #500)


代理地址后面要加/v1

―
