### ISSUE TITLE
请问有没有碰到类似的bug？

### ISSUE THREAD

**Issue by milky0919** [mushan0x0/AI0x0.com#502]
碰到过几次，气泡模式里查询问题或者翻译，它跟你说无法回答；然后过了挺久你问下一个问题时候，它突然又开始回答你最早的问题。

**Comment by mushan0x0** [comment]
使用的AI0x0模型吗还是Chat0x0

**Comment by milky0919** [comment]
> 使用的AI0x0模型吗还是Chat0x0

AI0x0、但是用了段时间后好像又没这问题了
