### ISSUE TITLE
自定义openai接口后仍然是chat0x0

### ISSUE THREAD

**Issue by pilcstp** [mushan0x0/AI0x0.com#505]
接口是`http://localhost:<port>`,  在ChatGPT Next Web 上没有问题

**Comment by mushan0x0** [comment]
后面我修复下

**Comment by mushan0x0** [comment]
应该已经修复了，再试试吧

**Comment by pilcstp** [comment]
还是不行

**Comment by mushan0x0** [comment]
你说的仍是chat0x0是什么意思

**Comment by pilcstp** [comment]
> 你说的仍是chat0x0是什么意思

改完apikey, endpoint, model。打开新对话问'你是谁', 回答'chat0x0'

**Comment by mushan0x0** [comment]
正常，这是内置提示词设置的
