### ISSUE TITLE
选择gemini模型问题

### ISSUE THREAD

**Issue by keen0309** [mushan0x0/AI0x0.com#508]
查询完了还在转动，点击旁边的叉号还是关不掉，导致不鼠标随行不出现
![image](https://github.com/mushan0x0/AI0x0.com/assets/103982843/55046837-8a30-4302-b5d0-abe4d4950c32)

**Comment by keen0309** [comment]
还是没修复，默认的可以用

**Comment by mushan0x0** [comment]
试试2.3.4呢
