### ISSUE TITLE
注册收不到验证码

### ISSUE THREAD

**Issue by iamlzh** [mushan0x0/AI0x0.com#51]
注册收不到验证码

**Comment by coressss** [comment]
我也是，还以为是我邮箱的原因，试了好几个邮箱也不行

**Comment by liuyuanjun520** [comment]
我也是

**Comment by 203430** [comment]
开发者说了，验证码端口坏了，在准备用短信验证码

**Comment by liuyuanjun520** [comment]
ke

> 开发者说了，验证码端口坏了，在准备用短信验证码

可是界面上只有邮箱注册呀

**Comment by 203430** [comment]
要等阿里云通过

**Comment by 203430** [comment]
![Uploading Screenshot_2023-03-23-16-53-01-011_com.tencent.mm-edit.jpg…]()

**Comment by 203430** [comment]
![Screenshot_2023-03-23-16-53-01-011_com tencent mm-edit](https://user-images.githubusercontent.com/128492148/227151553-cbb4df93-0359-494f-ad81-0d6929c6e20d.jpg)

**Comment by mushan0x0** [comment]
短信注册已发布了，大家试试吧

**Comment by 203430** [comment]
兄弟们快试试，能的话踢一下😚
