### ISSUE TITLE
插件“图表和图示”无法使用

### ISSUE THREAD

**Issue by ysdgithub** [mushan0x0/AI0x0.com#512]
插件服务端请求返回出错：
{
  "error": {
    "status": 500,
    "statusCode": 500,
    "response": {
      "ok": false,
      "url": "https://mermaid.pyxl.uk/generate",
      "status": 500,
      "statusText": "Internal Server Error",
      "headers": {
        "connection": "close",
        "content-length": "49",
        "content-type": "application/json; charset=utf-8",
        "date": [
          "Sun",
          "10 Mar 2024 08:17:09 GMT"
        ],
        "etag": "W/\"31-UXhAiTG0xn6Bvuon7m351Ci3gKU\"",
        "server": "Apache/2.4.52 (Ubuntu)",
        "vary": "Origin",
        "x-powered-by": "Express"
      },
      "text": "{\"message\":\"Request failed with status code 400\"}",
      "data": "{\"message\":\"Request failed with status code 400\"}",
      "body": {
        "message": "Request failed with status code 400"
      },
      "obj": {
        "message": "Request failed with status code 400"
      }
    }
  }
}
![image](https://github.com/mushan0x0/AI0x0.com/assets/97598202/22edf602-61c7-4dc3-b0c9-465dcfa8abc0)

**Comment by mushan0x0** [comment]
第三方插件问题
