### ISSUE TITLE
语音朗读没有任何的声音

### ISSUE THREAD

**Issue by MILKMILKKING** [mushan0x0/AI0x0.com#514]
选择文本进行语音朗读，以及语音输出ai回答，均没有任何声音，请问是还需要进行声音包的下载吗？

附：
语音朗读声音选择任何角色，都没有任何声音播出。

**Comment by mushan0x0** [comment]
现在服务响应特别慢，后面会换成openai的服务

**Comment by MILKMILKKING** [comment]
> 现在服务响应特别慢，后面会换成openai的服务
最近微软开放了TTS，能不能直接拿来用？微软的声音我觉得就挺好的了。

https://github.com/rany2/edge-tts

**Comment by mushan0x0** [comment]
可以的，后面做个备选

**Comment by mushan0x0** [comment]
已支持
