### ISSUE TITLE
ai 0x0 模型不稳定

### ISSUE THREAD

**Issue by KingStoning** [mushan0x0/AI0x0.com#515]
今天我使用ai 0x0 模型时，打开速度很慢，打开失败。一直在加载中（如图），不出正常页面。出现正常页面后无法输入内容
      我首先切换了别的模型，测试chat0x0正常，其他第三方模型正常使用，速度正常（如图）
     重装应用好，好了一些，但是仍然出现了问题，加载慢，打开失败。
     切换了网络，我使用的是手机开热点，切换了联通和电信卡，问题照旧
![屏幕截图 2024-03-17 225953](https://github.com/mushan0x0/AI0x0.com/assets/157497163/1d429a9c-fd55-48f3-a42c-95d0f88b57e8)
![屏幕截图 2024-03-17 225933](https://github.com/mushan0x0/AI0x0.com/assets/157497163/c8c1411c-9bf6-4917-af47-f6343e6c7812)

**Comment by mushan0x0** [comment]
今天使用稳定些了吗

**Comment by KingStoning** [comment]
今天比昨天稳定了许多，打开速度上有了提升，没有出现像昨天似的卡顿
________________________________
发件人: mushan0x0 ***@***.***>
发送时间: 2024年3月18日 14:34
收件人: mushan0x0/AI0x0.com ***@***.***>
抄送: KingStoning ***@***.***>; Author ***@***.***>
主题: Re: [mushan0x0/AI0x0.com] ai 0x0 模型不稳定 (Issue #515)


今天使用稳定些了吗

―

**Comment by KingStoning** [comment]
刚刚再次出现了问题，我比较疑惑，明明一个小时前是稳定的，但是用了一个小时后再次变得无法加载，我点击“设置”无法弹出设置页面。重新打开出现了这样的页面。（我的电脑没有开代理，重启后打开仍然是这样）

[cid:58c13192-90f8-487c-af01-0697c87067a6]
________________________________
发件人: mushan0x0 ***@***.***>
发送时间: 2024年3月18日 14:34
收件人: mushan0x0/AI0x0.com ***@***.***>
抄送: KingStoning ***@***.***>; Author ***@***.***>
主题: Re: [mushan0x0/AI0x0.com] ai 0x0 模型不稳定 (Issue #515)


今天使用稳定些了吗

―

**Comment by KingStoning** [comment]
> 今天使用稳定些了吗

作者，您好，今天下晚自习后再次测试，恢复正常。前两条回复是使用的邮件回复，图片未能展示成功，所以我重新发一下出问题时的照片，作为您的参考，祝您发大财
![屏幕截图 2024-03-18 162253](https://github.com/mushan0x0/AI0x0.com/assets/157497163/86d913eb-78a4-4fc7-9865-9ea6cfc9f5d9)

**Comment by KingStoning** [comment]
好的，谢谢你的解释

________________________________
