### ISSUE TITLE
能不能加个开关，可以关闭动画，太卡了

### ISSUE THREAD

**Issue by pythonlouvre** [mushan0x0/AI0x0.com#517]
查询输入框展开，鼠标移上去的下拉，查询结果框的展开这些动画能不能加个开关关闭这些动画啊，太卡了，而且影响效率，看个结果还要等动画泡完，蛋疼，CPU还狂转。

**Comment by mushan0x0** [comment]
没有动画也会卡，这个软件内存占用比较大，应该是内存不够用导致的

**Comment by pythonlouvre** [comment]
我这看到的是CPU狂转， 我CPU风扇噪音很大，很明显动画的时候CPU风扇狂转，占用率立马上去了，内存只有60几兆，怎么可能是内存导致的

**Comment by mushan0x0** [comment]
<img width="306" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/5c7dacfd-4ba5-4db6-a8e6-f6d644e00514">
模型换成这个试试

**Comment by pythonlouvre** [comment]
![动画](https://github.com/mushan0x0/AI0x0.com/assets/651199/29f2acbf-f652-43ac-a84a-600511007585)
还是一样的，我根本就没跟模型交互，只是界面交互，看上面的动画，多操作几次CPU就上去了

**Comment by mushan0x0** [comment]
好的，我看看这个情况

**Comment by mushan0x0** [comment]
https://cdn.ai0x0.com/versions/AI-0x0_2.4.0-alpha_x64.exe 试试这个版本呢，会不会流畅些

**Comment by Tsenghan** [comment]
用了240试了试，cpu占用依旧感人。可能Electron本身对老电脑不友好吧

**Comment by mushan0x0** [comment]
> 用了240试了试，cpu占用依旧感人。可能Electron本身对老电脑不友好吧

是的，主要是页面 dom 更改导致的 cpu 高，我试了动画关了也是一样的

**Comment by mushan0x0** [comment]
动画已优化
