### ISSUE TITLE
mac上，使用一段时间后，无法选定内容查询

### ISSUE THREAD

**Issue by 852569069** [mushan0x0/AI0x0.com#518]
![iShot_2024-04-11_14 54 23](https://github.com/mushan0x0/AI0x0.com/assets/30398478/ce66d1d1-5e0c-45b2-8840-94a3c10e6209)

**Comment by mushan0x0** [comment]
别的应用内可以吗，也许是pdf文件的原因

**Comment by 852569069** [comment]
别的应用也不行。

**Comment by mushan0x0** [comment]
好吧这也不是pdf，我后面修复看看

**Comment by 852569069** [comment]
谢谢

**Comment by mushan0x0** [comment]
2.5.0已修复
