### ISSUE TITLE
悬浮球的显示与隐藏能不能加个快捷键

### ISSUE THREAD

**Issue by jefferyhhh** [mushan0x0/AI0x0.com#519]
全屏看视频的时候又要费劲把它隐藏掉，希望加个快捷键方便一点

**Comment by mushan0x0** [comment]
你是什么系统什么浏览器，正常会自动隐藏的

**Comment by jefferyhhh** [comment]
win10，一般看哔哩哔哩桌面端

**Comment by jefferyhhh** [comment]
嗯嗯好的

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v2.5.2-alpha 这个版本修复了，你试试，应该会自动隐藏了
