### ISSUE TITLE
内置的lobehub 是否支持客户端模式

### ISSUE THREAD

**Issue by mingyue0094** [mushan0x0/AI0x0.com#521]
原版的是有客户端模式的。
![图片](https://github.com/mushan0x0/AI0x0.com/assets/63558866/2b0f9e6d-bb24-4261-8c37-0f07d40b7666)

这样，可访问内网的代理服务器。

找了下 ai0x0 的好像没更新这个客户端模式，请求都绕服务器一圈。

**Comment by mushan0x0** [comment]
后面会进行更新

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v3.4.0-alpha 已更新
