### ISSUE TITLE
最新的几个包，在M1芯片下无法启动，打开后就退出

### ISSUE THREAD

**Issue by linghongli** [mushan0x0/AI0x0.com#522]

**Comment by mushan0x0** [comment]
你加我我给你看看
<img width="453" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/cb56b979-2aa5-4cd1-af40-d1c84c6ac781">

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v2.5.4-alpha 已修复
