### ISSUE TITLE
建议在有数学公式的时候支持数学公式表达

### ISSUE THREAD

**Issue by SERGIO0903** [mushan0x0/AI0x0.com#525]
<img width="662" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/128696131/98dd82fd-62c2-4477-a8c7-7a6c7fd6aa17">
比如这里最好就能内置一个markdown或者latex读取器来读取这些数学代码

**Comment by mushan0x0** [comment]
<img width="627" alt="image" src="https://github.com/mushan0x0/AI0x0.com/assets/29084441/cf5f4616-4b2c-440b-8731-a1bcf09e88b2">
是chatgpt的语法问题
