### ISSUE TITLE
Chat0x0相关

### ISSUE THREAD

**Issue by milky0919** [mushan0x0/AI0x0.com#526]
用的自己的Key。
Chat0x0无论选什么模型都等于没选，实际用的模型都是gpt-3.5-turbo-16k-0613。
一旦切换到Chat0x0，再切回AI0x0，AI0x0的模型设置也被清空了。

**Comment by mushan0x0** [comment]
我后面看看

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/issues/460 类似问题
