### ISSUE TITLE
悬浮窗生成的代码块拖动问题

### ISSUE THREAD

**Issue by Kami648** [mushan0x0/AI0x0.com#528]
在用AI编写代码块后，在悬浮窗内滚动页面会乱跳，不方便复制

**Comment by mushan0x0** [comment]
可以录屏看看吗

**Comment by Kami648** [comment]
https://github.com/mushan0x0/AI0x0.com/assets/58800659/87f13ae2-456f-4b24-bb51-db85491397c5

滚轮往上滚动会往下回弹

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/2.5.8-alpha 试试这个版本呢
