### ISSUE TITLE
切换其他大模型，第二天会重置会Ai0x0问题

### ISSUE THREAD

**Issue by li1243893836** [mushan0x0/AI0x0.com#531]
软件版本  2.5.9-alpha（内测版）
电脑版本 windows10 22H2
描述跟标题一样，不知道是没有设置还是其他问题，希望有时间可以查看一下

**Comment by mushan0x0** [comment]
是这样设计的，因为推荐使用AI0x0模型，付费后会保留前一天选择的模型
