### ISSUE TITLE
订阅机制

### ISSUE THREAD

**Issue by 121yiayi** [mushan0x0/AI0x0.com#534]
由于不需要其中付费AI，重复购买性价比不高，希望作者大大可以有对于特定功能的订阅机制，灵活的订阅机制我们也更有付费的欲望

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/issues/393 如果有自己的key可以使用内测版，部分付费功能可以免费使用

**Comment by 121yiayi** [comment]
> #393 如果有自己的key可以使用内测版，部分付费功能可以免费使用

好的，正在使用内测版

**Comment by 121yiayi** [comment]
> #393 如果有自己的key可以使用内测版，部分付费功能可以免费使用

所以是不会出功能方面的订阅套餐嘛，新出的功能很想试试，但碍于订阅机制着实让我停住了脚步

**Comment by mushan0x0** [comment]
> > #393 如果有自己的key可以使用内测版，部分付费功能可以免费使用
> 
> 所以是不会出功能方面的订阅套餐嘛，新出的功能很想试试，但碍于订阅机制着实让我停住了脚步

是全屏识别功能吗，这个以后会出单独的额外次数包的

**Comment by 121yiayi** [comment]
> > > #393 如果有自己的key可以使用内测版，部分付费功能可以免费使用
> > 
> > 
> > 所以是不会出功能方面的订阅套餐嘛，新出的功能很想试试，但碍于订阅机制着实让我停住了脚步
> 
> 是全屏识别功能吗，这个以后会出单独的额外次数包的

对，还有那个字幕
