### ISSUE TITLE
软件崩溃问题

### ISSUE THREAD

**Issue by yida91** [mushan0x0/AI0x0.com#535]
使用ChatGPT一段时间后，软件崩溃且再次打开后也会迅速崩溃

**Comment by mushan0x0** [comment]
有开虚拟形象外观吗

**Comment by yida91** [comment]
开过一次，后面又换回来了。今天再开软件也是迅速会崩溃掉，是机器的性能不够吗？

**Comment by mushan0x0** [comment]
有打开记录回想吗

**Comment by yida91** [comment]
没有，需要打开吗？后面重置了所有设置，还是会在一段时间后崩溃

**Comment by mushan0x0** [comment]
<img width="227" alt="image" src="https://github.com/user-attachments/assets/2c68189a-30c8-4a86-8f12-e1db3d7fa14d">
不用打开，你微信加我我看看日志吧

**Comment by mushan0x0** [comment]
最新版已解决
