### ISSUE TITLE
deepseek的API怎么用不了

### ISSUE THREAD

**Issue by Wooden-Gear** [mushan0x0/AI0x0.com#537]
deepseek的API用不了，是不兼容他家吗？
他家接口跟openai是一样啊！

**Comment by mushan0x0** [comment]
是不是返回空白的，应该是接口地址错了

**Comment by mushan0x0** [comment]
<img width="1114" alt="企业微信截图_38806571-71ce-4496-b556-868e69f0b080" src="https://github.com/user-attachments/assets/62569073-b05b-4625-b8f0-22983186e1ef">
<img width="1037" alt="企业微信截图_3fa906f2-4627-465a-9e51-709a9d375726" src="https://github.com/user-attachments/assets/3811ac6f-8348-4cdb-a17c-0645d7d9e04f">
