### ISSUE TITLE
悬浮球消失

### ISSUE THREAD

**Issue by LinJHS** [mushan0x0/AI0x0.com#540]
在我更新到了最新的3.1.1-alpha版本后，发现：

- 在悬浮球贴边的情况下，当我将鼠标移至副屏（竖屏显示器），悬浮球消失了。即使我的鼠标移回横屏的主屏，悬浮球仍然无显示。
- 说明：在上述过程中，鼠标无点击，重启电脑and应用均无法解决。不确定旧版本是否会出现此问题。
- 解决方案：将悬浮球拖出来（取消贴边）后，重新让其贴边，能解决此问题。

注：主屏是横屏的（2560x1600），副屏是竖屏的（1440x2560）。

**Comment by mushan0x0** [comment]
可以先在横屏时勾选悬浮球上的固定屏幕看看，竖屏的情况我看后面能不能修复

**Comment by LinJHS** [comment]
我已经尝试过在横屏时勾选固定屏幕，但在移至副屏之后仍然会出现出现悬浮球消失的问题。

**Comment by mushan0x0** [comment]
不贴边的话是正常的吗

**Comment by LinJHS** [comment]
不贴边是正常的；将悬浮球拖出来（取消贴边）之后，重新将其贴边，也变得正常了。

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v3.3.7-alpha 试试这个版本呢

**Comment by LinJHS** [comment]
现在回学校了，没有两台显示器，试不了

**Comment by mushan0x0** [comment]
可能没问题了，先关了，有问题再打开吧
