### ISSUE TITLE
多屏下能不能固定一个屏？

### ISSUE THREAD

**Issue by bobo-shark** [mushan0x0/AI0x0.com#541]
我有两个屏幕，一个用来阅读，一个用来工作。当打开neural的时候，点击个屏幕，她就切换去那个屏幕，导致闪来闪去影响我阅读的屏。能不能固定一个屏？

**Comment by mushan0x0** [comment]
鼠标移动到悬浮球，勾选固定屏幕就行了

**Comment by mushan0x0** [comment]
打开了虚拟形象的话，右键人物，选择固定屏幕就行了

**Comment by bobo-shark** [comment]
哇！这么晚竟然回复了！
我刚刚发现一个情况，当我刚开机还没启动第二屏幕，是没“固定屏幕”这个选项的。（这样我就不能确定是不是因为昨天双屏状态下没这个选项了，当时找来找去没找到）
不过已经解决了! 现在有这个选项！谢谢大佬！

**Comment by mushan0x0** [comment]
哦哦不客气
