### ISSUE TITLE
大模型选择Poe报错500

### ISSUE THREAD

**Issue by w81481708** [mushan0x0/AI0x0.com#543]
大模型选择Poe报错500，使用Poe的网页版是正常的。
![image](https://github.com/user-attachments/assets/31342f49-d5e7-4184-a065-133dfdfa974f)
![image](https://github.com/user-attachments/assets/46711ecb-2332-45c6-8b11-fb09abd0e273)

**Comment by mushan0x0** [comment]
我后面看看

**Comment by mushan0x0** [comment]
500 错误未复现
