### ISSUE TITLE
使用鼠标随航，部分软件输入框选择文本后，影响复制剪切等快捷键功能

### ISSUE THREAD

**Issue by lawlietchan** [mushan0x0/AI0x0.com#544]
过程
1.启用鼠标随航
2. 在部分软件的文本输入框，用鼠标滑动的方式选择一些文本
3. 按下复制快捷键 Ctrl + C，会变成了c
4. 直接结果就是经常是在输入框复制的操作，变成了输入了 "c"
5. 这个在某些软件是必现的，比如Axure 和 Clash，不得已在这些软件屏蔽了0x0才可以正常编辑文本

环境：
1. 系统 Window 11
2. 软件 版本 3.2.0-alpha

其他的一些参考：
1. 之前我使用的Snipdo+Open AI translator的组合，Snipdo没有出现这个影响快捷键的问题
2. 后者的开发者其实做了选中划词的功能，但也是有很多问题，他是推荐用户结合Snipdo这个工具使用

**Comment by mushan0x0** [comment]
https://github.com/user-attachments/assets/ee55104a-0768-48c4-9163-f286e5809734

没有复现，你录个屏看看呢

**Comment by mushan0x0** [comment]
松开的时候马上按复制键是吧，这样好像会变成c

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v3.2.0-alpha 已修复，重新下载这个版本就可以了

**Comment by lawlietchan** [comment]
https://github.com/user-attachments/assets/51347db1-053c-4e04-8899-686ea1434236

你好，感谢你的修复，但我重新安装了新版本，还是挺高概率会出现这个问题。
我的操作是选中文字之后比较快就按下 Ctrl + C
我录了个视频，你看下是否能看出问题（为了显示按下的按键，我同时也用了一个软件，平常是不用的也会有这个问题）

**Comment by lawlietchan** [comment]
> https://github.com/mushan0x0/AI0x0.com/releases/tag/v3.2.0-alpha 已修复，重新下载这个版本就可以了


https://github.com/user-attachments/assets/b32f1f7a-992e-4aef-882d-9a37af4357c3


你好，感谢你的修复，但我重新安装了新版本，还是挺高概率会出现这个问题。
我的操作是选中文字之后比较快就按下 Ctrl + C
我录了个视频，你看下是否能看出问题（为了显示按下的按键，我同时也用了一个软件，平常是不用的也会有这个问题）

**Comment by mushan0x0** [comment]
好的，看明白了，我等会修复一下

**Comment by mushan0x0** [comment]
又修改了一下，你再下载一次 https://github.com/mushan0x0/AI0x0.com/releases/tag/v3.2.0-alpha 看看呢

**Comment by lawlietchan** [comment]
> 又修改了一下，你再下载一次 https://github.com/mushan0x0/AI0x0.com/releases/tag/v3.2.0-alpha 看看呢

你好，新版本这个问题的情况好了很多，已经基本不怎么会误触成输入c了
我还有一个问题，是在使用ChatGPT模型的时候，会发现无法发送内容去查询，可能我等下另开一个issue给你反馈看看

**Comment by mushan0x0** [comment]
好的
