### ISSUE TITLE
与 Snipaste 截屏软件冲突

### ISSUE THREAD

**Issue by LinJHS** [mushan0x0/AI0x0.com#545]
AI 0x0 版本：3.2.0-alpha
Snipaste 版本：2.9.2

场景描述：在同时开启 AI 0x0 与 Snipaste 截屏软件后，点击 Snipaste 的截屏，在选择好截屏区域后，Snipaste 窗口闪退。退出 AI 0x0 之后不会出现上述问题。

注：此外，微信截屏在选中截屏区域后，会丢失焦点，但窗口不会闪退。

**Comment by LinJHS** [comment]
找到解决方案了，在场景中添加Snipaste的“始终隐藏悬浮球和鼠标随航”

**Comment by mushan0x0** [comment]
好的，后续将自动排除该软件

**Comment by decetion** [comment]
> 好的，后续将自动排除该软件

你好，我发现AI 0x0与多个截图软件冲突，我实验过的就有PixPin，windows自带的截图功能，以及ShareX等，大多是完全一直不能截图，一直闪退，也有第一次闪退之后能截图的，但是截图的文件名称都会为"AI 0x0......"：
![image](https://github.com/user-attachments/assets/51984cc5-71e2-4c9f-a331-55fc50bf358b)
所以AI 0x0应该与截图功能冲突，应该解决它与截图功能冲突的问题，因为大家使用的截图软件比较多，排除截图软件的话应该排除不完

**Comment by mushan0x0** [comment]
@decetion 我实际上没有复现这个问题，包括 Snipaste，这是我用自带截图的录屏，你可以录屏看看闪退的情况吗

https://github.com/user-attachments/assets/35be4f4a-4400-48cc-ba6f-fc68c3c48af5

**Comment by mushan0x0** [comment]
这是 Snipaste 的录屏，都为发生截图应用闪退

https://github.com/user-attachments/assets/2b4f8d00-77ab-468e-b250-931aef56a4c9

**Comment by decetion** [comment]
@mushan0x0 这是我用windows自带的截图录屏闪退情况，是用快捷键win+shift+s：

https://github.com/user-attachments/assets/a5cacd00-fe14-4b53-9fe4-f80a0b83e1b6

这个录屏文件是使用ShareX录制，使用这个截图软件不会发生闪退，但是截图或者录屏文件的文件名都会变成“AI_0x0....”：
![image](https://github.com/user-attachments/assets/1c398506-d4ed-4228-9e69-44d1a4fce826)

**Comment by mushan0x0** [comment]
好的明白了，等会我会发个版本修复一下，但是文件名这个处理不了，这个是截图软件自动识别的
