### ISSUE TITLE
使用chatgpt模型，无法使用划词查询功能（网页不会自动发送消息）

### ISSUE THREAD

**Issue by lawlietchan** [mushan0x0/AI0x0.com#546]
问题：
使用chatgpt模型，无法使用划词查询功能
打开网页看了下，好像是无法按下发送按键（按键置灰），自己手动在网页输入框编辑可以发送

视频：

https://github.com/user-attachments/assets/c5477f68-e575-4581-9041-0d748b994fc6

**Comment by mushan0x0** [comment]
好的我看看

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v3.2.1-alpha 已修复
