### ISSUE TITLE
通义千问模型，悬浮球无法获取回复

### ISSUE THREAD

**Issue by lawlietchan** [mushan0x0/AI0x0.com#548]
切换至通义千问模型，网页已登录，但悬浮球无法获取回复，一直显示 加载失败 ，请刷新

![image](https://github.com/user-attachments/assets/2de03eeb-8a89-409f-80c3-c23be444ba57)

**Comment by mushan0x0** [comment]
好的下个版本修复

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v3.3.7-alpha 已修复

**Comment by lawlietchan** [comment]
> https://github.com/mushan0x0/AI0x0.com/releases/tag/v3.3.7-alpha 已修复

你好，感谢，但还是有问题
我简单试了下，看起来像是模型直接回答的回复可以获取到，
但模型联网之后的回复，悬浮球还是获取不到
![image](https://github.com/user-attachments/assets/79683cbe-3560-4bb6-8dcb-ca377921167d)

**Comment by mushan0x0** [comment]
好的下个版本再看看

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v3.3.8-alpha 已修复
