### ISSUE TITLE
软件打开后使用钉钉，钉钉的窗口会变白

### ISSUE THREAD

**Issue by 3471437753** [mushan0x0/AI0x0.com#549]

**Comment by mushan0x0** [comment]
应该是毛玻璃效果导致的，可以先关掉这个，下个版本会进行修复
<img width="347" alt="image" src="https://github.com/user-attachments/assets/e1cd5647-4381-42e9-b276-12343ca9a8ae">

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v3.3.7-alpha 已修复
