### ISSUE TITLE
问题很大，不能用邮箱注册，不能绑定邮箱，怎么用邮箱登录？

### ISSUE THREAD

**Issue by liujinping32** [mushan0x0/AI0x0.com#55]
问题很大，不能用邮箱注册，不能绑定邮箱，怎么用邮箱登录？

**Comment by mushan0x0** [comment]
最新版是用手机号了，但是登录界面的文字没改

**Comment by mushan0x0** [comment]
下载1.2.2版本试试呢

**Comment by Otiguy** [comment]
![image](https://user-images.githubusercontent.com/48633984/227236290-7513a117-1279-4a8c-baf5-84fcb09422ae.png)

**Comment by Otiguy** [comment]
可以了~😃

**Comment by KeepMovings** [comment]
![image](https://user-images.githubusercontent.com/56525775/227283467-417569dc-d233-4a30-bc89-43be503a10cd.png)

**Comment by KeepMovings** [comment]
手机收不到验证码

**Comment by zhlc0756** [comment]
还是发送不了验证码。1.22版本

**Comment by meesii** [comment]
app.asar 有170M，你都打包了啥进去，太可怕了！

**Comment by zhlc0756** [comment]
您好，您的邮件我已经收到。谢谢！。
