### ISSUE TITLE
系统自带记事本不停闪烁

### ISSUE THREAD

**Issue by FreeGAV** [mushan0x0/AI0x0.com#550]
请支持 deepseek 模型

bug：启动系统自带记事本不停闪烁

**Comment by mushan0x0** [comment]
deepseek 请参考这个 https://github.com/mushan0x0/AI0x0.com/issues/537#issuecomment-2254365781
笔记本问题下个版本修复

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v3.3.7-alpha 已修复
