### ISSUE TITLE
电脑长时间开机，悬浮球非常的卡，非常非常影响体验

### ISSUE THREAD

**Issue by esp3j0** [mushan0x0/AI0x0.com#551]

**Comment by mushan0x0** [comment]
你是啥系统，可以截图看看任务管理器吗

**Comment by esp3j0** [comment]
![image](https://github.com/user-attachments/assets/1c38aaa5-13e8-41a8-a1a4-38677fc15331)
win11

**Comment by mushan0x0** [comment]
这是卡的时候吗，看起来占用挺正常的呀

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v3.3.8-alpha 试试这个呢

**Comment by mushan0x0** [comment]
先关了，如有问题再反馈
