### ISSUE TITLE
悬浮球输入回车后ChatGPT无反应

### ISSUE THREAD

**Issue by Dreamslink0608** [mushan0x0/AI0x0.com#552]

**Comment by esp3j0** [comment]
看一下客户端是不是在设置页面，如果在设置页面，确实会这样。得返回聊天页面

**Comment by Dreamslink0608** [comment]
> 看一下客户端是不是在设置页面，如果在设置页面，确实会这样。得返回聊天页面

谢谢回复。客户端的确是在聊天页面。这个问题是升级了最新的内测版本出现的。升级前没有这个问题。

**Comment by mushan0x0** [comment]
应该是chatgpt升级导致的，下个版本修复

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/releases/tag/v3.3.8-alpha 已修复
