### ISSUE TITLE
软件无对话窗口弹出

### ISSUE THREAD

**Issue by ycbrisk** [mushan0x0/AI0x0.com#559]
对话窗口无法正常显示 
设置等其他界面可以正常进入
对话窗口一直显示  “正在加载中哦～ ₍ᐢ •͈ ༝ •͈ ᐢ₎♡”
版本3.4.1

**Comment by mushan0x0** [comment]
请问是哪个模型呢

**Comment by ycbrisk** [comment]
所有的，包括软件内置的AI 0X0对话模型

**Comment by mushan0x0** [comment]
没有复现，你录屏看看呢，重新打开也这样吗

**Comment by mushan0x0** [comment]
可能要看日志，可以加我微信看看

![image](https://github.com/user-attachments/assets/242a7e92-9ea4-4ad5-9dab-4a12afe13a92)

**Comment by ycbrisk** [comment]
好的，我加您了
