### ISSUE TITLE
Mac 11.7.2下悬浮框只能拖动一次，之后就会失去焦点，处于完全无效的状态

### ISSUE THREAD

**Issue by leebufan** [mushan0x0/AI0x0.com#56]
需要点击顶部show/hide之后才能再次拖动，但拖动一次后还是会失效，每次操作完就需要重新点击show/hide才可以。

**Comment by mushan0x0** [comment]
系统升级到13试试呢，老的版本没有兼容

**Comment by leebufan** [comment]
应该不是系统的问题，现在大部分情况下鼠标移入悬浮框只能下拉一次列表，在此划入之后悬浮框就假死了

**Comment by mushan0x0** [comment]
确实是系统的问题，老系统我没适配。。。

**Comment by mushan0x0** [comment]
https://ai0x0-track.oss-cn-beijing.aliyuncs.com/test-versions/AI%200x0_1.4.4.dmg 这个支持低版本mac了

**Comment by leebufan** [comment]
感谢，我安装试一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: mushan0x0 ***@***.***&gt;
发送时间: 2023年4月17日 21:54
收件人: mushan0x0/AI0x0.com ***@***.***&gt;
抄送: leebufan ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [mushan0x0/AI0x0.com] Mac 11.7.2下悬浮框只能拖动一次，之后就会失去焦点，处于完全无效的状态 (Issue #56)





 
https://ai0x0-track.oss-cn-beijing.aliyuncs.com/test-versions/AI%200x0_1.4.4.dmg 这个支持低版本mac了
