### ISSUE TITLE
显示乱码

### ISSUE THREAD

**Issue by Gooood-Xi** [mushan0x0/AI0x0.com#560]
![image](https://github.com/user-attachments/assets/68d9742d-c885-477e-874b-f4bc615ce6d4)
回答问题会出现大量乱码

**Comment by mushan0x0** [comment]
把随机性设置为1试试
![image](https://github.com/user-attachments/assets/a8964812-4c42-4c09-9056-9f8f6c31a3ec)

**Comment by Gooood-Xi** [comment]
> 把随机性设置为1试试 ![image](https://private-user-images.githubusercontent.com/29084441/393741262-a8964812-4c42-4c09-9056-9f8f6c31a3ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzIwMzMsIm5iZiI6MTczMzczMTczMywicGF0aCI6Ii8yOTA4NDQ0MS8zOTM3NDEyNjItYTg5NjQ4MTItNGM0Mi00YzA5LTkwNTYtOWY4ZjZjMzFhM2VjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA4MDg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MGI4YTMwNThiYjcxMTI3OTM2Zjc3ODg3MDA2YmQzNzVlYWNjMzk3NTQ4ZjRhZWFlYTRjMzU0ODc3Nzk2MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jsZQsIFcPKTU6S85f6y3D7zCJlh69-lpF_J8jU6nzFQ)

可以了，多谢
