### ISSUE TITLE
在使用时感觉卡顿严重（已解决）

### ISSUE THREAD

**Issue by nameless2024** [mushan0x0/AI0x0.com#561]
系统是win11，为笔记本，cpu是r9-7940h，gpu为4060，感觉使用时卡卡的，悬浮球会掉帧，打开的网页（试了GPT，通义，豆包）都感觉很卡，完全比不上浏览器的使用体验，好奇是我的电脑的设置问题么。

**Comment by mushan0x0** [comment]
把右上角毛玻璃关了试试呢
![image](https://github.com/user-attachments/assets/2e43e088-e2cc-4ec7-a95b-e764b120e19f)

**Comment by nameless2024** [comment]
感谢大佬答复，现在流畅很多！

**Comment by mushan0x0** [comment]
好的那就行
