### ISSUE TITLE
Windows 10 专业版（19042.870）无法下载

### ISSUE THREAD

**Issue by Pluto-wr** [mushan0x0/AI0x0.com#562]

**Comment by mushan0x0** [comment]
截图看看呢

**Comment by Pluto-wr** [comment]
![WechatIMG107685](https://github.com/user-attachments/assets/2d661766-36ad-47ab-b0a3-584cf96d8903)
![WechatIMG107688](https://github.com/user-attachments/assets/84b387ec-f5d2-4803-8174-9bbd664579e1)

**Comment by mushan0x0** [comment]
没有自动下载吗，win10及以上是支持的

**Comment by Pluto-wr** [comment]
稍等我确认下哈

**Comment by Pluto-wr** [comment]
sry。他看错了， 其实有自动下载。

**Comment by mushan0x0** [comment]
哦哦好的，那我关了
