### ISSUE TITLE
回答文本太多，一直按继续，会出现部分内容丢失

### ISSUE THREAD

**Issue by jeao729** [mushan0x0/AI0x0.com#59]
1....
2...
3...
4.文本文本（然后这段不完整）
5...

**Comment by jeao729** [comment]
也有这种情况：
1....
2...
3...
4.文本文本（然后这段不完整,）
9...

**Comment by 203430** [comment]
我也是

**Comment by mushan0x0** [comment]
这个是压缩token导致的，gpt3.5记忆不了那么长的内容，所以隔几次对话会压缩一次
