### ISSUE TITLE
功能无法正常使用，建议提供api-key减低压力

### ISSUE THREAD

**Issue by lny161224** [mushan0x0/AI0x0.com#61]
【Bug描述】无法使用chatGPT,文心一言，baiGPT的各种功能
【附图】
![image](https://user-images.githubusercontent.com/49985830/227400312-ddd969b5-c9f0-4436-982b-480f9e7efeac.png)

**Comment by mushan0x0** [comment]
用baichat多点几次刷新试试呢

**Comment by yimi1943** [comment]
确实，为什么不支持API接入？经常出现一会不用就要重新登陆，比较麻烦，建议新增api接口

**Comment by houchaowei** [comment]
求加入apikey

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/AI0x0.com/issues/104#issuecomment-1486120140 有的还没发布在内测
