### ISSUE TITLE
电脑双屏的情况下只能在主屏幕打开软件使用，副屏用不了。图标也拖不到副屏。

### ISSUE THREAD

**Issue by wh1213812** [mushan0x0/AI0x0.com#62]
电脑双屏的情况下只能在主屏幕打开软件使用，副屏用不了。图标也拖不到副屏。

**Comment by mushan0x0** [comment]
试试1.3.5呢，做了适配，win上不知道表现怎么样

**Comment by waterstem** [comment]
1.3.5，windows 双屏的情况下鼠标点击不到悬浮球，鼠标移动到悬浮球附近，悬浮球会消失，出现在副屏

**Comment by wh1213812** [comment]
好的好的，收到，感谢！



---原始邮件---
发件人: "Xiaolei ***@***.***&gt;
发送时间: 2023年4月3日(周一) 晚上9:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mushan0x0/AI0x0.com] 电脑双屏的情况下只能在主屏幕打开软件使用，副屏用不了。图标也拖不到副屏。 (Issue #62)




 
1.3.5，windows 双屏的情况下鼠标点击不到悬浮球，鼠标移动到悬浮球附近，悬浮球会消失，出现在副屏

**Comment by sammyzhang2599** [comment]
1.3.5 双屏要关闭双屏，重启以后 恢复正常，再开双屏。又出现问题。

刚才升级了，还有乱跑的现象，在主屏靠近会跳到副屏的最右侧，然后去副屏是能点击到悬浮框的。能操作了。

**Comment by mushan0x0** [comment]
乱跑这个是临时的实现方法，后面还是会做出拖动的
