### ISSUE TITLE
出现了ChatGPT error 429错误

### ISSUE THREAD

**Issue by luckyfengzi** [mushan0x0/AI0x0.com#65]
详细错误信息如下：
![image](https://user-images.githubusercontent.com/7686864/227440638-d21422a7-f2ba-4cf5-b347-7c8c86d447ac.png)

**Comment by dengtianhang** [comment]
undefined
[ChatGPT error 429: {
"error": {
"message": "Rate limit reached for default-gpt-3.5-turbo in organization org-3bkF85XWjvC3MxSxO295lCfb on requests per min. Limit: 20 / min. Please try again in 3s. Contact [support@openai.com](mailto:support@openai.com) if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.",
"type": "requests",
"param": null,
"code": null
}
}
]
