### ISSUE TITLE
经常会出现无法输入的问题

### ISSUE THREAD

**Issue by AppleJunJiang** [mushan0x0/AI0x0.com#66]
很确定光标一直在word里面，但是回答完了经常无法输入到文档中

**Comment by mushan0x0** [comment]
可以试试1.2.6吗，win好像不是wps有问题就是word有问题。。。

**Comment by AppleJunJiang** [comment]
1.建议在设置里显示版本号
2.文心一言，选中文本，任何模板查询无反应，无法发起提问

**Comment by mushan0x0** [comment]
文心最近改代码了，还没适配最新的

**Comment by mushan0x0** [comment]
1.3.5文心已适配
