### ISSUE TITLE
建议：刷新快捷键、界面尺寸保持、图标贴边

### ISSUE THREAD

**Issue by Sunshagon** [mushan0x0/AI0x0.com#67]
如题，
①因为网络的问题，会有刷新界面的需求，希望能有一个可以刷新界面的快捷键！
②每次打开软件，界面会恢复到默认，无法保持上一次的调整好的尺寸
③图标也希望可以贴边隐藏
另外右上角的窗口操作按钮，于观感上有些突兀🤣🤣
![image](https://user-images.githubusercontent.com/43169575/227447702-472f0e86-06a1-4ffb-9c3a-bc8e263a1d0c.png)
最后，十分感谢作者大大开发这款客户端🧡🧡🧡如有打扰，万分抱歉！！！

**Comment by Sunshagon** [comment]
> 1.2.6 贴边已经发布了试试吧

好的，多谢🧡🧡🧡

**Comment by Sunshagon** [comment]
> 1.2.6 贴边已经发布了试试吧

另外，大佬方便拉我进一下内测群吗🤣🤣

**Comment by mushan0x0** [comment]
qq群 575539890

**Comment by mushan0x0** [comment]
2暂不支持
