### ISSUE TITLE
兄弟 我开着翻墙 还得开着你的加速 那这个软件的意义何在啊

### ISSUE THREAD

**Issue by fufutech** [mushan0x0/AI0x0.com#77]
兄弟 我开着翻墙 还得开着你的加速 那这个软件的意义何在啊

**Comment by BXBhunnan** [comment]
而已今天卡的都上不去 我也开翻墙了 不如上个版本流畅

**Comment by fufutech** [comment]
开着翻墙 等着自己的chatGPT账号 还得开着他的加速  我就觉得大可不必    如果想收费可以换另一种方式

**Comment by mushan0x0** [comment]
自己有代理建议不要开这个功能，这个是给没有代理的用户准备的

**Comment by mushan0x0** [comment]
加了代理还开加速会加载不出内容的

**Comment by fufutech** [comment]
我现在必须 开着代理 再开着加速 才能正常使用  否则就用不了

**Comment by ShenShizhe** [comment]
> 我现在必须 开着代理 再开着加速 才能正常使用 否则就用不了

确实是

**Comment by mushan0x0** [comment]
> 我现在必须 开着代理 再开着加速 才能正常使用 否则就用不了

说明你梯子是不生效的，是软件的加速让你正常使用的。。。

**Comment by ShenShizhe** [comment]
> > 我现在必须 开着代理 再开着加速 才能正常使用 否则就用不了
> 
> 说明你梯子是不生效的，是软件的加速让你正常使用的。。。

不是呀，梯子没有问题的

**Comment by fufutech** [comment]
我梯子肯定没有问题啊 兄弟  我自己都能在chatGPT正常访问的

**Comment by mushan0x0** [comment]
> 我梯子肯定没有问题啊 兄弟 我自己都能在chatGPT正常访问的

好的我看看这个问题，有可能是跟本地的冲突了

**Comment by fufutech** [comment]
我再试试不同的节点 不知道跟不同国家的节点代理有没有关系

**Comment by ShenShizhe** [comment]
> 我再试试不同的节点 不知道跟不同国家的节点代理有没有关系

不用试了，一样的

**Comment by mushan0x0** [comment]
应该是跟本地的冲突了，等下个版本修复吧

**Comment by fufutech** [comment]
那等作者看看这个问题吧  很看好这个工具 确实便利很多

**Comment by ShenShizhe** [comment]
> 那等作者看看这个问题吧 很看好这个工具 确实便利很多

确实很棒

**Comment by mushan0x0** [comment]
1.2.5跟系统代理冲突的问题修复了

**Comment by fufutech** [comment]
我去更新下

**Comment by ShenShizhe** [comment]
真快啊，这个BUG解决了
