### ISSUE TITLE
几点建议

### ISSUE THREAD

**Issue by lanjinzhoucode** [mushan0x0/AI0x0.com#79]
1.能不能自定义增加配置吗，比如我可以使用国内的一些免费免登录的网站。
2.可以调用api接口的方法吗，这样就不用科学上网把。
3.咨询一下你自带的加速会一直免费吗，你可以增加加速器收费功能，因为我们本身自己也会掏钱买的，如果你这个稳定，我就可以在你们这里买。

**Comment by mushan0x0** [comment]
1.2.5版本应该加速比较稳定了

**Comment by mushan0x0** [comment]
2已支持，1暂时不做支持
