### ISSUE TITLE
部分功能问题与建议

### ISSUE THREAD

**Issue by rightgood2023** [mushan0x0/AI0x0.com#8]
1、悬浮球，能否加入一个快捷键功能，以便可以随时隐藏起来？
2、当前每次都有Donation的提示，但是点击没有反应。mac os环境。
注：除了捐献，如果收费，能否按周、月、季度、年的收费形式？
3、能否加入自定义openai api接口？以便可以连入自己的api？
4、我不想要用麦克风功能时，能否不要每次打开都跳转去面板设置？其它功能也是如此。
5、在word中生成时，需要按快捷键option+q，然后就在悬浮球那里还需要再按一次回车，这个过程有些繁琐，不知是我这边的系统问题，还是这个bug。我看网站的视频演示中看到的是，直接在word中生成出文字，没有这个需要回车确认的过程。

**Comment by mushan0x0** [comment]
1.后续会添加
2.现在没有要求捐赠，捐赠提示是BaiChat的，https://donate.theb.ai/ 可以在这里对他们进行捐赠
3.暂时不行，后续也许会添加
4.不太清楚具体的意思，可以再解释一下吗
5.因为需要选择不同的预设，所以需要回车确认一下，后续也许会添加预设的快捷键，就不用回车确认了

最后你的反馈，你的建议我都会认真考虑的🙏

**Comment by rightgood2023** [comment]
关于4，是这样的问题：
启动应用时，选择了给应用开通了不同的权限，但是其中麦克风功能不想要，不给设置这个权限。这导致每次重启应用时，便会弹出go setup的弹窗。能否默认不强求开通这些权限？只有当功能被应用时，再检测是否有设置了权限。

**Comment by mushan0x0** [comment]
明白了，目前主要精力在开发功能上，所以授权方面没有考虑那么细，后续会改进的。但是这个语音功能可以放心使用，因为不会联网，用的本地跑的AI模型实现的🙏
