### ISSUE TITLE
ai0x0无法使用

### ISSUE THREAD

**Issue by sughljt** [mushan0x0/AI0x0.com#81]
已经登陆了账号密码，而且使用成功了的，但是还是提示You need a valid user and password to access this content.

**Comment by mushan0x0** [comment]
1.2.5修复了

**Comment by sughljt** [comment]
您好！您发送的的邮件已收到

**Comment by sughljt** [comment]
好的，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月25日(周六) 中午1:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mushan0x0/AI0x0.com] ai0x0无法使用 (Issue #81)




 
1.2.5修复了
