### ISSUE TITLE
更新之后不能使用

### ISSUE THREAD

**Issue by gsp0708** [mushan0x0/AI0x0.com#83]
401 Unauthorized
You need a valid user and password to access this content.

**Comment by mushan0x0** [comment]
1.2.5恢复了

**Comment by nx2008** [comment]
升级完1.2.5还是不能用“加载失败”

**Comment by mushan0x0** [comment]
开启网络加速，多点几次刷新

**Comment by nx2008** [comment]
> 开启网络加速，多点几次刷新

刷新了很多次了，加速也开启了，始终是加载失败，你应该能看到我的IP请求

**Comment by mushan0x0** [comment]
有缓存，点刷新点快点，就能刷进去了
