### ISSUE TITLE
更新1.2.5后 不用的  

### ISSUE THREAD

**Issue by HuiGu13668** [mushan0x0/AI0x0.com#85]
加载失败，请刷新。

**Comment by mushan0x0** [comment]
开启加速，多点几次刷新

**Comment by HuiGu13668** [comment]
收到 开启后，刷新后可以了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mushan0x0/AI0x0.com"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月25日(星期六) 下午3:05
***@***.***&gt;;
抄送:&nbsp;"Alienware ***@***.******@***.***&gt;;
主题:&nbsp;Re: [mushan0x0/AI0x0.com] 更新1.2.5后 不用的   (Issue #85)





 
开启加速，多点几次刷新
