### ISSUE TITLE
为什么baichat不能搜图片呀

### ISSUE THREAD

**Issue by 1115346167** [mushan0x0/AI0x0.com#87]
![Uploading image.png…]()
上午还可以的

**Comment by mushan0x0** [comment]
你传的是啥图片

**Comment by 1115346167** [comment]
这个是我截的图片，显示上午搜的内容可以搜到图片（下午就提示  很抱歉，作为一个语言模型，我不能提供图片。但是，如果您有任何问题需要我的帮助，请随时告诉我。）这么一句话了

**Comment by mushan0x0** [comment]
这是正常的，它回答内容是随机的
