### ISSUE TITLE
Google账号注册的GPT登陆失败

### ISSUE THREAD

**Issue by ZhaoMfff** [mushan0x0/AI0x0.com#91]
我在注册chaGPT时选择了谷歌账号注册，使用此软件登录GPT选择Google登录会直接报错显示网络不通页面

现在市面上流通的第三方基本上都是基于key调API，看了请求是3.5模型，可以说流畅，我想了解直接登录GPT和key调api的区别

**Comment by mushan0x0** [comment]
后面会出调用api的
