### ISSUE TITLE
BUG:Notion中无法出现鼠标随航       建议：预设顺序可调或配置快捷键

### ISSUE THREAD

**Issue by meishiwanwan** [mushan0x0/AI0x0.com#94]
1、Notion中无法出现鼠标随航，快捷键可以
2、建议可以调整预设顺序，最好可以配置预设快捷键
3、建议出结果后有复制、替换、填充等按钮，类似BOB，出结果后直接复制等
方便在仅查询时复制使用
4、暗色模式，键盘上下选择提示不清晰，
5、上下选择，备选预设名字针对不同长度没有适配好，希望可以固定“已选”预设名字的大小，不至于跳来跳去

**Comment by mushan0x0** [comment]
1.4.2可以看看1、2、3还有问题吗
4和5现在已经支持鼠标选择了，更方便些
