### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by whckcs** [mushan0x0/AI0x0.com#95]
现在体验不怎么好，把跟随关了还是会跟着你鼠标动，跟随开了时跟时不跟，好像开不开都一样。还有几乎每次选中文字后ctrl 1打开显示的还是上次选中的文字，要么就是选中文字后选择任何一个预设都没反应，这两个问题发生概率为90%。

**Comment by whckcs** [comment]
哦，更正一下，原来跟随是指悬浮那个放大镜，如果开跟随用放大镜的话基本没有上面两个问题，那两个问题主要是用快捷键后出现的。还有希望网络加速能稳定一点，弄成付费的也好，主要是开全局太难受了。

**Comment by Exile008** [comment]
> 现在体验不怎么好，把跟随关了还是会跟着你鼠标动，跟随开了时跟时不跟，好像开不开都一样。还有几乎每次选中文字后ctrl 1打开显示的还是上次选中的文字，要么就是选中文字后选择任何一个预设都没反应，这两个问题发生概率为90%。

+1 全局快捷键得选中新一批的文字才不会出现上一次的文字

**Comment by mushan0x0** [comment]
应该是启动的时候卡了，导致跟着鼠标走了
